### ISSUE TITLE
Jameson, we have a problem.. Failed to import ship

### ISSUE THREAD

**Issue by morpe** [EDCD/coriolis#598] opened 2020-07-27 17:36 UTC
**Browser:** `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36`
**Path:**
**Error:** Unknown
**Details:**
**scriptUrl:** `/import?data=H4sIAO0NH18C_-1aXXOjuBL9Ky5e9sWmQHznLROPN5lxNpk4NVu1W7coGWRbN4C4ApLxTs1_3xYQA_5CcXIfUhU_zMRYOjTq091HLX4q1ywsIpIpZ3__VD4nS5oQwmmyVM5-Kp-igqTwJb8aK2c6cm3HMGw0bK7_gWOinCl_EpyyxJ-woMhIqAw3OPDb_YoMxk8kiuBb84MANDRNdzW49iOFO8YkyXH0ebEgQQ7TspQEFEf-UwXNcU7YYkE5UfZN8KcswBEVNz9Trosop6OM8EeWwegpeSQR3G0onpQuKOHVs07xXFxXbtkT4WOOn8qxWXaV_c4Y4OhD5YZTMBdH3zE8MFxRbXuobL44pvFr2OCMcYyX5JbwGQlYEm6haTtoSFMd13Q9fQOJdBWZFkJtVFg-HuNoynAoYZ_TNs_S20DnPGYFvyUJyWExKUt6DbSQqm3wPEO1PPi4bcxr_IPGRXyHkyXphQN3ay1ASzPhaxvtDnx8s5hUPu5ZO9V2XbdxBgJnuKau7_pjgqMIiCNnotWx0BUGwsfWf_1nqHwrgGD5WqwsWK1c5SSGm6zS3E-LKCMRBsLNC57l_oL-IKEfYV7e8SZRznJekKFyyynjJQTcYxYxQfOpGHWJeZgyCCddEQ9wHsfsKrmIaCqCblh_v2RpKgJKR9qwN05dpAmqHojTKV2u8j-J-Lcbq1P6z-BuHe6LVK03UkOOl35cJFSQK-sPUwi55eC6Nb4OVP1QoF7jLOuNAbPlQKR22HqV5GRZOqCXB3oLBVjgCOZ7x1kQ8iJ5iGmWUch0OHioaRCTkBZxLw-uy2Hvhggfrtq4Cn246r24yth1laZt-wqV1_qFkKUfFkKzFeP5c8lpayEWDn4TgugTlIuc8N8G18G3gibJru-Q3ZdvcZEzPwJdULn-eLI9h8GD6fPgPkn0UinjqrZuGa7VqA8DKqeHDLRbkHvBdFWsbCO5PP1kQQT129tAaaquna5ezK56Qa74epy7sdChAU4SYERF2wwMB8eFjzgJSp18nL4zMfxYTfhg7wd73wl70Qd7P9j7btlbKYd-YjrCD9vEnK0oicJPjAna-V8BAkzrknNMQzr4DvtfWN59jNQ0CSVXI9-RjGa5eMrehW2vqq16lR7b9vfJiCNtDyTESsQy-kheDXrU_1m55vN6zTP6D9H8AAI_s3o9f0-T9bGiuyPutc6dgxVeLCJcJAEsnp8D2MvuiGSp5vVSrXbfCVQ7mvy6a_vQ8Pl4GpwwHojsy4IHic3-mCwIcOP5x-rBys5eGtE6kfZ018pnMZt05qquuNKh4-tiBminAxXtt4sZ-_2HjFkSuAbO1yn54Rt-AF5PaX4ASW_S7oqmF_XYFkwsetSYB5gv2RyvQ8b4ASi0gboQgy9xHqwkI8o2zN2Iqtqm_nlTN1qxNCMRScjgC8H7VITeqyIq7GAFe9y1RMOMkHRwG-FcPMImgqxXbewdt0UUw4Kavd3j3QrES4KjfPWSQLQ6tdvyQAqIpurronC0G98jsN6GK9bbRaOOVNPcXpBTwnFkeFUMNi3rEUKq5YC96HBYPkdPTZQlBw1p9MZQRVnZMmK7u6Qvj0SAaUnuV7Vki_fXEIps8O0JmLqH970FJBXwaQkfiYbW06atdTwAZjmnUHPDwZg9JU0EmK-KANRxuNs9kpBvbumo3SPzPBVp21wsV_UCpziQAURWBdEcDxmGaunA8M6pE8RjDktFAwpRupZQ5WZLlJvuYe4BG9qOEvXAPl4PGgY2_JFNvdYeFlbT_DHl5XK1-HfL2QIek_HBLZi-L_eiPg6SCpw9El7u40LJA4sxh8jPJMh3KnV0DTKk8Lyxwx2pQ0pHtZok46qG3sm01TrdpDmF_c2e-NhjnWl2U6Jnd2NkAwl71gUTqlIiIeqdHZ1ugKHimZ1dYEFwcTIocfpptHrUumkd53ZNAAlet_rJmCaVVZkssb09mmIyGwOxkuWeLsWERFSkh8EE84zsPTLvTa-LLPRXBD9KSArBgME1TvCy3Zuw3i6hIvv0hKp1j59d0QYwTwsKTbVbac_uyGvwxoviQesIGt32UHky7tjH-baCWs5DkT1KzlmynJtwIA3I4kVeph4Z3jmGborXCrZ5d02z4MhBEtx68AVGZmxfRjXe6iyprThN1TyNHa7dQnEcVXDjmJKipdaAolGkKeN52wWo_5AeJs6qibKqynAOqKoxSEZO50XOuH8JTphw8r-iLt1v99ZMWbjD1q2CRnb0pISLqBAbwEEtVBiXeYem6r1m0uKmE0IWUg2xM--8vVEj3pFgVb9I0YOootYm2nR0D-3WEnkDxVaoEV62atv2VvKpEaUNNFoGGqrnIqdj4GwNqx6_pYE14qsM7FeHbZK9qJZuR4NUYjM129mT2GYkATF4OLVJVtU-lp9wVA67oRMznN0GMs3n0_K2g8unvhfOzWcBTs6TZSTzGlZnO652ZZKmerbddXNW3iYrvWvKpsw7HGLe7uAIpEVBItgvP7Sh-rezE5h1D7MkUy_IhEN90d9JQjgWTN3bGZ0SOrhYkaLsrmzzA8l1Rf9f7dAX6CbD7sgTo9xGds9xNssBO2rQwflKTo2Jj9tA6_Zz2X1VK2e3NWIKRaV73is7Oft6RG595Xhmq3y53NDlRYlN_Kfp_kzM2Y6AZYEhY-IEJHq70SoJivaDirDKAsbSEst4kZ1GCWlsQ86L5XI9x-sSEckGfYlol4hoGxGEF-EBL4D9gAUu7O3flmhOiaa30UICQeTPSY79nIgl7M0gYzFjDwa4nyR-to5TnK_AMJBJcljoENaqgDjlphxKZ9Wr7WgA2ovFNCtf0PX5wXPKBqnKUxcsem751XgpbFXz_7K5_9xDjCmQHfO1_0jnXHR0GK-3nz29HAH0hc23HSraQuCDNOUMB6usoLkEVjWHr8_rabNyWgs5gXwNyDkRMZjS0J9HuEyQ_ccGV2PtKFLIinkEQgA2_U8rGWsrUH0_aMpxIE6YI4hKeRtFOdL6AI0X2CcAOxY-MhqQVLwp90jqenEc5TvkUBJ9F9PaONV79y_nY6Xbn_kIWVZY2bSylWG9rJDl9frvULSRQV3df7Wm43rA84715v7m681odj49_2P8-W4kfoZKWY4XbyGwQuQR2LxDIsCxuA8CxTXSnBFy7nUH9M2Zpv-l_PoX4xETUuYwAAA%3D`
**line**: 0
**col:** 0
**error:** {}

**Comment by felixlinker** [comment] 2020-08-07 19:49
Duplicate of #597; your URL was too long. Nothing we can do about that really except better hinting towards this in the error message.

**Closed by felixlinker** 2020-08-07 19:49 UTC
Labels: bug, investigation-needed, reviewing
