### ISSUE TITLE
Setting PIPs not working as ingame

### ISSUE THREAD

**Issue by xamidi** [EDCD/coriolis#616] opened 2020-11-24 06:14 UTC
I noticed that setting PIPs does not work the same on coriolis.io as it does ingame.
For example, using ᐁ ᐊ ᐃ ᐃ ᐃ results in (2, 4, 0) ingame, but in (1.5, 4, 0.5) on coriolis.

**Comment by alex-williams** [comment] 2024-05-15 08:46
Closing as a duplicate of #655 as the pips function needs a re-write and this will be covered under that rewrite.

**Closed by alex-williams** 2024-05-15 08:46 UTC
Labels: bug, beta, cat:ui, duplicate
