### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by Agh42** [EDCD/coriolis#302] opened 2018-06-08 05:35 UTC
Just received this error message.

Browser: Mozilla/5.0 (Linux; Android 5.0.1; GT-I9505 Build/LRX22C) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.158 Mobile Safari/537.36
Path: /outfit/imperial_cutter?code=A2pptsFplxdusCf62c0o0o0t0t0t0t040404040404040407074f050504fr2dm93224.Iw18ZFA%3D.CwBjwRgkGY%2FmAmRFlWiDnyKA.H4sIAAAAAAAAA42SO0sDQRSFr0l23Tw3u3kQJT6zWliIik1AsFJsBEEbu1QWYmOhpBBsUlhYiIhapPAHWFiksLCw8EdYiAQLCSIiFhYa53hvINPJuMXhLN%2BZOzuzh5RNRD8WS%2FuYJT7rECUTCvCcXiK%2F9gIED4zRo%2BZ1cp%2FFuYsSuXOfQP7CZR5Sec13WdyVbyBbaAM54YVWmKh0kOFkWPXrZFWSwRfgX8eJsns5Tna2i6hpCUWEV96ZN54AWKqsl9ZYovKlsROPaETcqLgxcePiYKtKN%2B5WX3nIbROYlG%2BGo9b1pA0WS1bZax9AeoZfi%2FVnYOAyyUOiarWbtCp8ZnvrDSiIlI5aPClm4HEDTxh40sBTBu6qBX3SutyE3K8%2FtcM3Lb9wqLnJh0z%2FJ%2BSpJR06k7J0eiISHMaY%2BwaeMfCsWtT8XHNBgTjkDOvzBt6nljXfZglJO%2B0r7li8zO30Hlly9yne7oa7j0E1oeOnMq7BNjVc5KQ4X2odiAPoj%2BcX6qz9m18DAAA%3D.IwOgrA9KkMwQDBAbAFggJmHAhgO2wMYD2uAJthBgOxZA
Error: Unknown
Details:
scriptUrl: https://coriolis.io/outfit/imperial_cutter?code=A2pptsFplxdusCf62c0o0o0t0t0t0t040404040404040407074f050504fr2dm93224.Iw18ZFA%3D.CwBjwRgkGY%2FmAmRFlWiDnyKA.H4sIAAAAAAAAA42SO0sDQRSFr0l23Tw3u3kQJT6zWliIik1AsFJsBEEbu1QWYmOhpBBsUlhYiIhapPAHWFiksLCw8EdYiAQLCSIiFhYa53hvINPJuMXhLN%2BZOzuzh5RNRD8WS%2FuYJT7rECUTCvCcXiK%2F9gIED4zRo%2BZ1cp%2FFuYsSuXOfQP7CZR5Sec13WdyVbyBbaAM54YVWmKh0kOFkWPXrZFWSwRfgX8eJsns5Tna2i6hpCUWEV96ZN54AWKqsl9ZYovKlsROPaETcqLgxcePiYKtKN%2B5WX3nIbROYlG%2BGo9b1pA0WS1bZax9AeoZfi%2FVnYOAyyUOiarWbtCp8ZnvrDSiIlI5aPClm4HEDTxh40sBTBu6qBX3SutyE3K8%2FtcM3Lb9wqLnJh0z%2FJ%2BSpJR06k7J0eiISHMaY%2BwaeMfCsWtT8XHNBgTjkDOvzBt6nljXfZglJO%2B0r7li8zO30Hlly9yne7oa7j0E1oeOnMq7BNjVc5KQ4X2odiAPoj%2BcX6qz9m18DAAA%3D.IwOgrA9KkMwQDBAbAFggJmHAhgO2wMYD2uAJthBgOxZA
line: 0
col: 0
error: null

**Comment by razor81** [comment] 2018-07-11 00:11
I also experience this. In my case, it happens consistently when the phones orientation is changed on the outfitting page when a tab with a graph or chart is open: profiles, offense, defense tabs cause error on orientation change, but the power and costs tab doesn't, the orientation change happens normally.

Info:
Browser: Mozilla/5.0 (Linux; Android 6.0.1; ASUS_Z00TD Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36
Path: /outfit/krait_mkii
Error: Unknown
Details:
scriptUrl: https://beta.coriolis.edcd.io/outfit/krait_mkii
line: 0
col: 0
error: null

**Comment by willyb321** [comment] 2018-08-03 22:45
Duplicate of #208

**Closed by willyb321** 2018-08-03 22:45 UTC
Labels: bug
