### ISSUE TITLE
Crash when adding Ammo Capacity to Point Defence

### ISSUE THREAD

**Issue by natblundell** [EDCD/coriolis#276] opened 2018-05-08 17:12 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
Path: /outfit/beluga?code=A0pktpFplCdpsnf71b1b27271b030004040404p13cmememdmdmcmb022i2f.Iw18ZJA%3D.EwRgDB5iO9sgMzBa1Q%3D%3D.H4sIAAAAAAAAA2VSOy%2BDYRQ%2BvdKWfJdevErrViISVQYJQw2ug7lhkEjHDmJnEL%2BATUwiRoONSCdWEWMHg0SZEEGqcXmP5wz92sQ3PHnf8zznOec95yPdRES%2FPkBoxEPUupggss7dRKk5ALv0lPAuQOzEi4Bbx2oJxswvcySrmaMDLUTqHHzfdRgij447orUKs500iMJHcIns2VDmAlDGGZ9Xj4rSK8qbFyjXHxD16YlafnAL1oHNH%2BYegV659stpQE7s16v1dsrIV%2FfM6eMPmDTr5Rrlu%2F1m9s%2B8M5vDuCaybUgNNPCFL%2FBvyDIKaM3sFlFFQRTUSzXRj0eUFyaRv2ih%2F6tPtP%2BI13GoLvJmqmi%2FDN5%2FiJf2qShMWhoq5aSS7XRyiE7UNrpjQ887m5gGGnk4WUVMRnXipak0Ymw2iHKgLAF7B4NVW1hkSq5dB0Fkm6jDVoN8V%2BSXYpcRu32cjIgUtvWsM8IxoBLoio9DdIoYh%2FWiw589w3QBG7dLr9h9CUWik%2FhP1BOuqXVMiCM66Wz0Lg2qOoRop16RqIzQzncQtW8MIsr0%2F%2FsD%2BxdmEZICAAA%3D.EweloBhBGYA4QIKYEMDmAbJIYT0A&bn=*%20Yu%20Horl
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.a2acc7.js
line: 17
col: 21674
error: {}

**Comment by willyb321** [comment] 2018-05-10 20:33
Duplicate of #272

**Closed by willyb321** 2018-05-10 20:33 UTC
Labels: duplicate
