### ISSUE TITLE
Coriolis told me to...

### ISSUE THREAD

**Issue by malkav73** [EDCD/coriolis#669] opened 2021-06-24 00:54 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAJ7X02AC_81ZbW_jNhL-K4Y-ewVS7863JN406SW3aWxsizsUAi3RNi-yqKOkJO5i_3uHlBtTsmPKXheoEeRFER8NOfPMPDP6Zj3wtM5oaV3895t1uVrxu_w6Y4V1gZ3h5u9bXhRUWBduMLQ-5wuWUypYvrAuvllXWU0L-KO6G8sVURC6Xjgabq__m6yodWH9SknB8_iWLZbXpCAJq9bWFgxuuGd_DJ7WKfy-vSwxXYRQhODaG5jAVjSvSPZ5PqdJBYvKgiaMZHG1pGIFPxNSJiSl1r7b43uekIyVNIWF02bB4Pp9wT19oZl14Q_lebA5o6I5kXsyk9etB1KW6rayvCt_4hxQ8ND6IhiYSrKvBPZrXXg2WLr5Hdne9-F2_V1e0YVotq2DoB0QH2soTgfmkb9SMRbk1WgLth3NllGgo4zJiizoIxUTmvA8NZqEXduVH-8dEXt2hL0It2FZWQk2qyvez0RkO55mI_ZaW30iFf0yv2GCGu1DjXmuBuaGyA11OBnKMrAn7A8zYKC5ADs26gI9kDe2qlfmg4s0IBdQv_8-tH6pIQ4hEMBFAGzdVXQFsMuiimekZMmKlSXLqCDJczxnbzSNVzRl6mFfcuuiEjUdWo-CcRVN8qGTjEs2PKjbbolICw7Mw5a0Wmc06hIa9eNz9DfwecM372x8C9peOo0o2HZHzo8wxfF18oY2DhyMnJPD2tci2vdcx3NODmkZxlvLfiCmA_3UMQ47QY3saBS47bhO69VsDjv-KLRjkr6QPKHpsTHuqBjfPImURZzw5Llg1Qc4-B1nsmTF9eZeDWIlayERCRELPiPrlHNhNOla3nxLqmSpkMyECjxvl1CXYsVrEd9S8rIe1102TWhGczr4mZJ8l08QYYb6SBpwVSZZYi6PT3SewTX2QgePGankVswVckznFHz41z9hJ1m1fKizihUZU3ngcFyFI3skPxobXah-IR5Fvh6r_4K9Vyx5oiWUGxk1RuRPUEWR_GyrzScoaeppkQ49bQ7oCGjULhT-DiScdMZLOMlj7HU3RxFs7XWdzel8XEFk_G88vRCgarCRBU3Q9QzbMNij61SahRjJq_iK87JSFNYC9xbIPpiSnO0pAyNkDqr-sinUXeGDK3aqgVaojkiVOLBDdfI6HgR3BbxhCYOQX_cQOrrO8T92IRxsXEhbC3WkJSR2N04yqIW-0ZlbV_TNQ_sc2iyLp3XedeX1MuN0MKEpBPKuN-HLkIRog5yBZKheqfxuTkQT0JMgVdLBmL_mf4dKd-3gNJXeqoK-a4cBRLRzmgIBI0bvWJ7tRKglhJuT_lJUDFqWPTvcNc7FLRkSuW02vAOCrplzaIT6JCWM2rkuaiuIBlPyQgqcHqJLF-u-c5gSm9CRdPAaOjhmpUBY3hhV9uXDaE9dvpmMISLzxRPJF7RNiM_ZC4Ps9kBEVdfPu5TAgYkS8zKNl7Lim5kg_Q6PykGNinMRwdE96nQEdH8q4BZOGNpO2M2X_bmA7EALjKCFAhWmmsIRmaOrtbH2vsChx1AJI78V95EfQI8wGrW5DqC9Qx-6Ai3_OLaHVOY4SIDlGoIjFSAjFAn8wzVhS4IbAVEMWndejeXiPkQIXeyN3F0iPLAyie9l2v71PXlvuXDFsmwwrUW-t-HD20rvni1141MHLKFe3sG7biPaDjogY3Na1kXBRXVcGrqHhZNmYV-d5X6ks7T5iuq8bwT9f70RIJovQMUOxq80y_b5AhuHaUp_pNqj_tEVuxlElL21neO12-BdbbdBfKLJEjo7c2F0tIwFOiDcrYr9rcNhW3niPXW7v2VYk50Q866ONVmDWF-dy7IN2umWmRWxHpFHMbBLnV5J0EPAxF0aTmhewvM_TINTBhV6cANkB_28p1MP0ZkYEbUS4YkaNmxVoqgtEputTqU7q0lC8st8kZkd66I2vQy9TqkeUupFzezQJ5ISoU9tJNK8phl01886lGvsmW5gFXSnz120Wb1YrGdkrdCCvobJHwjHchwXdBEXNYEQJjlIvplqlJso9vuBOgrU71lBInfPxBZUAM3SnyhUaCI59ERZDuI_6bZ595QNrpe0VjOfbvFwekxu3x8EpQCEe7U0Bs0IdSaKIdTAUau6Xwn-TPMnuoBvuyJrX4KJQp0gkdtOpFQs1tD9KMBjNWnwY9Oo3eGOF9rRyB-139EcP4vaN-aCbhJFqNNPnjCSaolgkMB-tCNakR3hDrtVJCzeQ04bZ_Qkk6vi3t1H9jLhvOgzIelAevsh1chXDaY1SPMETUH6GqS5sGAff1hYwDUkT7uU7C2uP6wpx_Rf-ivMVuc0nkziRznnhgTManPr1GoLZWE4XAtSWhGW0bSsxZwktISaAxuOK5av-3k2UG5wup4F2U5FImoQqOBSCPh-aOF-tJQnz-DbhK-KWibx3m8uFGikQLEOOuOzWUZjUjhxRd8q86uLK7UAeQdASF8Q_wDIW1-Q4AAI6wsS6iApTeTAUOYpAWcs5OxFGJHGchU-E45zJpxWoikIhND_-CyWo_oXNhNyyLuGTo2_mse7cu3PfNYNSDkpBuYUheAkWZY1q6gpKDXQZrFYX27WT-R6_RE55Cd4BIBCNi9YGr8umaq_5vdrd2N0NiR8JiSZbtEZsVp2vXCW0ELWkBe6EeCHUb5C_qTZV7nMkslRojYvcqzhZuNqYqJ-TaHllrrA-w1v_rupHdPL3-7gCpQAdcM9JymvZR6poE2H-r6SmA5y8CcUfHK8KUIXvgsV_T_W9z8BM9Nl4_4jAAA%3D
line: 0
col: 0
error: {}

**Comment by gopstr** [comment] 2021-11-26 17:29
Same as https://github.com/EDCD/coriolis/issues/684#issuecomment-980177786
but tries to find hpt_dumbfiremissilerack_fixed_medium_advanced here

**Comment by felixlinker** [comment] 2022-11-12 11:35
Closing as duplicate of #681

**Closed by felixlinker** 2022-11-12 11:35 UTC
