### ISSUE TITLE
Module Storage.

### ISSUE THREAD

**Issue by GraXXoR** [EDCD/coriolis#88] opened 2017-03-08 18:01 UTC
It would be wonderful if you could implement module storage so that we could populate the various slots with preconfigured modules.... It is a wee bit of a chore to input the engineering stats one by one....  ＃FirstGalaxyProblems...

(I'm sorry, I don't know how to add labels like request or enhancement...)

**Comment by cmdrmcdonald** [comment] 2017-03-08 21:26
Duplicate of #72

**Closed by cmdrmcdonald** 2017-03-08 21:26 UTC
