### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '1')

### ISSUE THREAD

**Issue by Roon750** [EDCD/coriolis#716] opened 2022-10-29 20:36 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Path: /outfit/alliance_chieftain
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 84922
error: {}

It occurs when clicking on weapon modifications. Thanks

**Comment by Roon750** [comment] 2022-10-29 20:38
It occurs when clicking on weapon modifications. Thanks

**Comment by felixlinker** [comment] 2022-10-31 08:16
Duplicate of #714 

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:16 UTC
