### ISSUE TITLE
crash when trying to engineer certain weapons

### ISSUE THREAD

**Issue by ajcapps** [EDCD/coriolis#722] opened 2022-10-31 03:20 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Path: /outfit/adder?code=A4p5tzF8l3d9sdf3------------.Iw1%2FkA%3D%3D.Aw1%2FkA%3D%3D.H4sIAAAAAAAAA2P4x8bAwPCXFUj8mQQkuDewMDDw8vz7%2F18wFcgSann1%2F7%2BKCQcDw3%2Bmf2JwlcVAgl%2Fl1%2F%2F%2FInK%2F%2F%2F8XXcDPwCAB0qhcIA5UyfxPGq6yCqTyigHQpAvsDAwid4CCyh5f%2Fv%2F%2Fz%2FLPEKaIv%2BLN%2F%2F9CZ%2B4BRdn%2BJaCKHnjw%2F7%2BezTeg1H8GEAAArtJZELAAAAA%3D.EweloBhAOEoUwIYHMA28QgIwV3fEQA%3D%3D
Error: Unknown
Details:

scriptUrl: https://coriolis.io/main.js
line: 46
col: 84892
error: {}

**Comment by felixlinker** [comment] 2022-10-31 08:17
Duplicate of #718 

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:17 UTC
