### ISSUE TITLE
Broken interface on Safari

### ISSUE THREAD

**Issue by gbogopolsky** [EDCD/coriolis#641] opened 2021-01-28 10:28 UTC
First, thank you for the awesome project that is Coriolis.io!

I noticed that since the update from yesterday, the interface is totally broken on safari, while it was perfectly fine until then.
It seems to work fine on Firefox and Chrome on macOS.

For reference, I run macOS 10.15.7 with Safari 14.0.2, Firefox 84.0.2 and Chrome 88.0.4324.96.

**Comment by felixlinker** [comment] 2021-01-28 10:47
1. Did you try fully reloading the page? You should be able to do this by pressing Command+Option+R on a mac.
2. If that doesn't work out, can you provide me with a screenshot?

**Comment by gbogopolsky** [comment] 2021-01-28 12:39
I tried to fully reload as you suggested, without success, it still looks the same to me:
![Capture d’écran 2021-01-28 à 13 37 11](https://user-images.githubusercontent.com/25324757/106139798-2e899f00-616e-11eb-9da6-4c8d8694b161.png)

**Comment by felixlinker** [comment] 2021-01-28 13:53
We had this issue occur a couple of times for Firefox. Most of the time, waiting and force reloading helped. It is really hard to debug this one for me because I never was able to reproduce the behaviour.

Depending on your proficiency with browsers, would you be able to tell me whether there are any errors in the console and whether all style sheets are loaded? (Hitting F12 brings you half way there)

**Comment by gbogopolsky** [comment] 2021-01-28 14:38
Strange behavior indeed... There are indeed two style sheets that are not loaded:
![Capture d’écran 2021-01-28 à 15 32 33](https://user-images.githubusercontent.com/25324757/106153352-bf687680-617e-11eb-947f-46388731dfb1.png)

**Comment by gbogopolsky** [comment] 2021-01-28 14:39
OK, force reloading did not work, but to find the errors, I had to activate de Developer menu, which allowed me to try to clear the caches. That worked!

Thanks for your time!

**Comment by felixlinker** [comment] 2021-01-28 15:27
I close it in favour of #456 :)

**Closed by felixlinker** 2021-01-28 15:27 UTC
Labels: reviewing
