### ISSUE TITLE
Error uploading engineered corvette details to Coriolis

### ISSUE THREAD

**Issue by boltaSTO** [EDCD/coriolis#217] opened 2018-03-12 03:55 UTC
As the subject suggests . . . recevie an error message "Jameson, we have a problem - unable to load ship" along with the following information - any ideas?

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIADP5pVoC_-1ca2_bWJL9K4aB3dkFOsJ9PzKfYrvTSXcy7Y296fkmsKVrmwhNaijK3Z5G__c9RcoPXokiRSXBYDMBHMgP1i1enqo69bj84_iqDOH45VWSLcN3x-n8-CV33x1nySqf3Zwk98vjl38cX2RFxcz0Iv1n0PX3q1_rH9HnrEjmxao6fnmcVMffPXz7t-QWQo__69Xf-X_-7eTi_K-v_xu_zJufpvk8LAL-y6vpVXp9U4Xy-M8___zu-LaYr7JQL_mqvC1WJX36pSg_vc3Py-K6DMvlFH-TXqWzpEqLvP7Ln1fVVVpVaX79Og3Z_PJ-EaZn4Srks_C-_ttQvglJVt28X2VVusjwPV02T5eLLLn_mGQr0klqMeHyP6DkXfMTNdGCC-2lEEw4yRT027bU978vsmKZ3oUPYZkuqwTLbhH_QsqJfS6eT6S0klnNpWYaa5gO-T-leajS2W7pXE1MWzpXRhipoThTyirbIf19slxuVZdNHGuryxxjwnrLuGdOdgm8vAnlbY-6aqLcM9ls4jX22hstNJNWeIJCyK9x482jevj8FuDE_QjOnn6_BtpFyEIejn4MSQ7BZZili_Au3IXs-KV--H79pw2ypsDE3f3Zqro_fgQerbVpDcIx5aHWI3xfh3koa_xNT4vyLlRVmK6F_lAm8yChQZEfv6zKFWQsyrQoUyzzkj_tpvHc4mY13elZmCUZp7V3a2GMtUo-alFfBgVuf02q6fdZWoXeZdnjcmLYctpHy9VgL0O594Jy4II8WvCSNnSf1b6vcXFaZGvvsXtNq5gV9nHN9cWrZVXcpsvmEZ-vykU2cPHXJeRc3KRX1VkJjzDWe50URXWZ3m43HSYi0_GwcWMU8w4G32GVry_Ofl5U6W2SdRi8cnB3LXtXTgupmBBcAafbxb7Nq3Dd7MQWn-Qntq2rgyMVXFujvZZ8X48EcbrtkbxVWlqnvOq-8_Pit1CelclvW1XUE92WybUmH2SENd5LbXpcEWebruh1yNIZ9uTodVIu6bIef4RnM31X5Ncfkvw6DHBGRvFnkMUjmL7BjZZzQlwdos30NMMm6gFuiNv6SRB0VyG7TPJP_TYDBRCyWgo8XNwwhGb5fi8I3PrabN6srsObpJwvijSv-FireXV7W5xm6YJ02PawhcLTbeHRaqcZhydmRtsuAJ0lt8n1NoGaTVQbPBqh1hulDdNKML9b4nkoL8KsyOefVTSCbpn-uqqKTswjslsVRXaruLXMMKWtVmqEJXEzcZEhGQfbZNhaJ_sjutk0o8tifvQXsImjE6AJDPEvR-9n_7NK8974_ktIFvDbP9-FcnaTlNdh3m9UxnHvzSOm3yyqac0WT5M8h6wfUkTZbEo47UW1kdYaxrDkcgG14HFj8K5_Pk3BjvJ5mpT307JY5XP8Ml9l2YZFiC9oEUJFFgGb8EwJ7oxV-1qEgoWZdhBRcPdWWhAozfVoexgruN8alJ0425ZscevSQbywQo4IfLAFLyJb8NzB1UovXKeyHXEPUdO3A77nzAstQV4kh4n927T2M613pPeXjzZgP1GS45jmxjoPv9gdbZo84hy5TNWkGFtk24lop2bMYos14gPMwVmzt9myWKBCjue9INOSYrzVjpM7IITxifHtEIZw451zQsJ72TFGyxAG20bLJJOOIUVwVoj9jBbuqu0BGDgbJz7tvYKau3LnJHtXJNu2k7sJi1S0HjeN4I0v8y8fY5FFK8P7HEFtnh2egD3euwbrl-ZAR5BehYvVYlGU1SDSy59lw0R6n13_nPeKXjdmvQLJggbvkzRvUs7lWDfUXP4mJNWHpNrqiIyOqZkh2qvAJIWXostYGsFIGmHhVwVgub2UI_zEtyOzgLdXnnvEZg5_1yd-R076AkbJeduHAu9UJjB4JJ0Z5M6sVMaUB17TgP97-A2OVNeNyiORltuo_AaZWnHa4B67FJt2CQxcAQJFeXSeZGmvNTabCc9ZDqpmUa2gnUCuBRCK7e7k8ZkJQpTnXNRADvN0dXt4UO0MUXbCfRzyHBUMpZDwzm50jBoruDdISTWRtgU0o42Unjmq1TCr_QigCUgxbcLupVIG3h_GJqUdF1kMb5NgxELHYccIpqDAUnDWVwdBrNwA8UlZFEeXSfmPVTo0nnx_BYikIa-GRRMpW9HkJCS375JlKB9iSQPLDiSLp0q_Q5jXA4JJ1ezilLC0SqunUBLhf3zCNoD9veBtVgUPBv0FBzdWVM7cl_25mEsBoV6CLkin6w7IaNsaLXmIcUVe3GhrwNi0ccxazvYsLgpEhciuDO0lV4gKsK4RpirNxMm2ipJbANdJ6OfM5zNUGCgcscatm6ah8G87XdvpHWn4ZKRpllYggox_1q7iq_k87TBVDVrQtgANgmE18nZjjDioochtXBhw8NPaeuYBCcoID-gncjOxEfGSwisPtZHFIDjuXbx3Exl1P51ENBTCCKXxXPkB7cQB2n7RhuIbAOxDSHPQ5Fm4pab2Hr1FY5xWpl3O35C3V3qhNOyctRAvvhriZdyk0dJqbLDxhnVn5oMhb2QEeWk8MgGlRN0_PATyY4V3Ql5tdNAVcC4tgx8Du9TiEMj3a_ttQv4cKXX1Y_HrgNav1do_BaaHC6fbuvv4UNb4nDI1rBN8niXAHGzv1WJRFsns5mKVNvl5z96AcPN2ctaIasvp3RBRM4GGoDzRqcOqDMvTZJHMurq9vF31BiJBxTTInvXA5u46wPJDaMpI27mejvpVCmGUEmyQKT6mNc1Fu66AdF1wjqTMOCRTvsswL-6XVbj9Eruwlvz5d6Hha30qR_mEc1DWaC_AVCT3brfsQ5Tuaa67LRXLm3B09lvIsv6-egz-6Zv0-uZ1Gf6xQkgbVicRsSnGIslLuaHtdmGF8tLzR8sky67G2iTV_B54-Oy-q0zO4jI5og9isYEDtqOmOpSY2HZfQ1ua3YLZCKrJ-Z11jR1ARMIk2kVzaQQkC-Us8jrbR-JALzbQ8gaeHKlNng7CSv04aPgGxjgfVkczW_CxqMXshQxuhHYGT4bu8UMyT0Z76s5SqnKgCM-2V0xAQzj104yQSvgx5SgX825PEUxZmidgUnbluM2gy5Za3EYVFTl4XS3TwnpyHF3uM-TLorwkL1RdzJL8VX6dba2Fg56atsbKSE_FOK-Uh3H0JtBiSwL9Ds_z6Ed8Xha9xKlRda3xnmM_QrfR1ghZDoGa2OqELm7SxU9pdbK6XYRyEGOC3945BkkSP6WV-JCk-OW0kSyHUaa1NheLIs3CsNk9Zgepw6droWovTS6TNBu2K1Ltsyskd789-QVwXw5URe-jSi2YD9SFJr550yQYPdlYFp9C_iFc47-OfpWQExaNaRkP2sApg0TY6vRUp0WWpUusvjtz0u0uKuiO8vU_xSTkd_LUUF7fn4ey1n07p2Qq4pRMOnxJcB3lDsp8tZ3ottJKNFrTNLYd0_BWEyWjFrWSzHtNxEx3coMhqbTy8RZr1mwxfJiE_9kvk0YYaEcFhrAlpHdIoU3nhM5OjLmJiIZquOVEMhxlX7wrcMF48PGHkPf0LVWMYK-9Zo4z6Gw7n9aj9IuqRISpbrYVqrEZUbuVW8OFJ6bEzSElhRciHi-ohzVoXsMpq4DgHra-pY_5LqRHpzdhlV_3xsWHmyePhcj4WAwYMmGEZyfavflY3PPO5hT7W9Qa7W5wWs3AYpr-be37xIG-r3uqG85Dt_sPiG5SOy0VNeLGTKG9EKZN-OBHJXfUk6cjIZJ3FuN2d7pdXODjDvmtRb4Iw1FyJ7ZPkvzT2aqzs8XjUTxkgJbcp9TIWjrnUp9kU0q0TS5vT9NShqs1WBAzyIU0_8yUT26F9ily1pN6RLppUqTLgTkGUvAt0H4S94TsB3azFrGN_Uni0c0d15CWXwzSCOMqmi012nDJpJJIPc0oSNsJa-eeFp6PK-yTU3Saat-2hI_HShk10jjwLB3zatSZAuEnUkcTMVJ5xhVZHrejUWzb59Oo5OuModNYnOkB1nGxSPP_XWzrKrYVRriSBiCBiQjvKOv6f2Yf3clRbB6qOU8x5OySMVZunIm4mBXF4vmZjC4V1FPUwfP0TD6qoIeqUB_L4N3HMszQYxlS0uDjowLPjn32ZB9I0mV0LqQ53HmS3D-v5_fnGzTfpcWjCnawCpKUaKnwvr7gkN6CRIB7SoBcfbUaAgkHqxzQ5VBDNSFLb-r6tSZ-qCaEDNVGxmlSXhcfktmn5xrwAdBQ9nErOKsvHnSyD9w6stIKBpqUJ8X8_ixdzoq7UN5T6QaEbfpqfkccdd6_IZoZaZsdAR3PPsNU94ABHN0e7EbQ0MrRqLBGCMJD1_tO4NiJiQRaU3en4IE1kt8DhtvGCe6dvxEOWXM7EHOKF_BAXkvnO8dbOg856PiQg2I0fqaQjypv-JhZuY3qJE3feCVgRKCrfvfIQecIjjJIFtvJLR1j49IjVnp6_v-aIzhi9whObT_9KRF2Tm2a25eed4uw5h2YlOHGaCu0ZW7_ibfocB2jth9gxpDmEuQOmHgbKbl_4k3HJmKUApsWNP-PXNGNObUnWXt4G0JBPTTinfV0-mncjNpGjV0a6Wg4TSIOGJqp_QYM5DLN7z_DPHR7_KahtjtfY4HsIzrdKbxVCE00E6a08IcVIqlhEjlqTXUKTXOd3ulRR2_UhEfnWqh9ZEDsDYT7PXM6YVi7kQg8MiGU9EhVvOejcjoZ9yaFFIJz4bn11HrsO3zDtpwTP0vn6dHHpCJj6j9xs87j6uZkue-0jWyfv2vLIhLHBvewHV9P2rQQLr4iwu1EteGCbN3T4KPjgIs8bMRsIqOOJpiCAHysoKb5GHQDftFpUIpdgtOgie4s7Q2ps7O4rAVj1Ew7sBAg3XSeMey2HNGeXiHVvVCWxgWYliMtR9vIchC2ybAlvVfnG7cb-fXsRsYHtajdZYRSzmkvOieIBr7eSMdGyahfrw3-MyDy4pCXG-k2oSDZBsTKKa6ct_6QpofQ7bcy0bsRhPHWKG64lDSk_XUBulb668BT9MFTjR4YHIqa6K1VeLLwOMZqZJJaycNQw-M0nVMnAcItE2NogIybNN6AVQAu1C_1nf5xEA43TotRKx_4pjjhLG8Kgt8sDvVXpRcu6rBaZyRzGg_ai4Pps4wjtqW3OWjHpITXGUkw-AbBEBa5MUivtocRjFHqdhIMa9vnrOSE1LTUHYHIcUdvfbvMg9v3VOgRBgky4lrntMEQs-zfgG-FvoBiN4XWll2asXa5E9DxIA214bHXSns6juf2LS2q6FUMTHGwZOuk9XCx3W92-L1zjFDaiWkzbwNWK2l8xoGRjDku-EIbgKt9csbQyx2kYsy4TgK1rpl3jVRq3T4lBqna4Z_h9MYnODT_pZt7zaDjT2mW_ZKUZZJXD1X-PWYfQcP0sxE7wvJpmd6GB1EDoPzUYOPMw4Q3sWy_YozR7RoyYoz2BEl6MwS-OkvTg6MMj72Wp_Y4SLP2jplxRya0i8bbkHMLZA8K9MfuHQmiOhUigbfUaaNBPD2uSCMmLtpVohPcMmqPS3NQHIiPXGMbqZqGSIt8wclvPI11XzGNZfGZWsK1tuSAaV5NyXElyPg9kEorWI0xdCjokGFIvvHCTooQVgohubHG7Gs4nkG3luHQaIlkBlFCiVF2s_FyNYHsV8ElKXAcZb49bH8EfkP2sUhnA07sOUFnxh6VqK86p876x1CvMGi2uulZDH5rrRTcP8XD9cUj31r75655cQhY3qSLt2fUg_n5hZCv1z95OGDz_vTi6FUWfg_3R-9CkRd3R2_fPkHpj-ObVZZRo14Lxixzz17xrY3moDg0F1AVVZJR84QhXzG0mas8K5I84HadNYwOcP8fCvLYBahcAAA%3D
line: 0
col: 0
error: {}

**Comment by Tkael** [comment] 2018-03-13 02:17
Duplicate of #205.

**Closed** 2018-03-14 09:12 UTC
Labels: duplicate
