### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPowerGeneration' of null

### ISSUE THREAD

**Issue by chartercook** [EDCD/coriolis#320] opened 2018-07-18 07:12 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Path: /outfit/cobra_mk_iii?code=%5Bobject%20Object%5D&bn=USS%20Rockford
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.34c16f.js
line: 11
col: 510100
error: {}

**Comment by chartercook** [comment] 2018-07-18 07:13
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Path: /compare
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/app.34c16f.js
line: 17
col: 21674
error: {}

**Comment by felixlinker** [comment] 2018-09-01 18:50
How did you get to this link? The url seems to be odd. The path parameters are `code=[object Object]&bn=USS Rockford` when decoded.

**Comment by willyb321** [comment] 2018-09-01 21:40
@felixlinker I've seen this happen to a few people. Only way I an think it occurs is somehow a JSON.stringify failing but I have no clue where to look.

**Comment by felixlinker** [comment] 2019-04-27 13:26
Closing as duplicate of #278

**Closed by felixlinker** 2019-04-27 13:26 UTC
Labels: bug, investigation-needed
