### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by JHill29th** [EDCD/coriolis#338] opened 2018-08-14 08:00 UTC
Whenever the browser window is resized:

```Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Path: /outfit/federal_corvette?code=A0pxtsFklodzsxf51r1r151c1b13130003020404---B006060505fr5i2dm9v6C02f.Iw18ZlA%3D.MwBj5BGacj4WYAmEQ%3D%3D%3D..EweloBhBmVoDgCwgGYFMAmaBOBDANgPoDGA9tgG5oAu1aIAwuVbWgAQCyAlgM49ekAdjxABGCBKA&bn=Corvette%20Missions
Error: Unknown
Details:
scriptUrl: https://coriolis.io/outfit/federal_corvette?code=A0pxtsFklodzsxf51r1r151c1b13130003020404---B006060505fr5i2dm9v6C02f.Iw18ZlA%3D.MwBj5BGacj4WYAmEQ%3D%3D%3D..EweloBhBmVoDgCwgGYFMAmaBOBDANgPoDGA9tgG5oAu1aIAwuVbWgAQCyAlgM49ekAdjxABGCBKA&bn=Corvette%20Missions
line: 0
col: 0
error: null
```

**Comment by willyb321** [comment] 2018-08-16 00:00
Duplicate of #208

**Closed by willyb321** 2018-08-16 00:00 UTC
