### ISSUE TITLE
Incorrect calculation of the 'Mass Manager Effect'

### ISSUE THREAD

**Issue by MoonSeeker2020** [EDCD/coriolis#662] opened 2021-05-11 22:20 UTC
The value of 4% of the Mass Manager effect is applied on the base value of the optimal mass, instead it should be calculated on the value already optimized by the previous engineering.

**Comment by felixlinker** [comment] 2021-05-12 06:02
Thanks for the report! And kudos that you found out, what the issue is 😉

This is already known, though!

Duplicate of #660

**Closed** 2021-05-12 06:02 UTC

**Comment by felixlinker** [comment] 2021-05-12 06:54
Should be fixed now!
