### ISSUE TITLE
Erroneous DPS reported for Corvette

### ISSUE THREAD

**Issue by nemesyssoft** [EDCD/coriolis#57] opened 2017-01-25 16:55 UTC
Not sure what happened in one of the last update. My DPS is now reported as 2,538,092.7. I imported directly from EDMC:

https://coriolis.edcd.io/outfit/federal_corvette?code=A2putpFklndzsxf50x0x7l28281919040404040402020l06p05sf63c5ifr2dm9v46l2f.Iw18QDFFA%3D%3D%3D.AwRm4yutVkEKA%3D%3D%3D.H4sIAAAAAAAAA02Su0scURTGzz5mX3fH68yOu9dsZDfuJGphEItkwUfSBJGw2Agq2JpKrBIECyGC%2F0GwThGwcLcSixBIu4VVihQJ4l%2BglaiLrvf4nWKSaT7umfO733ncIZslogcH4n9URG5FE6mdFJFXSRKFPxNEnLBvBMKRyhmgus3MuQ2EnLRlSYGnoSlYNf6UiMxnXNVvH5gD1zL7F8A5ZZ%2F8q3TgI791x2yCPFGwGcDJsbOR0%2FMsOnnxA8dnXUCjH2CSP%2BwzF%2F4i1K%2Fgzjm7EvXUr0GGd1Dd%2F4bYtEA6Uz3ULNjVyLNfhDj1en05ExiiwSbCxuY6Udq9Z66cgR4pog6r%2F3ec7QGizG41wnv4mF4Crr8LWYyRTRdkIORrITtpkG0hp2VezEdmUVap7bvoTs2OI%2FW%2BhVUcATeHWI06ha8nEorwYAz%2F0gA%2BOQf8FgswjHlVFZ6eSHgpr%2BHZhWgp5gqqXMmLhCJ6AJa1vRxIP0aew075Qs4LKSe9LwOWYtBL9KBGQHoioYhW0qKxLYHS8gcc4zXVjEAdgdYwUTK8Zq5%2BwioyX%2FEt6Eqfw3YxMq7fIJWdQLmx3wgTXXncp7H8CV4z%2B0vyKcSJafTB%2FAjeygIOtwIAAA%3D%3D&bn=Kantos%20Kan%20Federal%20Corvette

**Comment by cmdrmcdonald** [comment] 2017-01-25 19:08
Please could you provide the import data for your corvette?  This should be available from EDMC by exporting the raw data.

**Comment by nemesyssoft** [comment] 2017-01-26 02:23
The problem doesn't manifest itself when I import from EDMC. It shows a DPS of 110.5. It's when I reload the build or access it through a bookmark.

Here is the raw data from EDMC:

{
  "cargo": {
    "capacity": 128
  },
  "free": false,
  "fuel": {
    "main": {
      "capacity": 96
    },
    "reserve": {
      "capacity": 1.13
    }
  },
  "id": 21,
  "modules": {
    "Armour": {
      "module": {
        "free": false,
        "id": 128049372,
        "modifiers": {
          "engineerID": 300210,
          "id": 11009,
          "modifiers": [
            {
              "name": "mod_mass",
              "type": 1,
              "value": 0.29318356513977
            },
            {
              "name": "mod_defencemodifier_health_mult",
              "type": 1,
              "value": 0.26306948065758
            },
            {
              "name": "mod_defencemodifier_global_hull_mult",
              "type": 1,
              "value": -0.044615425169468
            },
            {
              "name": "mod_defencemodifier_health_mult",
              "type": 2,
              "value": 0.010113115422428
            },
            {
              "name": "mod_defencemodifier_explosive_mult",
              "type": 2,
              "value": -0.01991587691009
            }
          ],
          "moduleTags": [
            21
          ],
          "recipeID": 128673644,
          "slotIndex": 43
        },
        "name": "Federation_Corvette_Armour_Grade3",
        "on": true,
        "priority": 1,
        "recipeLevel": 5,
        "recipeName": "Armour_HeavyDuty",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 143796630
      }
    },
    "Bobble01": [],
    "Bobble02": [],
    "Bobble03": [],
    "Bobble04": [],
    "Bobble05": [],
    "Bobble06": [],
    "Bobble07": [],
    "Bobble08": [],
    "Bobble09": [],
    "Bobble10": [],
    "Decal1": {
      "module": {
        "free": false,
        "id": 128667742,
        "name": "Decal_Combat_Deadly",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 0
      }
    },
    "Decal2": {
      "module": {
        "free": false,
        "id": 128667757,
        "name": "Decal_Explorer_Ranger",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 0
      }
    },
    "Decal3": {
      "module": {
        "free": false,
        "id": 128667750,
        "name": "Decal_Trade_Tycoon",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 0
      }
    },
    "EngineColour": [],
    "FrameShiftDrive": {
      "module": {
        "free": false,
        "id": 128064127,
        "modifiers": {
          "engineerID": 300100,
          "id": 3904,
          "modifiers": [
            {
              "name": "mod_mass",
              "type": 1,
              "value": 0.42523837089539
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": -0.2126482129097
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.23241454362869
            },
            {
              "name": "mod_fsd_optimised_mass",
              "type": 1,
              "value": 0.46293264627457
            },
            {
              "name": "mod_fsd_optimised_mass",
              "type": 2,
              "value": 0.040929391980171
            },
            {
              "name": "trade_mass_health",
              "type": 2,
              "value": 0.088846378028393
            }
          ],
          "moduleTags": [
            16
          ],
          "recipeID": 128673694,
          "slotIndex": 47
        },
        "name": "Int_Hyperdrive_Size6_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 5,
        "recipeName": "FSD_LongRange",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 13752602
      }
    },
    "FuelTank": {
      "module": {
        "free": false,
        "id": 128064350,
        "name": "Int_FuelTank_Size5_Class3",
        "on": true,
        "priority": 1,
        "unloaned": 83090,
        "value": 83090
      }
    },
    "HugeHardpoint1": {
      "module": {
        "free": false,
        "id": 128681994,
        "modifiers": {
          "engineerID": 300180,
          "id": 2148,
          "modifiers": [
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": -0.47768124938011
            },
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.068289995193481
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": -0.17476351559162
            },
            {
              "name": "mod_weapon_active_power",
              "type": 1,
              "value": -0.2427194416523
            },
            {
              "name": "trade_weapon_damage_weapon_active_power",
              "type": 2,
              "value": 0.11697211116552
            },
            {
              "name": "mod_passive_power",
              "type": 2,
              "value": -0.031561955809593
            },
            {
              "name": "mod_passive_power",
              "type": 2,
              "value": 0.052067745476961
            },
            {
              "name": "special_thermal_conduit",
              "type": 3,
              "value": 1
            }
          ],
          "moduleTags": [
            1,
            4
          ],
          "recipeID": 128739089,
          "slotIndex": 26
        },
        "name": "Hpt_BeamLaser_Gimbal_Huge",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Weapon_Efficient",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 7871544
      }
    },
    "HugeHardpoint2": {
      "module": {
        "free": false,
        "id": 128681994,
        "modifiers": {
          "engineerID": 300180,
          "id": 2180,
          "modifiers": [
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": -0.46386921405792
            },
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.052390374243259
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": -0.12643526494503
            },
            {
              "name": "mod_weapon_active_power",
              "type": 1,
              "value": -0.21997955441475
            },
            {
              "name": "trade_weapon_hardness_weapon_heat",
              "type": 2,
              "value": 0.099044546484947
            },
            {
              "name": "mod_health",
              "type": 2,
              "value": 0.34891483187675
            },
            {
              "name": "mod_health",
              "type": 2,
              "value": -0.074022874236107
            },
            {
              "name": "special_thermal_vent",
              "type": 3,
              "value": 1
            }
          ],
          "moduleTags": [
            1,
            4
          ],
          "recipeID": 128739089,
          "slotIndex": 27
        },
        "name": "Hpt_BeamLaser_Gimbal_Huge",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Weapon_Efficient",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 7871544
      }
    },
    "LargeHardpoint1": {
      "module": {
        "free": false,
        "id": 128049461,
        "modifiers": {
          "engineerID": 300260,
          "id": 4699,
          "modifiers": [
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.33230463266372
            },
            {
              "name": "mod_weapon_active_power",
              "type": 1,
              "value": 0.61637383699417
            },
            {
              "name": "mod_weapon_jitter_radius",
              "type": 1,
              "value": 0.56468063592911
            },
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": 0.12204115837812
            },
            {
              "name": "mod_weapon_clip_size",
              "type": 1,
              "value": -0.12667710076818
            },
            {
              "name": "mod_weapon_hardness_piercing",
              "type": 2,
              "value": 0.033723440021276
            },
            {
              "name": "mod_weapon_hardness_piercing",
              "type": 2,
              "value": -0.036045636981726
            },
            {
              "name": "special_incendiary_rounds",
              "type": 3,
              "value": 1
            }
          ],
          "moduleTags": [
            1,
            8
          ],
          "recipeID": 128673502,
          "slotIndex": 28
        },
        "name": "Hpt_MultiCannon_Gimbal_Large",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Weapon_Overcharged",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 520593
      }
    },
    "LifeSupport": {
      "module": {
        "free": false,
        "id": 128064159,
        "name": "Int_LifeSupport_Size5_Class2",
        "on": true,
        "priority": 0,
        "unloaned": 0,
        "value": 67528
      }
    },
    "MainEngines": {
      "module": {
        "free": false,
        "id": 128064097,
        "modifiers": {
          "engineerID": 300100,
          "id": 6259,
          "modifiers": [
            {
              "name": "mod_engine_mass_curve_multiplier",
              "type": 1,
              "value": 0.18401804566383
            },
            {
              "name": "mod_engine_heat",
              "type": 1,
              "value": 0.50814712047577
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.11027134209871
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": -0.065716363489628
            },
            {
              "name": "mod_engine_mass_curve",
              "type": 1,
              "value": -0.049905456602573
            },
            {
              "name": "mod_passive_power",
              "type": 2,
              "value": -0.041602794080973
            },
            {
              "name": "trade_mass_health",
              "type": 2,
              "value": -0.0050673335790634
            }
          ],
          "moduleTags": [
            17
          ],
          "recipeID": 128673657,
          "slotIndex": 46
        },
        "name": "Int_Engine_Size7_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Engine_Dirty",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 43595746
      }
    },
    "MediumHardpoint1": {
      "module": {
        "free": false,
        "id": 128049463,
        "modifiers": {
          "engineerID": 300260,
          "id": 4729,
          "modifiers": [
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.3351256608963
            },
            {
              "name": "mod_weapon_active_power",
              "type": 1,
              "value": 0.61838209629059
            },
            {
              "name": "mod_weapon_jitter_radius",
              "type": 1,
              "value": 0.56370949745178
            },
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": 0.10164558887482
            },
            {
              "name": "mod_weapon_clip_size",
              "type": 1,
              "value": -0.12007241220411
            },
            {
              "name": "trade_weapon_damage_weapon_active_power",
              "type": 2,
              "value": 0.052759505808353
            },
            {
              "name": "mod_health",
              "type": 2,
              "value": -0.032706737518311
            }
          ],
          "moduleTags": [
            1,
            8
          ],
          "recipeID": 128673502,
          "slotIndex": 29
        },
        "name": "Hpt_MultiCannon_Turret_Medium",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Weapon_Overcharged",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 1292800
      }
    },
    "MediumHardpoint2": {
      "module": {
        "free": false,
        "id": 128049463,
        "modifiers": {
          "engineerID": 300260,
          "id": 4731,
          "modifiers": [
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.3383542060852
            },
            {
              "name": "mod_weapon_active_power",
              "type": 1,
              "value": 0.69319069385529
            },
            {
              "name": "mod_weapon_jitter_radius",
              "type": 1,
              "value": 0.55067348480225
            },
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": 0.11971006542444
            },
            {
              "name": "mod_weapon_clip_size",
              "type": 1,
              "value": -0.11080657362532
            },
            {
              "name": "trade_mass_health",
              "type": 2,
              "value": 0.0050421766936779
            },
            {
              "name": "mod_passive_power",
              "type": 2,
              "value": 0.03293726965785
            }
          ],
          "moduleTags": [
            1,
            8
          ],
          "recipeID": 128673502,
          "slotIndex": 30
        },
        "name": "Hpt_MultiCannon_Turret_Medium",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Weapon_Overcharged",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 1292800
      }
    },
    "Military01": {
      "module": {
        "free": false,
        "id": 128668546,
        "name": "Int_HullReinforcement_Size5_Class2",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 450000
      }
    },
    "Military02": {
      "module": {
        "free": false,
        "id": 128737279,
        "name": "Int_ModuleReinforcement_Size5_Class2",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 450000
      }
    },
    "PaintJob": {
      "module": {
        "free": false,
        "id": 128732319,
        "name": "PaintJob_Federation_Corvette_Tactical_White",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 0
      }
    },
    "PlanetaryApproachSuite": {
      "module": {
        "free": false,
        "id": 128672317,
        "name": "Int_PlanetApproachSuite",
        "on": true,
        "priority": 1,
        "unloaned": 425,
        "value": 425
      }
    },
    "PowerDistributor": {
      "module": {
        "free": false,
        "id": 128064217,
        "modifiers": {
          "engineerID": 300180,
          "id": 2199,
          "modifiers": [
            {
              "name": "mod_powerdistributor_weapon_charge",
              "type": 1,
              "value": 0.3841078877449
            },
            {
              "name": "mod_powerdistributor_weapon_rate",
              "type": 1,
              "value": 0.19800421595573
            },
            {
              "name": "mod_powerdistributor_system_charge",
              "type": 1,
              "value": -0.14778608083725
            },
            {
              "name": "mod_powerdistributor_system_rate",
              "type": 1,
              "value": -0.059305459260941
            },
            {
              "name": "mod_powerdistributor_engine_charge",
              "type": 1,
              "value": -0.13218450546265
            },
            {
              "name": "mod_powerdistributor_engine_rate",
              "type": 1,
              "value": -0.1434560418129
            },
            {
              "name": "trade_passive_power_distributor_global_rate",
              "type": 2,
              "value": -0.040251906961203
            },
            {
              "name": "mod_powerdistributor_weapon_charge",
              "type": 2,
              "value": 0.06487612426281
            },
            {
              "name": "trade_passive_power_distributor_global_rate",
              "type": 2,
              "value": 0.0055165058001876
            }
          ],
          "moduleTags": [
            19
          ],
          "recipeID": 128673752,
          "slotIndex": 49
        },
        "name": "Int_PowerDistributor_Size8_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "PowerDistributor_PriorityWeapons",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 23161983
      }
    },
    "PowerPlant": {
      "module": {
        "free": false,
        "id": 128064067,
        "modifiers": {
          "engineerID": 300100,
          "id": 3942,
          "modifiers": [
            {
              "name": "mod_powerplant_power",
              "type": 1,
              "value": 0.081056952476501
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": -0.0084498468786478
            },
            {
              "name": "mod_powerplant_heat",
              "type": 1,
              "value": 0.010082358494401
            },
            {
              "name": "mod_powerplant_power",
              "type": 2,
              "value": 0.043923784047365
            }
          ],
          "moduleTags": [
            18
          ],
          "recipeID": 128673765,
          "slotIndex": 45
        },
        "name": "Int_Powerplant_Size8_Class5",
        "on": true,
        "priority": 1,
        "recipeLevel": 1,
        "recipeName": "PowerPlant_Boosted",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 138198514
      }
    },
    "Radar": {
      "module": {
        "free": false,
        "id": 128064254,
        "name": "Int_Sensors_Size8_Class2",
        "on": true,
        "priority": 0,
        "unloaned": 0,
        "value": 1482367
      }
    },
    "Slot01_Size7": {
      "module": {
        "free": false,
        "id": 128064344,
        "name": "Int_CargoRack_Size7_Class1",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 1001657
      }
    },
    "Slot02_Size7": {
      "module": {
        "free": false,
        "id": 128671329,
        "modifiers": {
          "engineerID": 300120,
          "id": 1909,
          "modifiers": [
            {
              "name": "mod_shield_mass_curve_multiplier",
              "type": 1,
              "value": 0.22754582762718
            },
            {
              "name": "mod_shield_global_mult",
              "type": 1,
              "value": -0.11411890387535
            },
            {
              "name": "mod_shield_broken_regen",
              "type": 1,
              "value": -0.27796500921249
            },
            {
              "name": "mod_shield_normal_regen",
              "type": 1,
              "value": -0.11626049876213
            },
            {
              "name": "mod_shield_energy_per_regen",
              "type": 1,
              "value": 0.094919167459011
            },
            {
              "name": "trade_shield_curve_shield_curve_mult",
              "type": 2,
              "value": -0.090624377131462
            },
            {
              "name": "mod_shield_energy_per_regen",
              "type": 2,
              "value": -0.025307156145573
            },
            {
              "name": "trade_shield_curve_shield_curve_mult",
              "type": 2,
              "value": 0.064781285822392
            }
          ],
          "moduleTags": [
            15
          ],
          "recipeID": 128673838,
          "slotIndex": 53
        },
        "name": "Int_ShieldGenerator_Size7_Class5_Strong",
        "on": true,
        "priority": 0,
        "recipeLevel": 4,
        "recipeName": "ShieldGenerator_Reinforced",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 69240302
      }
    },
    "Slot03_Size7": {
      "module": {
        "free": false,
        "id": 128064332,
        "modifiers": {
          "engineerID": 300160,
          "id": 1789,
          "modifiers": [
            {
              "name": "mod_shieldcell_spin_up",
              "type": 1,
              "value": -0.086017057299614
            },
            {
              "name": "mod_shieldcell_duration",
              "type": 1,
              "value": -0.047102440148592
            },
            {
              "name": "mod_shieldcell_shield_units",
              "type": 1,
              "value": 0.021292699500918
            },
            {
              "name": "mod_boot_time",
              "type": 1,
              "value": 0.071096949279308
            },
            {
              "name": "mod_shieldcell_spin_up",
              "type": 2,
              "value": -0.018995799124241
            }
          ],
          "moduleTags": [
            24
          ],
          "recipeID": 128673805,
          "slotIndex": 54
        },
        "name": "Int_ShieldCellBank_Size7_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 1,
        "recipeName": "ShieldCellBank_Rapid",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 8272137
      }
    },
    "Slot04_Size6": {
      "module": {
        "free": false,
        "id": 128064351,
        "name": "Int_FuelTank_Size6_Class3",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 290341
      }
    },
    "Slot05_Size6": {
      "module": {
        "free": false,
        "id": 128666681,
        "name": "Int_FuelScoop_Size6_Class5",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 24449069
      }
    },
    "Slot06_Size5": {
      "module": {
        "free": false,
        "id": 128064322,
        "modifiers": {
          "engineerID": 300160,
          "id": 1788,
          "modifiers": [
            {
              "name": "mod_shieldcell_spin_up",
              "type": 1,
              "value": -0.084282241761684
            },
            {
              "name": "mod_shieldcell_duration",
              "type": 1,
              "value": -0.069141998887062
            },
            {
              "name": "mod_shieldcell_shield_units",
              "type": 1,
              "value": 0.025862643495202
            },
            {
              "name": "mod_boot_time",
              "type": 1,
              "value": 0.081815980374813
            },
            {
              "name": "mod_shieldcell_duration",
              "type": 2,
              "value": 0.041702415794134
            }
          ],
          "moduleTags": [
            24
          ],
          "recipeID": 128673805,
          "slotIndex": 57
        },
        "name": "Int_ShieldCellBank_Size5_Class5",
        "on": false,
        "priority": 0,
        "recipeLevel": 1,
        "recipeName": "ShieldCellBank_Rapid",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 1055120
      }
    },
    "Slot07_Size5": {
      "module": {
        "free": false,
        "id": 128727930,
        "name": "Int_FighterBay_Size5_Class1",
        "on": true,
        "priority": 0,
        "unloaned": 0,
        "value": 575643
      }
    },
    "Slot08_Size4": {
      "module": {
        "free": false,
        "id": 128672291,
        "name": "Int_BuggyBay_Size4_Class2",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 77760
      }
    },
    "Slot09_Size4": {
      "module": {
        "free": false,
        "id": 128666723,
        "name": "Int_FSDInterdictor_Size4_Class5",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 19203610
      }
    },
    "Slot10_Size3": {
      "module": {
        "free": false,
        "id": 128663561,
        "name": "Int_StellarBodyDiscoveryScanner_Advanced",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 1313250
      }
    },
    "SmallHardpoint1": {
      "module": {
        "free": false,
        "id": 128049388,
        "modifiers": {
          "engineerID": 300180,
          "id": 2182,
          "modifiers": [
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": -0.36969983577728
            },
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.031404055655003
            },
            {
              "name": "trade_weapon_damage_weapon_active_power",
              "type": 2,
              "value": 0.1423497647047
            }
          ],
          "moduleTags": [
            1,
            2
          ],
          "recipeID": 128673560,
          "slotIndex": 31
        },
        "name": "Hpt_PulseLaser_Turret_Small",
        "on": true,
        "priority": 0,
        "recipeLevel": 1,
        "recipeName": "Weapon_Efficient",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 26000
      }
    },
    "SmallHardpoint2": {
      "module": {
        "free": false,
        "id": 128049388,
        "modifiers": {
          "engineerID": 300180,
          "id": 2192,
          "modifiers": [
            {
              "name": "mod_weapon_active_heat",
              "type": 1,
              "value": -0.49203109741211
            },
            {
              "name": "mod_weapon_damage",
              "type": 1,
              "value": 0.06700810790062
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": -0.18959537148476
            },
            {
              "name": "mod_weapon_active_power",
              "type": 1,
              "value": -0.24574214220047
            },
            {
              "name": "mod_weapon_hardness_piercing",
              "type": 2,
              "value": 0.0031668737065047
            },
            {
              "name": "trade_weapon_damage_weapon_active_power",
              "type": 2,
              "value": 0.10862150043249
            },
            {
              "name": "mod_passive_power",
              "type": 2,
              "value": 0.040235444903374
            }
          ],
          "moduleTags": [
            1,
            2
          ],
          "recipeID": 128673562,
          "slotIndex": 32
        },
        "name": "Hpt_PulseLaser_Turret_Small",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "Weapon_Efficient",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 26000
      }
    },
    "TinyHardpoint1": {
      "module": {
        "free": false,
        "id": 128668536,
        "modifiers": {
          "engineerID": 300120,
          "id": 1913,
          "modifiers": [
            {
              "name": "mod_defencemodifier_shield_mult",
              "type": 1,
              "value": 0.17489272356033
            },
            {
              "name": "mod_mass",
              "type": 1,
              "value": 1.9368133544922
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": 0.081008836627007
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.14472851157188
            },
            {
              "name": "trade_mass_health",
              "type": 2,
              "value": 0.035626668483019
            },
            {
              "name": "mod_defencemodifier_global_shield_mult",
              "type": 2,
              "value": 0.0052796513773501
            }
          ],
          "moduleTags": [
            22
          ],
          "recipeID": 128673782,
          "slotIndex": 33
        },
        "name": "Hpt_ShieldBooster_Size0_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "ShieldBooster_HeavyDuty",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 238850
      }
    },
    "TinyHardpoint2": {
      "module": {
        "free": false,
        "id": 128668536,
        "modifiers": {
          "engineerID": 300120,
          "id": 1914,
          "modifiers": [
            {
              "name": "mod_defencemodifier_shield_mult",
              "type": 1,
              "value": 0.15175276994705
            },
            {
              "name": "mod_mass",
              "type": 1,
              "value": 1.5660903453827
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": 0.075865894556046
            },
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.12496235221624
            },
            {
              "name": "trade_passive_power_booster_global_mult",
              "type": 2,
              "value": -0.070830009877682
            },
            {
              "name": "mod_defencemodifier_shield_thermic_mult",
              "type": 2,
              "value": 0.0047348104417324
            }
          ],
          "moduleTags": [
            22
          ],
          "recipeID": 128673782,
          "slotIndex": 34
        },
        "name": "Hpt_ShieldBooster_Size0_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 3,
        "recipeName": "ShieldBooster_HeavyDuty",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 238850
      }
    },
    "TinyHardpoint3": {
      "module": {
        "free": false,
        "id": 128668536,
        "modifiers": {
          "engineerID": 300100,
          "id": 3950,
          "modifiers": [
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.049866359680891
            },
            {
              "name": "mod_defencemodifier_global_shield_mult",
              "type": 1,
              "value": -0.026919748783111
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": -0.024229854345322
            },
            {
              "name": "mod_defencemodifier_shield_mult",
              "type": 2,
              "value": 0.036322306841612
            }
          ],
          "moduleTags": [
            22
          ],
          "recipeID": 128673790,
          "slotIndex": 35
        },
        "name": "Hpt_ShieldBooster_Size0_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 1,
        "recipeName": "ShieldBooster_Resistive",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 238850
      }
    },
    "TinyHardpoint4": {
      "module": {
        "free": false,
        "id": 128668536,
        "modifiers": {
          "engineerID": 300100,
          "id": 3951,
          "modifiers": [
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.073374435305595
            },
            {
              "name": "mod_defencemodifier_global_shield_mult",
              "type": 1,
              "value": -0.027446540594101
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": -0.037895452231169
            },
            {
              "name": "mod_defencemodifier_shield_kinetic_mult",
              "type": 2,
              "value": -0.0045657334849238
            }
          ],
          "moduleTags": [
            22
          ],
          "recipeID": 128673790,
          "slotIndex": 36
        },
        "name": "Hpt_ShieldBooster_Size0_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 1,
        "recipeName": "ShieldBooster_Resistive",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 238850
      }
    },
    "TinyHardpoint5": {
      "module": {
        "free": false,
        "id": 128668536,
        "modifiers": {
          "engineerID": 300100,
          "id": 3954,
          "modifiers": [
            {
              "name": "mod_passive_power",
              "type": 1,
              "value": 0.013932451605797
            },
            {
              "name": "mod_defencemodifier_global_shield_mult",
              "type": 1,
              "value": -0.028204485177994
            },
            {
              "name": "mod_health",
              "type": 1,
              "value": -0.024494780227542
            },
            {
              "name": "trade_passive_power_booster_global_mult",
              "type": 2,
              "value": -0.066611737012863
            }
          ],
          "moduleTags": [
            22
          ],
          "recipeID": 128673790,
          "slotIndex": 37
        },
        "name": "Hpt_ShieldBooster_Size0_Class5",
        "on": true,
        "priority": 0,
        "recipeLevel": 1,
        "recipeName": "ShieldBooster_Resistive",
        "recipeValue": 0,
        "unloaned": 0,
        "value": 238850
      }
    },
    "TinyHardpoint6": {
      "module": {
        "free": false,
        "id": 128049519,
        "name": "Hpt_HeatSinkLauncher_Turret_Tiny",
        "on": true,
        "priority": 0,
        "unloaned": 0,
        "value": 2975
      }
    },
    "TinyHardpoint7": {
      "module": {
        "free": false,
        "id": 128049519,
        "name": "Hpt_HeatSinkLauncher_Turret_Tiny",
        "on": false,
        "priority": 0,
        "unloaned": 0,
        "value": 3150
      }
    },
    "TinyHardpoint8": {
      "module": {
        "free": false,
        "id": 128662532,
        "name": "Hpt_CrimeScanner_Size0_Class3",
        "on": true,
        "priority": 0,
        "unloaned": 0,
        "value": 103615
      }
    },
    "WeaponColour": {
      "module": {
        "free": false,
        "id": 128732195,
        "name": "WeaponCustomisation_Red",
        "on": true,
        "priority": 1,
        "unloaned": 0,
        "value": 0
      }
    }
  },
  "name": "Federation_Corvette",
  "value": {
    "hull": 155200708,
    "modules": 510723045,
    "unloaned": 83515
  }
}

**Comment by nemesyssoft** [comment] 2017-01-26 02:25
Just curious, if you click the link in my initial message, don't you see the erroneous value? It is happening in both the latest Chrome under Windows and in the latest Safari under macOS.

**Comment by cmdrmcdonald** [comment] 2017-01-26 17:50
This is an issue with the way that coriolis handles experimental effects.  I had this on the list to do properly anyway, so have updated the beta site with the ability to set and change special effects, which should also address this issue.

Please could you give http://beta.coriolis.edcd.io/ a go, importing your JSON and seeing if it looks correct even after tweaking and reloading the page?

**Comment by nemesyssoft** [comment] 2017-01-27 05:41
Same thing happens with the beta, although with a different value. After importing, the DPS value seems to be ok. After saving and reloading the build, it gives me 2,411,598.4 DPS. Again, caused by the large multi-cannon with a reported DPS of 2,411,505.9.

**Comment by cmdrmcdonald** [comment] 2017-01-27 07:35
And this is definitely with the current beta (version number 2.2.12b in the bottom-right of the page)?  I'm not able to reproduce this at http://beta.coriolis.edcd.io/

**Comment by nemesyssoft** [comment] 2017-01-27 14:43
Hmmmm... did you do something to the beta? It's displaying the DPS correctly now. Maybe I was tired when I tried it yesterday night. The beta I'm using is 2.2.12b. There was an update when I initially accessed it.

In any case, I guess you can close this ticket once the beta makes it to production.

Thank you!

**Comment by cmdrmcdonald** [comment] 2017-01-29 08:35
Fixed in 2.2.12

**Closed by cmdrmcdonald** 2017-01-29 08:35 UTC
Labels: bug
