### ISSUE TITLE
Failed to import ship

### ISSUE THREAD

**Issue by NikdoCZ** [EDCD/coriolis#242] opened 2018-04-12 12:32 UTC
I can not see my Imperial Cutter over Coriolis. It always throws a bug. Interestingly, if I resign to another ship, it all works again. Probably an Engineer Error?

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAI1Pz1oC_81ZXXPaOBT9Kzue2beU0Ydly3lL87F0NmwzkEkfGa0tQBNje2U5Le3kv--VTQrGJjY0beGBwSCde6R77tW94psz01I65zMR5_LMUZFzToIzZ5lGRSxz5_ybc6GXaaHtp0-pfvyQ3Ol0rmWeT2GMmqlQGJUm5ciPhZkpY1Qyv1Eyju5XmZxeyZlMQjkqx0o9lCI2i1ERG5XF8GynRSrPYrF6EHEBRBwSoAEhfzpnzlP1DR0EiGD2fNZq4PpLFqe5epJjmavcCDDWBooGvreFCY8BcdHmhffA_60SaVT4Ojgb-LgO7hLus07wkcjzFrx3GA0Q2gLEg30I9wuplx303lE-8PwaHOWe_wyQMpnD-io3vHz-ABKgQJqjze__iKVFulVf_xivIhh_5mgZqkzeyicZA-LL83pgpZkpePtpdVWYlfP8IilrqaE4TDhyA2otJhXAZWGM1NM1zliK0ICLwWyaOOdGFzAx0yrVCrCt9fXKXMRxQClDYC_PgJGIR7sqXX8_FRW2qXbQOU-KOLZ7cqOBwmShZuZKW5tHCv9mcgXLN2Nh2nyy62E0CPZ4GHA-ZkYtYSXtaqG7WkF0D9SHxMh5tWVtGt6BIexA1boNIm6HxrDX1Nh1_KS0-GMktCmKxy6hwe5MwVdATUY9ROa5mJLvIoP9mA5hRTqyjp5O1FfpTy9jWB7bozS0URphiHFGS8UUMr4XyaM120mAMlwj8DK5NO9V5mmn0AmnIHVrfFjM5VDoKEtVYnAPChBowSbQhpmZ3hUw4FbkEHD3hdbSTG-Fnu-LNrJJzBRzSiyJcvyJsSC_i4WayUmRZak2vQSBvaAmiK3525IknZJk2MO8pDASKrkuwyrvRwHVg6KaW1rnfQMCU9cHcbOKgIxUsTxUEDzocEUF2-kLjBHEZgsPciI8aC8ejHg1HiOVQB6uiNyoLzKq81jP3xBxN0S4j3ELD_e38VCxMkKvUA9l-NQnfj1ERuWEsVTJLNWhXMqkChX2eqhs0idAgptrTMibVrgXUaTsrLaTtnFOEveHals2cGm9lHCZz36gnj0IcF81wBvVAP-BGnYPpZ9Ywg6hHKwr7IBq1vM4c716odHAO0ax3WXtAuzomp1GhXsXCxABiP4iy3QqwsWkUFWV2rEqn1Ds11ZVQdVxOot0XNaFd-lnqa_A5Vr9W5j06A5zfdBdikyE7bXtO9ootv19EVeBjWW4KI_9lvD1G-G7D2yyyo1cvhGzNdjbMPskRQZb-jbM1mCHMuuI3aAZu0MJjQHUymo3dulO7O5KazpU88WNlv8VkKlXvfoEguslUQPyoG4BEBmlbo_wzaydaMtODNTNZ2nftyLYjrKxZ46NGtubXs9gmCq3pEUAB3SErzWWDRw02HuWlMt6RZRu417EfUsZsTYZlbs8fZ-mEH79Wkzk-U3pZCVMj4p6kycDz3c59nFf1VQmWvUyFpE4OsG-6l3auMjwDysUWANgnzomMslTfW9zjJmEIrlI5nHrfRduKI6zn5luKmLQuMGef6p2vleKYfUUU8Hkx2UWMDiJU4NwpbFebR8J6kKtLlL-kgks_CXFHdf_lVTIAVSoy2pULsHL6ViEj9skcHeVhH0XIfqdAq1uVX7hxQylFFWdRUnA_d0EeDm7R6PneYTRuhMmRsax0O_TaAUnX5g-Sb2ygQf6gN9EAjkl6uTDyYZMUJLp2f269Z7vKg0fIR1cpsusMN0E3K3KmSLL4F4lq0NuJGwNT-udbxUg1VlQhQfqm8wJhU42aPAgJ8KDngiPvjcSpH5DAzaX4s4CrLvxl5saC96dujjitEGFnciWeCfCwz8RHvzX8EAtPB6gZpLxQ6rCHt0yJ667dbVbzrqzJ9qDLC10LR-S1vPO_2GbkuabY_t8GO55mHFkD_Lvf9lyF1PmeQg2wKRG2FEI-Qxz7kF-L5I4hZ7dcoTJ3Pbi_wO5PkSuBB4AAA%3D%3D
line: 0
col: 0
error: {}

**Comment by willyb321** [comment] 2018-04-12 21:33
Duplicate of #205

**Closed by willyb321** 2018-04-12 21:33 UTC
