### ISSUE TITLE
Wrong empty optional slot on build exported from EDMC

### ISSUE THREAD

**Issue by texaspete** [EDCD/coriolis#428] opened 2018-11-21 22:00 UTC
On this build, I have an empty Size 2 slot, and the FSDi is in the class 1 slot.
Coriolis shows the FSDi in the Size 2 slot, and has the Size 1 slot as empty.

https://pastebin.com/vaev4Y48

**Comment by felixlinker** [comment] 2019-05-17 17:55
Duplicate of #464

**Closed by felixlinker** 2019-05-17 17:55 UTC
Labels: duplicate
