### ISSUE TITLE
Module import fails

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#467] opened 2019-01-29 21:36 UTC
[This build](https://coriolis.io/import?data=H4sIAAzHUFwC_-1aW2_buBL-K4aeU4EXXfOWxskme5Kt1w66wC4ODEaibSKypKWoNN6i_32HkhOLshPJsYseHLQvdQRxZsj55psL9dW6zeIy4YV1-tdX62y5zK7T80Tk1ilG6GT94CrLcy6tU1I9u1Z8aZ1ai1xNl2WiRMTSNEunM_HE42nC5JxbJ9an1DpVsuQn1kiKTAq1Aokn1iTJFKy90W9dMRnnmUgVtr6dtHS3NfvE0DtLeLTgSvGElSn8kmvtSx6Lctmp_rZ67X9GP_nB-mm3fuqdWBfpXKScS5HOrdOv1sek5Dn8oa6HsIAEXkBQSE82z39jSw7K_uAsB3hMVCnjlbURo2Eg_hmMVzH83jzW0ihCKACkXTyBcrHkqWLJxWzGI218kfNIsGQq-SOX91wyBQZNI1ZELNbI2140vckiloiCx7B83Fw2OH9ZdgPPE1B9ogNCzASXdUjcsHv93LplRVG9VhTXxS9ZFlen9EkKMJslnxnsGgLEBqvXv6lN9LE-r79OFZ9XjjCFoC0hDmpIwdi3nYCGodMUdgcuX7LkJmNxp01uQ5pjI-S5TUlncpmVcsRTrvSRZGmneV7TvIDarut9---J9XsJR6xhhuzAd2DrBk-Aa1tQLcD-pBOpE_3WPoHyE6g_CqgE_joSRrF3XIj6GIdh0EJpSL3vAtIebIrNLBot2Gz2ohncvepUeQcv7ZO_aGdU-BR7nrcdFVecqYlIH26e7Xt-cM5yFtUwaUTKmC0Hd2yxHSdYb_oo2MU2bWLXoz414AIbv2VPYlklwreBYoaBAd8xTwC5dxCf3QYZceDZJAyR67bghkywLeAUCzjFjdtLKbl6y_tkt_drUuziPJ_6obPt3clC8CT-mGWFAhvGvBCFEo_c9OlQxGLwmSkdz2m6gwJRFwUWlZr7tZoHWAxlYzcFXmYy4oOPSRY9bIjPfQ08exBX0OQbYhPIr8APDe-Psi9cDiX70gONZON728itQz7jacSfra3P-laXzHkiqlzSgU5Ajf7nbBQEdqCfhE01_6mPs3YeA4Wdglt4dXzHNbdfcff7RTq274OVuCkSXJ1kBWDrYKFmXBHX883QMsFWiH84mkYJMIu7H63Sn4H1M7AOCiwfhX4YHjGwoE5CcKLhUQPrRagZWJR-r8ByqsBaC1arnD9N6TQCLOZCdRdbC5Gfr99tiFnqKQaTEZPz7J6t4iyTa1EzlhSGLPoi61y_fcVUtNhlEavqzulcQt1NO-2qq9S-lOHtoIwqNEYJS9W0FsZjky6uoBmA4ioVO5giRN1x3K8zaGKDOGZR1J8JsF66keN6doA9B3lbXNAoIzuC1rWJDlG8kerbgYuRY7QvujwFxhORAIpYdW4X2RsSAMy7ASbtBEPdTRiAt6a5Njuv_KRjwOsbAxv_9kSJ54bbKKmXTYdCtkvvkcxmsNdMDkZg_I50Qgg6JtmbLsbItR3tH_I-uvdt19v0bLbj-YageiufciWg2doB5B3mOa3-1Gs1qC8iR1zOMp2CezAnRmZRslOmxuAY0vperQz0ImaLips9gwYer13fA3RoM-pjIq2NKvpyEyLbqLucDKd1mm2T0kXyKICWbplUZfmwo-_zjtX3mcxEbOe9zGTIwS0Pwk73QhlyzXGdg23HdZEftIT2xgSwWtM82wuddi8ZIkpNaCwgZ8lYQhVQwcPtC49LCf4Fx87UUC9upkEtNhHAKGWeZ1I15ZLuAT8snNQL-8KOhq-kxCFUNVLclyqT0ysxX1xK_ne5JvcGEKG0Ggy_8CTZNaXDnVO6itXjhqoZK1R3JQ2b5HJwnqVxKVTRo5iup4xF77RnwMtxbTdsl9RriWMeLdaXLx0SG4U1ZFAHu62CsqaL3hbS5vSOYjvcQdz9raMN6xw7gMqhKW2ygtpzeSzb1tIOse1Nwt7C1F7U3QZ_n0DyHYTprnaUp1AYAHLT-Zil81Yf-mspxeC6WCwZ28HgxD3a5K7VHxnEW5t4px2hJhFLz9J50sMlb5Wrz1vtmBb7RkYISQi5BdIWbt9ruC4x_VtUJheVW52-ZeCYxUy2iXZW8gRat4emqO6e4xJWQT_w0JNiA-fVQcUvPNU3DQCRdYfauv_gYnC-4CWI3qZW0m9IMZV8XmtZz0E6RhRAv6DzJS6PVrViajS_gY01o_rm7Bcs3ZGs32YEansGL3-U2QOI6S2rOTsJzTuZ_ScRNLT1tsJNTU08O9Rb9Q6bR3zYHp6ALrSVld4zljBzHZyB-za_1sCav2C3Qa_0OX93TBPgP4SnE72wb6GCdxQqV2WSjLlIZ3qwpjGtr0keV8Oy3aRNeALmDn7lbFeDho_VxTc7M9f23hiegZ2JWpzFseh1tUaMuzWHQKfmOuakd3-wQslcgXUTltQOg0NH0n2kvgelr8ptzQ1Ic35WFekAEmmARAOW9q2pK6zSCqv0J1bfgVXHdnxI6_TYYIUN0BC5-Nhw3SX3OIB9kdyCrLPVVx4Bss7_H2Sb98bE9hwP0yPiFofI6Fp8O6S-R8ihdxPhFgoCil1KDr2g6CP3fbcUr0p-9W79ddCSvUDrVqDd_uAImiFkKJM8Z0Ku70PI200ANXV4DR0_PjDeLOG3jzRalOnDqruOH3KeD0ZJ9RWTdaTwC4yJm1kqHxZ61OgnPT1l9ImDyaEpo8Jx0ARyCGUT9Q9NGX3kvi9lvCq5NYp0-1U5Tt_ouxUgmskVwu0eubri48cQTb6faNoWrS-KuGJ5LjMWLYpSqO7Po0f1Grk6Wy-bVMsakh8zEQHxRA9T8MRTp8DP4GyefNaLLO1AfYm6uem06geaDIJw_TuGI9Bd-MUHQu7WL6w551oNomzJi4FayKyc62-9IKir1_XHflmp2y4FjABYW2o1BOHwA8IfSHhH8Cl1T1Hwp_XtX42AQBl6LgAA) does not get imported properly. Modules between slot 2 and lower slot 6 should be shifted one down.

**Comment by djadjok** [comment] 2019-03-07 01:13
double that - but with python and empty 5 compartement

**Comment by felixlinker** [comment] 2019-03-07 01:16
Could you provide me with the import link you were using? That'd be great.

**Comment by djadjok** [comment] 2019-03-07 01:27
here from EDDiscovery - [https://coriolis.io/import?data=H4sIAAAAAAAEAO1bW3OjOBZ%2Bn6r5D6k891JcDJh9S8edSe8kG0%2Bc6nnYmqIUELYqAjESZOLt6v8%2BR8JJ7IARuMGTnVo%2FtMvSCfo4Ouc7F6m%2F%2FvjDyckpfsRZcfrPk9MrhmJWFqcf1PBiRXI5Ol8XK5ZtBq9ZXFIsYPw%2F8vfJydfqC6Y%2BFziV8rmSD894ykoeLjmKsVP9tRJbUKYWq%2Ba3Jm4yGC54iV%2BH5pwwToo1TFjV4LcP%2B5ZNJTLEI8SX7B6tY8Z4w6rncvoSFdGq88oT3coxjhAN8VNOGcc8xJQUuGHpmRSzhnth9bzwTuo3vFtH7HmP6ovawy36OSvCpMS0QNlDKMh%2FsRtGFAnRtMMXIHcHcsOuTkmCRZnnjBcKwKQCYDcAuALRRSXaGYP5OvopW5IMY06yJUy8oIGZj7TEOYwXn2cStj31HWsSOB%2BaRP6NUizBXBMRhVdkuSp%2BxfLf023pK%2FBBClI7j%2FilRHQDynCs7RnwQpIQzLf8sPp83f4hn4vu1XNPr0FF2yuq2S8IQMoXMDzfezt5wwm8PqLPQhPDfCtyhYX4LH5iLN5odHv%2B24dOwGBL8VLpfh86F94%2BgM9Uh9C3NRATRMUuxtcfv23r99NTDtueAi0i%2BilJcKTM6fRZ4lsXO8XKepSJepWJug0meo1IVtmZGNlEPd%2Fx3KDVRKunhTPCd7fjxTzdZvO0dvR%2BgHXqjcAyXWNiwsfWWYFl6yy1bgbdTHXO%2FsB8xtEfe1FOjYnnaxH6hlvztiFcqdq%2Bm7wgKaLtDm97Zl1JNU1OJg1Sg6jyBeoc84TxFGUR3o%2B2CUYNrDku1kuMiltU7EcJ5KNlKMtw%2Bm38SPw0B9Yp%2FsXuwyq3Cz9SFD1ccBKjdWhaDTT1%2FAfDhvKcogwXKM85Q9FKlM1507yS4uuzjeDijeAQSKRrx0QUnNyXBeOKtv39tF1Rwav8%2BNztO%2B3c%2FRZReAlJxgXHv5c4i47L5r9ilLNMnKMcRa2B3TU8R8uWnjWSX29g3uJoBUXBfscODCuYal3bM6wR2UevTMeHLMnqkCVNxtLnBqlWn55h6nd9rBi%2BWAtw%2B%2F8FdW6Q%2FlXq7BV5RI4jAsVojUYTJIp%2BabN6hAwMRScOlsGhe3HXKRYInAnGxXbm3lRc3qIYDdi%2B2ETicxY95KRoWE%2B2Y%2Bqz37nqZV6EK8hsBMkeKCqzaIV5WJSc4yIsSLZuwHEHw5eIxzmD6DPpDMXWQfnCSITnkIeEX%2FBuKfCy9BcwWUyV4LBbvlqDVcecPOLtnkaT0V1wiLewFUkxk%2BJHqNmCSWvcv1jMwiuWLW9RtksSo4f51grD9vQpu63L2EdrKQSOMZXV5EQH0dJiHK%2BYNA0v0OEDmTE0CEbVqYz0AttwgyDQd4%2Bgfu%2BvyYNiUCJiSWmP6%2B5xR7LgPRIkSokQhGIuWSghTzgOUxyTMm1q3KiJFyLs3tc1j4Cme8O3ExoIxyJF6skxTqCewH1ixMBgIsrKWEQoy3BVppn72XoHhzMyWfvAKMG2I9TJeqFSi8P42jQCz9vpD%2FenbD3pTAxtxusYtXRzCM5ZVFta08sOvKnv%2BZJxPFNLjZLfR%2BLua%2FR0li1pS8fKNFwdPst9T91qdWymmGYr7W3qBMlv0woXUmrYJKwfBHsMCPJkS0SM5bo0UEGYKAjucPQmIcScZThiWcEZDSNGKWwngcJAAnL2VyMKkK8Ajc5zjuXa7c2o8xfcVyTNIU7ozr12ctxtzhszR4XkybVdp9aSreWpf1Waak8N3wxsLdW5%2FXsQI1KJWBFM4yUGMkfPrdSNNztVQ2CP%2BTo9Xfrgmmo6aa%2BpFuoNfnp5gzuoilMSvbcjMXdqWPJg1NeGGssZKRLeYtjn1mMRx%2FC%2BO6M4FN1Hzh4AnhZjUF%2F%2FLcTpSAr8Gcy2INEtFkQUradgUFHLhmSgLbWcwJBWURccBPDGFzoABhxmp3P7f8gi22wqx4fpS8uLOYI84g6YJ2AK2sztWJVsRaQhxxsulf2mXkx8Xy6X63u0VhRsa5KHad%2FkoQuCVUkpxyRLGI%2BwfE%2FdlR0FxVNQuvcWX09e%2Bh6qWe15zCXAv92Bfyk7C7PyyPcj2rsw1vfT14EpzKzqBjy%2FECiHFquzOCYy9dt%2FYmFPDMcDd9dTmTNWCdedd2Wd5jhdomxFuzW6OzLtvg%2B8fUh3bMQHkW%2BduaJVmT306Cqqag4XiFAci5InKMLPbas9bTNFfoEivx5Ns0ObVZZrtZLfplkFakJZjOOjEl6X7rj2fGGk44XZYhHO5Q3iWxSTcj8vN3FX7yOQo1Vuqs9bwmIQmTG%2FL7kowiVJ78EV6O758%2Bv1Wjl%2BtPYqhGvHb6%2Fbqhsd7%2FE4zDIN7VnTSDFa70qWMQ18fb%2FS8GoyQ%2BC7Rk8kLdP2vq%2FX2MytpQvjtXxnKEVLfIEoZUkyBFb3AKgjun5aUkiHIDqB%2F%2FRy%2Bx4HX4e6vWt2cvubR8yruzLHjVWVacwxX8i%2Bbbw%2FHtiGNfW8uhfVPG1qBA58xmmKVHDbDoBsbcVuG9NxavWtC4ya6A%2FBQKtIs6GYH4KyVDKOqPzvUm0Ig9qNwDpAp12PBwI8S1N2TkkuM8m9CH1fz1LBWHwqEW6Yv%2BV6wbRLCnXIze%2BDSoKIca5qmlCsMKVHItixK4G%2FEcGahuv7Dbz5f4L9GxKsZVi%2B9uhuLIKVxwk3yQXhbfdyHfXRQfQMT35qzY%2FBaPZ9B4LKW%2B7W%2BX58A5T6A0UAkkU4iwni65CzMotFvxgA5Jkkr9dsO9yd6n%2BtTH799uMP3%2F4E98mQXds9AAA%3D&bn=Python](url)
while in fact second slot 5 is emty and all is shifted down

**Comment by felixlinker** [comment] 2019-08-24 12:36
This is probably related to #464

**Comment by felixlinker** [comment] 2019-11-26 14:41
[Another example](https://coriolis.io/import?data=H4sIANo43V0C_-2VUU_bMBCA_wrqM0RJmrSBtzEYoMHGWrSXCUVucmksXDuyHViG-O-7xG1pwdCGddIm-tTEuX53OX_n3HfgFrjuHOx0zgVJRak7uzudYU6LeukDJ4ngKanXLkRaMlC4_OO-c6ZhshgQEzkRpYzHkqTgNQgmGqp5UK985XivZQl4fSmpkFRXuOI-7O48As-4ji_FHciCEbwc0l8QxR8ZUWqJWsxDWpGP-ZhyaKh9C3VC8GkTolphT6sCZCrprUH3LOhMkgmonGa6iWuFP6cZDMuiENI0JLTwGcYoE9O-10dUaUlHpRby9Y6nj4GtsnwqgV0RfrNYfnepPRigMaAVdQhcCaleLBldJOvXSZFYGwWaFIUUJMlVSTUs9cA8ltWziLUyTOoJIjIhcixGpEqF6eKM3qznRCd5uy7kFFh6AhwkmW1g13QjjIdaCj5ezKLw1_NihVHBa3nw1kwLSIqEA8x6yEoo8E5_QZdr1tPUA6A8EzKBtCaf48nCMCzE628lYQbsmaOEZhTk9DA5J6MmsGNklOSu_vt3gulwNXC8MKoLlRTLIWy23nX6UZNFqTN1IkRaw5vuzHnz-rANONc6X-T63r4T-BawF7qO-5TsLpOP8ZXH1SXIAYyBL2JdJwosUNfprSj2UIob4A1vQIxV84ocr28r1OmuKPMz7p-myQAUDi7hyRI12Hf2LdRg9dtf5SAnL2H3XMfW1T1_ja7-LJhQeDzayWHk-KEFbd-v690GiPpO8ANH2HGWQWJGoICEEharRo84B8JQjYelyTotZpN1KITSYObKnc7V4kBpyqucyLQQOBneZkZqltP0Yfq9aD9PeDzAuMm-uO2-49sMDaIVu2OdTs8JrWb6K2w_ggxwe2eVm9e-KJmmBcP7pRSRY5v_NXx6VX-v3_z_2aD-iftYaq_3BugK8dcvdV3pR1PBtHmbzcjvb-Xfyv9e5e9uVv5TILfVUWns3ZD8YWj9Mv-z7ve7TvQ35N_zNy__G5kr3F-f2tb9JC_5TbUZ9YOt-lv136f64Vb9rfr_ofrXD78BtNNUCPkVAAA%3D)

**Comment by alex-williams** [comment] 2024-05-27 12:27
I feel like this is directly linked to #691 there is something wrong in the import process which is occurring in both of these Github issues. As this is the older issue, I will close it as a duplicate of the other and refer to the data here when investigating.

**Closed by alex-williams** 2024-05-27 12:27 UTC
Labels: bug, beta, cat:import, duplicate
