### ISSUE TITLE
Error exporting to coriolis

### ISSUE THREAD

**Issue by RBalsera87** [EDCD/coriolis#220] opened 2018-03-13 16:58 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAAAAAAAEAO1bW3PbuhH%2BKxjOdPqiaHjVJW9OHCdu7cS1XGc6nY4GIiEJxxTBgqAdnUze2l%2FXP9VdgJRI8WJZTvpUZ%2BaMTS6AxS72w7e7PN8tHllvndHASuiGWW%2Btsyy1BtYjjXP467u1zuPYehu4rmePJwNrI6I8Zpn11nXcqedMnIEVUrkS1lt7YCmhKAi7o8AZucF0YOVJLGjCYAE%2FGHvBj4G1lAymXdI4YwMrW%2FP0s1k1lWLD1JrlmWWeX57D02jz4OPfiiouElRHK%2BtORuPR2Pd2Ot%2BsBUv4N%2FKOZsz6oQfIbJsptinHeOOpbU9cx3Ph327cNWMJwwW0LI0iybLsQBimozF%2FBHElc1B6zWis1nvTOLb%2B0VqzOGo8yNNyJE8UW0mutriFYOQPrJTCsychH9ADE8%2BGtUIRPqRcvZOMhmu0XGEr8W27YsktaMkTnqzQomaVnUe%2BW3c82X6iMkoFTOvgE%2FOyYjjbnwbOdGeAT6maf2JUzXjycEXzBJaU87tcSqbmOBvYJhZh4SMUzEDQPDxnWSh5ahxj3eRyxTKCnvtjRsBGioAOglAS8SwVGV3EjOBgsoCxDwPytObhmvCMgNMTwn5joWLRkNyyf%2BYcvEDoZpMnHGcf7o%2BjOx0HB2eodMfO6qiOsXcquTDmtn%2BAZWvW8f9vnbp1bvAo%2FkksWu0yGo3H7h4iStk5YMV8pmCfzJnbftUcCcRG0xDmaaGufYquDup6Jjcil10e9Gy%2FCmZzIz3%2FKGnEnJrLrvhqrZ4Y%2FpecxbHYtvlupmgSwbEhAFEK%2FABPCV2BBTJFaBwTtU3BIWJJqFI0fKj44%2FQN3ognJm9imqj2TY5823d3m7xM1FyPSHHEfMZ%2FZ978fUyzLKhtV8sQM23LRt%2BLJMs3sJdlzmBbgqRaHveIB5cUQFPZoA%2FmdpzTdjmwWLLiCWPaj%2BXvhabXVIaC%2FOWJaU3Ll5eI47bt4qSShXDqqhvT%2B5q%2FEwKgPLJKiavd7r88Mhmu4a5iEalbYidZt8fdGuKPJWuahGwDmpBYZGAdYwayA3MCxwP%2BCgGw8TUErNzQGIRppI0oxSOP2E4iKswKYM4kLSO4UIE9stgY5ytcCpfJjRQrvJLmsChf8lDLa6j%2FkqslVwpuggu8ZO7gEGqo%2BrAEMc6ScItShZ%2BcoQ3AcAUTXWYfhYhKf9TBi7D92IGFwBTT7b2ZwXoTDG37D%2Fo5OMz6z7%2Fxmm1T4nJ%2Fye3Wt4fTg%2FWLs7JXYD%2Fs9KW1V9%2FTlIb15Z2h4z6zvDkQYTm2oYPj1nX4l4VhmqXgNhpfHzqneD5P90EZ76HGwCCOvwYU%2BaAPd9YZ5%2BNpLc6NuI5x38S4W4vxu7XMIQBk1hbhnwUezTcZ7JLhwUzzOEM4M%2FSnEtiBPZpMj4nr4l31LukN7AsWc7QwuQCChiKN6HYa0V1s%2BZxL7ZnDuNbPybkEikbucs2NOkP6K1driFCI6wXsE7RO1AAvYRwMF%2FMupgf1MMYIN1EbSfpEqITLmsK04HSI56WQ1ehmcolmBtBoBLZ3YmDr03kOS9djetIf0zc7jVtianJkTBnjIzzcUsVq6%2Fv9y99VLNiigG%2B%2FDlCcVwDK9EWb%2FwKnBzZyTbOsroL7HKgVI8kGhzbVGA%2BDl6lxsz9bNU%2B4wdieVn6OVSuPFU9jrsPwQDk3GI6dFwOeieV2sLuQsPpszZdKx2oX4Dlundh8AgtIHaAa9II2YnMxO2%2BDu3P2CAEKoUw1UxNPwMBzmC2UOc%2FguaQQlTq417iIgcXf8k0K8MBAf2DemEgW8FgjPp438UYnMZ9fAJCw%2FfmVSFa3NFmxFoS83IETSJKGVN1oOBHAhkSpwhiId9p%2BMMPTDkGryDUgixxsrBA2SQgMDPnwIVEa1DAUrQ4HBP7G6GhAZfBTodJ5hv70QqVzLP84QAhn6PWvet0OC97rkHHyGqp19F7hJLXjojMM3OOAkeOJbIfGwAVMezH6LLOoHXqu%2BJLN8jQVsjOfcgK%2FBjuVId1kC4VIOXELAN2yVR7DtQkpP11wZbJ8TKWo2ogshcPPDLcwOQJkGxsG%2BQkQcAInnslHwaWmFymPhQKCcss2WB9oEjYX8rDJ6bm%2FDhqeQSYPcSw6Mmsw0mTaTDor46qpZ91SJsCqS7Thdfl6z0n17j98%2Fjggs7%2FNtK2%2BfrgpebqQVUyejBz%2FFwDyKalo1SQ3xUIlz2%2FCs3lDLkSYZ7vctG6qDqyeGRuhWZ4YTcFqZQajn5lsF6AcTyCCuGRRjoyVJ%2FCrymVywF3N7jon%2BWl89qtWNmtJ1Y4gdsXgnmTthfyuTQ%2FA7qn%2FXNJYDO%2FRxJsOfbeOY%2B2aGE%2BeaJFi8M%2BwSGHcW2bcXtdjfKRnZDm65W57mWda9AC2O%2FVHR3qmWxMXPDN6gWfaLXKsZ3os0vTMsYWFqIIyrdfeLY1oJ5a7Xh3LZyzJAFCrJLsO4YVAb4k0y7lixXUGViQLmvGQRKyomw4I3HKJ2u1JA4xCw6DN9fld8JgrXqsyjsaBe%2BLd1ovsV4yT92uW64LBIcl2D4HdbH%2BuS8ZfjaGbUK7fEvOazEKaJKwHvq%2FQi7piqGkQcmb8PTPjyGJLEiqleELb4IsUhLDKoQXwIXD02DCIiGkMLyV3nLsB2f6JkN3ONZ%2BLwz6qeXQBwFj%2BTh8TtOkZ7rpOeZ9Rw4zVDiFmdFMd91h1GnUAL5j41ez7JNY%2F8iFJOZLx%2Fv0fmE7nLL6jyUNXfHuBXYvvUr4a4F49i8ayv56yNcSFpCtM7hJFOR5PpA66U6BZCxzWortlkjxd9awE8XQ8Dk6iZ7ofcs5CGrc3NLE1FQS7rWrJ%2BYdvaSwkNusk5fEipr8z%2BT%2FrTs2Aq9uOtvOoQ2VQ2mt4ZxYKkZphxj1%2B0z1aps0%2FF%2FGWhNigwJ6DRpE8Mck6nHkK6Au4ob2V4QwoFIo4BljWTyuOGjtTe2p7J%2BcSeveuOWVdDht59WTrlqWUo7s6KzxnF9fkrwlvzbLOTGmHJ2%2BW%2BhqE2xanQzhFHJQJPWhgkfcUCXAGR5qRhRQPLNm%2F62%2Bxjl13HExPz7S0dTyTJ3VGrl%2BP3Pf4fcUtDR%2Bq6VW9kalFCMr0Xc864c6KQJYgrGMYwhcTAgo8YgMkHxi%2FnkxJmmRLJpu55mQ6Pqo30B0cfr8B3NEBNdHfUXw0DbO%2BLNMIkp1ka6AICYSMaiDjSU7jGJPtshsH92fZ5oWAwYcrDWw4LZUiR74CwfUI%2BF6LGieYTn9FOfCFHOXAULsyS2vWqRub0YAADSmSTjM%2B62Ys14e9T55hV1RpDqI5TJli7uuE1Q4qwE7BVNhhMbDwAACXkqYEaczeLA2eSmH%2BDMZTPLxlGRDngxp6g8oc3trFYISNcnTjDj9kNJ05hW6NdGgC%2Bc1xfZU%2BTY5nM%2FqmRFbZYZZnCqe74b3qBMcaZneAO3sux7Zc8Nusrr7L61rZz5HNPs57tFvaythwRgP3mcPRV8j2%2FOF4cowXGlYPJm4BYubnmVhpZ7i%2BMxxPX3QIZkoC5Jlv7falfGfyXF2mPANZOb7ZzneGE%2FfF9WUDSO25tr7Xgp57bQTU4aB8%2Bi5frbbv6FaPclvLpsCiGSTIW3LP1jwE6P0EOR9tvdjOyoZLBJG4Spj%2B%2BmQt8Hpf6ZvrzUIX%2BR7NTNUM25l4o1fy3ZHZRCffPWB857ArHrNolsslDVmRKjc%2FqiveV3Lp5r6jR32RgbtZHFPIm0W03SXROjmJcok3O9NZAT2gdK7jBvaJu%2F%2FprbyyytDTzcN3b%2FTL5ysMlxusxZivkoqWXrPIUNR%2Fd1WG%2Br1cL0HUSw8%2F7culjq7da5p2J6bzz16%2FHU27o5H9fDaba%2B9d57Hq%2B56iWUzE8oVx%2FHVP576FhfRXEnT8jnvj1wuw2V2l5CbW3kGonXNIKR%2BZ3JZBXAZkLZDPyZu%2BIJ4dHa5OoD98Pv3TyhJSz1KIDRquZ1iz7IJszxnXO156dH1oO2CXMqQidPh9IbImnW1GpPxuq9ZWzwYk04BAUsjWMGvDiKSP8IqHGeK7bstDNqPzW%2Fh7CdkMWy5N%2FhJjbBdVAVDmG%2BQCgEb4TaLWsvZBg3vSl8Paovc6GboXPGw348T1%2FUpGpwVvMJ29ZwVNqiSyX%2B7PZqT64uAb1fr7V9ZqQPlYf9YNl7AGgcNbfJYv9CP8vVBfsUwt8OKu31O393i8JV1oSFzkHPOotw7K0EjkEOn6f0pQxfHXz8qxxXPQ58d%2FAaEx%2FTGOMQAA&bn=prometheus
line: 0
col: 0
error: {}

**Comment by Marginal** [comment] 2018-03-14 09:13
Duplicate of #205

**Closed by Marginal** 2018-03-14 09:13 UTC
