### ISSUE TITLE
EDDI import not working

### ISSUE THREAD

**Issue by daddyoseven** [EDCD/coriolis#111] opened 2017-05-10 13:54 UTC
i have only managed to import one ship..my cobra mk3
the other three i get the message below

Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAEAF2PTQqDMBCFr1JmnUWMMTauW3qBXmDQ0QZiAvkpiHj3RktdFGYzzPvevLeCGaCrKwYOZ4IO7jhZAgZvtLnsK7yytdBpLRWD2Q%2FZUiyAVJxrzaDHMHnoOIPkE9r90nIuGwbZWY%2BOirtoZCs3BmOg4jiijcQgJkzGu%2F3DkUAI3TaqUvxM8sCAy%2BVJYTauOG8HE%2BISE80%2FTKlrVYla7aNO8ka9wVRKfMU4DIFi%2FFNv2wdtpBTY%2FAAAAA%3D%3D&bn=RSC%20Concurrent%20Thought
line: 0
col: 0
error: {}

**Comment by lausianne** [comment] 2017-05-11 15:27
Same for me, Firefox and Chrome. One ship works, others:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAEAF2OMW7DMAxFrxJw1iDLihRrK7p0ytAbEJZSG5BFQJQLNIHvXtpAMgTcPt7j%2Fw%2BYIwTjFRRcEgT4KDhSiQgKfjGvEj1gWnOG0Bnt5IxVsFBcc2IIvb34QSKnYMT6QxC0gkYNhbdu6AdnvCRryYQlSZPXZjj7TcGtJvl9w8xJATdsM5W9a5%2FTm77rtNVav2Z9U%2BVxwnE6fVGd71QYtsOr%2FMctLU%2FVG3eRPdZpb88v%2B4qnz0kgMQ4aY6yJ%2BQ3ftn%2BUqYdjDgEAAA%3D%3D&bn=Multi-purpose%20Anaconda
line: 0
col: 0
error: {}

**Comment by fregolo52** [comment] 2017-05-11 20:07
Hello,

Not one ship, we can export the current ship, only.
Right ?

**Comment by cmdrmcdonald** [comment] 2017-05-17 06:51
Duplicate of #109

**Closed by cmdrmcdonald** 2017-05-17 06:51 UTC
