### ISSUE TITLE
[3.0.0 - 2022-10-21] Can't choose engineering effects for beam lasers since last update

### ISSUE THREAD

**Issue by bgadzicki** [EDCD/coriolis#719] opened 2022-10-30 15:05 UTC
https://coriolis.io/outfit/alliance_chieftain?code=A2pktkFflndpsif40H0H0s0pyLyL020202xs059vm70dm32b2b2bm1.Iw18RQ%3D%3D.CwRgDG6QTNDMdYmXMcSohIA%3D.H4sIAAAAAAAAA42QvS6DYRiG79ZXf61%2B7ae%2FUqL6lcTQxGgxGwxGI2dgsEhI2MwiZodgMHQQx%2BAADNIjMHQqntv9iL6xNOk73LmS%2B3r%2FHtgcgO%2Bc4utWkX%2FOAktXBaB8JEr6eSAdZgBmbC%2BYl4r5w08yfu8BtcdI5qsOYtZqQTpTxOmIrKzJrD7EQMPNzmld5oytBPN8bP5eV7moynxTw8h2XIq8P%2F5Q%2FzQgmbPdsPVasVAwcvGuDLSdNpy6TptOnLWTsZ6UtoDe%2FpBsHqyqKlrXK30PuFn%2B61tOjCdXpclV3bbD0%2B59nC%2FC4npL43RKfAipExtTm82pTeL%2F%2BgFjw9gS2wEAAA%3D%3D.AwegLCBMKgjAbCeECmBDA5gGxSEthCZjgg%3D%3D&bn=bromgoid

**Comment by andr3w1sh** [comment] 2022-10-30 17:56
Verified this issue for all laser weapons, not just beam.
Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 15_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/107.0.5304.66 Mobile/15E148 Safari/604.1
Path: /outfit/python
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 85071
error: {}

**Comment by felixlinker** [comment] 2022-10-31 08:18
Duplicate of #718

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:18 UTC
