### ISSUE TITLE
Pacifiers are broken. As soon as you go to apply engineering the program breaks.

### ISSUE THREAD

**Issue by MurkyDregs** [EDCD/coriolis#721] opened 2022-10-31 02:03 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Path: /import?data=H4sIAG0rX2MC_-1cXXPjthX9KxpNZ_JicwCCn-7T2l7HTuysY7nJtJ2OBqYgCTVFqCDljZvJf-8FKcsARYnQxyY7DfdhdyWRByBwzsW9Fxf8tX8nRouU5f2zf_7a_zCbiZvsIuXz_lkYniw_X4v5nMn-mYsROul_zCY8Y0zybNI_-7V_ni7YHD4UN5f9M-xGQUh85J28f_8DnbH-Wf9nRuciG356YTKZUjlho_47Fvx-R2U-pb1rnjzn2i8KlSCEfdXyL9ANPmNZQdOP4zFLCrgvn7OE03RIF4UYpoKOAK3p0uGtSGjKc2j3rP8BLu7dvl18y15Y2j_zT9RY8DFnshqNW_qkvu9f0hmdsHsmBywR2ai8I89v8m-FADDo2CfJobc0_YnCQ8M4EceN4yCAUVh-Q2InQLFH3N9O6rCtaMTxghWQ70SRCcLzQvIneB55KennGhpeQ0MOCVdoyPHi2NfhHqdMzmiqhsYCyscalB8FBpTijmLSgP-3_SFj5KAVVhg66Ld_nfR_XMCEFa_QNnw-6d8UbAa403kxnC3Sgic0y4BREz57gvmfLsqx_JT1zwq5YCf9e8mFLG8H5EEqFFmu4aJrKkdzAcTEfdVdnfJ-nfF2dPc3030wFbJ4oFnZN43t5zxNe48LmVVsNcmOcBvZ5ynNZ3SYp4tJO9nvy4t7g-rio5Pdc3BIYuy-kz1ykPrG24PsEbAdBgC9o2GCHRhihPG-PHWxE_rvvQPSA-vjWIe7o7_w2WL2NlEtgvSRzlYc-kjx02T-ErEVDBtYqI341cTTJGEpkxREPxzzX9homCqLuoH-7or-t-qqjv8d_zv-A1Pdjv8d___E_Cdr_McRqiuAkMBKBF4UbxTBNZ9ML-icJqo7hgwexaj3Dcxl7xyeq2Dym95d8uOCZ9m6KNygTRSJkFLk_IUN8ylL03ZhXLzd0Bssb2gTxx3N81a-edqEBo6hgnvxmdn66Vr4gJwwiNbVZC9S7DoB9kn0LgMMvcQhigMd9oEW7NP4ist2EYROELsERSvAyPG9EKH4OCEAMHF_TbmmqBSFa7pCThz5rSHFjI142dz2oOKuvGyLW_U7R9JHFdVXFFavkxgsu-fBd8EeKw3WBeY6YRQdFlZjXa44ivePql0NyCV_YEi9H__X3Spcp39kRf4Abyb_rcgmDW7VUak_Zmz0RJPnYULzBDgNC4xIK7Ftl8FfNiJk8BB_PdY642rzC9LYb53BDtYWBYe4rn_IQkOAZ14Y4Pi9Z7ETkAjF0R4adYlDPG1NcILQBe94X2lhfcRCx93fA0TGAhOUH9ef74qmqRiP7TBxI-ZWyUrK08kiW7qA4BeWPsx2sQ7UVVvWqk6rnVY7rX6NWq3W1XYphnFDJDaYcpaOzoVQShuWE8ETU4-XfMR7P0EEAHPUJEKE2kSYl408LRsp3hvZLsGyNwLMgEiebdxGNmZZwt5-rJ7sTnkv85QvHc_t-ykq-o8DTY-xmkGDYt_Dk4M79MBycAQpNNcKqxPi9K2NNfbvDelGjufHtd0aGNi0DGAP7udW7przmoPziYYJGO0cb6AwXlH4kWevtdWmY_CflsEkxKGZePsyDFbhvftlOGxthSOvjcPXjL68Xi7qObE7lvbOJc1GoskTinajcDJdZM-v7QweLODn3jJJJ2R-LL8HOVq0bq67N1nBJrJKCba4Fr5Jo9DfN6dmhNam83RsTfrICWKw2McUJa4aiY4nykbIg0W5Av1dlhXyxSV57IXlj1YlccxE8H6y9CJtzn3fwWrOw31DG23HxzmqMl2gpvrzHpyExInC2g5Qp0wbZfq7KdPrlNkps1PmV6hMv1Nmp8xOmV-hMoNOmZ0yO2V-hcoMbZQZeggT3KBMluVCDq9oXgwSmtW2wjjNaO9KyGKRsYakT4japWLPdD8w0ymGYFTnMib3qoRzA5WpaUB7BKPwKJbP3SIdA7BtVyVR5iavGtFn1tttZqNyZpe4MBVq-4wOE5E8z3nRCgUanl8sr9VwZupcDZUJlRPxRF9HQsgNUN4K6kJdfE2LZGq5CgRewyrwQc7EYqP5H7CUZaz3HaNN-cXW0lNagdsa_UvG5r37lBbqGY5k8AOjsqVG4JqBhUFIi-kuBtY3asfiqMytuwem8cwUZuAEGNohh9nXUxLXk46nJHDiCCxicKidxUvsSC-2Uju6yN8syZV0liSRjCYFtNsqoYqxtp5P0MD5cnEGnmXFsAKrV8VdM0l7jzTjDQ5P3FpvrdDnJfqUT6ZV2V07-e9EptYcNjoW8yOjRhL5jtr2QcF-Hg8OdFKSgJhCKkdUK9ttWQr0RcVzHUL8mk8CSixgjHjCQZ-vFsl6vaCO-O5m2gEL9BlS60Bku8K_88bW4voNm5PVbcNLLuvW9l6KMTynkL176HqTxXXbyMcqcPHCZFmIaVHVAl7qpHcpQXo2XvYOlPH04mbsustq_f3c5NjRTg3Awu8CvGG3ygf_NC_4jKYN-miq_A3MKuK4VuyxgrxncixUAJSwHWv0sec7itsxXgdWHFdF1BYRAtG8HDeKtrN7SQHF7HA7s7WyTMqzqle5LbXjBsN6NbjcVMF1xVKujEPvisqcNZ1kwa2h5DgfDafKUbGwpvDYvTtYYyZW5cV2tfr6zPp771BiD-sMUVwO3Fox_C77lNp5FeREgblVCTOyiyZwZDrpMcKKv5Hvbefc9BVmYyTL8xTAu8CWd1cSiAM-8bgoDZBV0ESwF_vr3LvjeTK8hQW3-Jmpv036fSxgJQFP9lLIJrsao2MtuvrUmpVo9gyJjPWRbAts1OCnHFaNxXwOIWE5-n41-m7r6N_CjYPqRlt3isQb3CmtCL48w3Ml2X8Wy8Vbj16nMAefWZo2WoDIyrcaaU2NIUa2ziaBu7nghc0qV1Wj5tYeTahXIIKrFARerZ5xifjAVv5g25kZY7mL_DBYX0LsO2hkrIBSYejXMlZLROsOek6k11ySyFiOB6_gzM6O2b8l4iH9a3cKdWpZuIbIdA01DVinf4KN6Z8NC-nvZckC03urp37KPj6qmShzVB-ySWpTX6svLtiEtEsjgQ7MuAZFqM1A5mVnc31G243jAx1RqedoFNJ4wVKIiZ91O0ta44YruAuiyWdLIxuRjSWN37JseZTzgfEMnNKkHrreMt67mLJFmUGp21fXLlk_ZMvQy8K03orT0Zufsp119j4NMQrBjDTwahgGhQRHt5jueFRQJSawX6tVPJfimWUPbAJ_rTvkDV6S7sDFjlmkCBM0eYWIoYSzObqpvxaFmFZ-99zReprHix0Sx7W4a48E0vpmwik4OAjHhxdpGlk0P3Qi4vqoxVxXTJ2s9KCFO-TNK2hJxcI_CA_V-biw_WiLb3OyJcJkk3IvwOc5V5ZjUEmtlM_xazkTaKaM_tV4WAT_5wLiJNU3zSvyjhD7-4Yj7AYHxf6uHvu7jvnqoHMhCrVn0I7iGwfxa-tZtRkKEzSY8-xv81Y03zi4vQFrZaRnlS1t1a7mA0ED6t0DUTOySh5YLOG6sDwIK4iyDVbKUkR6elvpAtudklJTbqmpoNNUp6lOU_tqyjU1RXbQ1EHtErNdT2v3YD-4RPRLROuaMtzgC18v0tSgwRfavpxCO9Jo54_cycTGVrxrviykcSfzw2jECy4yC5UYu6QEXLCo3L07bB_T8cxdQew7XhD6DQc9vwDuPo7oFuTt6c81oljk4Wq6CDpddLrodLGmi7DTxRG2Imp7EQfKwsjjBa7nkAAh78DUBa4XkQDJECG1NPDusrDD3avuZTPyHrLwdpJFVMrCqztmZSEZOxQ8_oLgGGngFvvMYdy4zwwfVLo-UbkfmDsI8XaP_Y6XsUQOiY3XG9c3YW_eu2v72gjjnRZoM94VTWD4bvmMF7tl2tTWc0vmfJyP9IFWk-1u3xLxzMmu4hbrg9CulfVuPNB_dNvN3iyCRRKcvqrKrR0s-GEGGGMzqY0cHNbfzr1PWfd72v00djy_Xi62T1n3OyQEzm4cx8c406_1M3TcACPs7WNx8U52qwqFsW4Uq1KbZJEXYsZzquZu-HnKi_YixoqfFyLdoZSxc206l___3eW_44BL5SsydDanAP1v8TR8r7enMzFE7Yf_79Wd34mnuiujqj9ZQedzKWgyzReg2SEdvaihGbWDVjfL1w_L-wfqfr0J9T4waKJQr5flcz4aTiR7tToccHOJjgWEG08qKJxnXuDh02IGwsVWYN_z4ry8fDtkPhc83QFzUF2_HbSgPPVsER_h4ubx-wz2J0fE0j4rOGVi0THBjAl5ETxhc_USuRe2zP9vR_kJ9MrSn9RtOs7nsrDIXIOAJOXe83bAqiTpbQ0CVat-alPQP1kSCWI8vPz_SCXdz_ojySb58ve3LZmPDx9_uLy5v3n8O_wAVr68UL2_TSyUY1qo0zcFnakWXOS6pxidEvyI8JkfniH8j_5v_wN9ySj_X2YAAA%3D%3D
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 84922
error: {}

**Comment by felixlinker** [comment] 2022-10-31 08:18
Duplicate of #718

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:18 UTC
