### ISSUE TITLE
Can't Read Engineeting on Turrted weapon

### ISSUE THREAD

**Issue by bazza14** [EDCD/coriolis#715] opened 2022-10-29 19:18 UTC
OK I'll just paste the error here as I'm not sure what the prob is.
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Path: /outfit/alliance_chieftain?code=A0pktkFflndpsff415151c29292900040404B1m9f4m3272b2b2bm1.Iw18RQ%3D%3D.CwBjYZhCIRhusm3CUUg%3D.H4sIAAAAAAAAA42SPUsDQRCGJx8Xk1ySyx3JJfEDozkVLMRWELERGxHLYGWlYGWhkCKF%2FoUgYmFhYWlhaSHBwtbewsLSIqVYaJxx3pMsKoHkiuGB99nZ2d0jHiGiL0tLt6XFvosSZY8zRG5dybu1iYK3CJFEeAVmHGZTS7LcFXHyc0T%2Ba0zN1YRKUfZNu0MtTvAhUuhoKV46ROUbXV47KKkZ41FjNnpmuF2hWVTzWROxeMlIJ1pSGRZJn7pEU6Bp0AxoFiQJ3unpTqOj7e5fRBaW30UkydumU1WLtTFBVIFUw2CSGpCnec%2FkOKJVHyNKXGf1OOGk9q%2F1u33WZwbk2QG5w2smv8D5sKu3eKQ39ZAimnzKqZTn9T%2BSfaVv4mx9irig0AxA4g7TzuNNI%2B1DwiQu2gXhE%2Fo8b%2FIzbPeomKuOqwTyoAcgKf0328ZsGxMk5aHNyo8ZN%2Ba5Yg6DuSAP%2F3AAEqE%2B3zcfrW5F%2BQIAAA%3D%3D.EweloBhBGA2EoGMD2AjATgQwPoFsDW2AliSAPKYAuAFgAQDSApowA6PowQQAcCfEQA%3D%3D&bn=Whack-a-Imp
Error: Unknown
Details:

scriptUrl: https://coriolis.io/main.js
line: 46
col: 84892
error: {}

**Comment by felixlinker** [comment] 2022-10-31 08:19
Duplicate of #718 

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:19 UTC
