### ISSUE TITLE
Importing data from ED Market Connector

### ISSUE THREAD

**Issue by lynchpinhags** [EDCD/coriolis#221] opened 2018-03-15 06:56 UTC
I'm trying to import my ship from EDMC and I'm getting the following error. Have tried both Chrome with adblocking disabled, and Edge. Ship is an engineered Corvette, if that matters!

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAOIOqloC_-1bXVPbPBb-K0xm9q71WF-21DsKpfRdaFnC0MuMGiuJBsfOyg68bIf_vkd2SPBXrCQwdGaXCyaE6NEj6TlH58P5PZgYpQafJjLO1IeBjgafMPowmKfRMlbZ4NPvwbGZp0tjX_1Mzd235MqkU6OybASf0RM9lrlOk-KTP5b5ROe5TqZnWsXRzeNCjU7VRCVjdVl8VplzJeN8drmMc72I4W87LNLZIpaPtzJeApFBSL3A_8fgw-C-fAN5IQ2ePrSif_l7EaeZvlfXKtNZLmGmFsSPOPRoFRKHtAPynzpRuR5vBxQeruL5AnfgXcosa4EgzPNfQvhewDoQbmbKzHsYiTqaQE8Ap5IpLKfc5ufX3-CIie9j5G_-_13OLcpQxSpRR38pmQCWUWO9UBfqXsUw4vnv1UdLVYyOo3vLKBo8PWvGTtWQFMLcp4KEMGVSjj9TkTKFdEYnqblXea5GK8yvRkYKAYE0GXzKzRIwFkanRuePgLRZo13gmQG44UxP8lMDMthXpWfD0x-LXM9l3HFcjHg-rpw4I37XkX9LcjUt6TalgxoHz9lu0vlI_CoE8kgHwlX6oMypkQ8uTJCHWI9okN8UzZmK9RgWe3QmTWaH1ZTDasqBvR5dpMn0WiZT5aCbgCIcrnUDezs6h6WZyJ73aKj_o4LRSQw7xToU428WSEKGg-LYsgVQgtOui2P1_miSRaOZkvcwPlnGcSG1pYpvZHJnP9ZLmTC_Qvl5cEGYlYRJr8Q58UUh8_PlVJ1LEy1SneRob18s53La5j0QARFWlUA6VVmiXCkzVOM0iQ6GA6dm9K9lnnYJFQkvrFmMj8XLnz3Uj0KP8yooRnibB5bxRSrblkupR1AFirFA9FkSb1oSTHN0-qDiuGlEdff7U8kFuM4vEzh0rZK8344CjoSga1GeL_LRZyXnFzJT4HL1_Beo3sqs14pCSigmQUOW-PVlST1UdbqIdp6Rgyx3guuVJfbrxx6KgB8qS-4JUpUl8sN9Zcn9mizx_4IqL6R5W2-JG_fmAaLcAazfU7rHFltFiBswfD8JYo_VJBiy15UgPliCEJhSEnZI8GZpjMpHhaT644uAchEExY19oSdquFwsUpM7BQyIiUrA8GL8y5gB9xuCoJRaBpdSJ1-Kfcz2NYFyOORs-bXMWxOhoBGKdqZqBRZE2WANkxRE057I0AYg7QPcErZ_RA0F8pC9cdi-Pehus_eeTA03LQLOcQLHmJqjKxnrpC_mLvcKPIiB1bmE3L6ohtwrAKvE0DXchiBYsDJ37wu3y9WNYj2d5Q_K_t7E3Zcq0st51Z_3XCohIrR6qZyaZXJ3qbNMx-paju9GZ_pvFY1K7N6VBIwQ5LeQwe9LRsc6l-bRR69anTmOIm1Huch3y9Wwe-UHBQ3bOKzw0zB-0Wn8LmWfHeA6_FF9hbB99ICqTyuhNy37nINRXiudgAcfqzncrztUgIKAMxpUM_kGnMNdt8mPKfPhx8G_zGAeU5knL7f3hZt5NiYHmw5JiMPqfX1ZDDhgLYRjWI1lcgUXd_5X-suFByZo46ifB47aims3cgz6hr34atRjBxtcLa5dxRKMAvbkeLEwqRzPhktdhgF9Lq9Cy25PCVXF6T1dXIi5vE43se9hwUx2Ihdy3HHJ00YVdXs0k12r8awIDVsKvMRDYbVIB5vSATd8zHI1fyVuK7DX4lZG1K_EbQW2O7dXTRpozavVJTY6hxDkzKh_L-EGcwuYcF3wdUjrDLhr6AT2EyDBiYNrW9iJohcTtQZRBR1rhPm-5mOzgOesatweIjdCd7RXpO031LQt0N6iSyQahPrKcrilwH0pzTg9-teDzSZ7ss_NNo8-pymYYeQWbQdBUzyLAuaFbGj_HUL8MMCCu8qmnGKcpjEQXWvlWkZyby-79WhJ42jD3eIn1gDoCsCGKoHs6MY6mXw4lslxMo2Vc2LX421aErILpY9OZmqZTPtCqJIZJPhgoD9LM3VyMIxWNFLCZC8F0l8cQJRjEhTedBinuY_KjG7fw_5s0juVXKsp_OooELhb80kaxzqD6baGvIHHcRWOIN55SSszfbxSpmDYClbzD_5h-QYjHq2WhGnAxAEZB4WbVdRquMIP-2vMw5l9-VUlw9yAUvNZe62Zoap75AwdkI58RKh6OoCIOGIbtvxVLavufdeLtsEvmNg6GnfzwljgqoXV4N6q-JEV84yMFWkRtts-9rMzLswUb8y0v_NIq37iBFxgWlQZXvDv764jFHKK_TUF8g4UQA8B2zgrWnZ7HSmQLRQCVwrE59gnawbs3RkEZVLpyABvYcBcGQjKCV4TCN-bAC8GU0cCaAsB6koACxSKNQHxzgSQXwwmjgT8LQSIKwEuVvPPZRy_ZWuNVduf9pEUQfZvru0E19_xbYSK4T49ANxIl8Ngv_Za2GivYfandXiL9hrb3l4rZNV_pdoCmUu176EkGa1Utr5KK-J9k8cVwqD2fEHnyTo9rrADnMvjCrWnaEJB9ntwhtHagzN0T_0y4FDVL8Xo_wLuEvCNTh536YMBc4ZIhfnJTE4mF3KZjGeWPQD2N5Rx6VQqs-N3nZ04zi4qs9sK1lAndxsC5eE58cCr1kqFB927Fu2UTnJPiNpDvT6CeNB2AANCEN6zvMarOSoXkPeFRECoyToLty7ZKveCsMaXEJ8wDMJnIdvvIVXukVpKyQkKCGMErCn0CT4gYe0lvN0V-S3FwlMd6aNbmVu_lyR9hecyxSxLhTZftVxt-ufUSyNBRd5VLBve-c7lZo78svdUkTdzMzOMKzyuYM65vLIAqxbwToaGWBg0LS14W0trBHZir4dE3PsgLubkTmqrBTWe8vYP-aJBG6nXrOmgP9pCXIs5v1ZzqHWY0X6Jh3-OhXGHvm6AGUHVG93oubL19aS6o_2laEIZKXLKW7BlFd-meuzQWoZYkwaba70YdWXT2VtVTODwpZGnbd9BAQA4wcW3UxtVnnw__Xq8euc50vx28uP76ZfrH8U_VqC_B_b5AruxLOCII_ri-1NIBNzerUAhT3NpI1JI0uB2oRBSLpM4lYntvXAhCKdPT_8F1aGdvo81AAA%3D
line: 0
col: 0
error: {}

**Comment by willyb321** [comment] 2018-03-15 07:24
Duplicate of #205

**Comment by triccaj** [comment] 2018-03-19 14:31
@lynchpinhags Hi - could you please close this this is a duplicate, as mentioned above, and will just mean more admin when this is eventually fixed. The team only has 1 dev so the less admin the better

**Comment by lynchpinhags** [comment] 2018-03-19 21:36
Will do!

**Closed** 2018-03-19 21:38 UTC
