### ISSUE TITLE
bug with edmc

### ISSUE THREAD

**Issue by amaxcz** [EDCD/coriolis#684] opened 2021-11-20 16:53 UTC
`
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:94.0) Gecko/20100101 Firefox/94.0
Path:
Error: Unknown
Details:

scriptUrl: /import?data=H4sIAKUnmWEC_-1a3Y7bxhV-FYHXMsEZ_uvOu2vHTnbrzWrhACkKYUSOpOlSJDMk11EMA2kuWhQJkPvetGhewA1idFt3nVfgvlHPkPJqSFEiJa8LA_VerCiK83E45zvnfOcMnysnkZ8FNFEGv32u3J_Po8fhYcBiZeD0l18fRXFMuTKwjL7yIJyykFLOwqkyeK4cBBmN4Uv6-EgZIOxYDtZsrb86_xsyp8pA-YKSOApHx2w6S7-g4r-ywoLfj9k3vbOFD8er0wJS1zTNAbwHX8MM2JyGKQkeTCbUS2FQElOPkWCUziifw6dHEo_4VGm6fHQceSRgCfVhYP73_NXNt_l_8qubP8HRH_J_51f5v3r5P_OX-ev8VwA4ppc0UAZmX6wOmzDKy_U5JmNxXjkhSVJcliSPk0-iCFBRX3nCGUydBE8JPL4ywCrMfHmsqfhFfzX-cZjSKWfpogairYEYmoSCTNUt_mSs0-gZ5UecPGudkKYa8oQMGeWIJSln4yyNumJhGQyZ1ovf9ZXPM1hkeKoBUrUXfeVxSueAPYvTkZ_NxxPG6ZwlCQsoJ97FaMK-pv4oAdsFI-JfktAD88CdQmWQ8oz2lVPOomKVxMIMg0hY_ZjwKX1EuB9HwC-kiIf4SNuPtN2XtqZdZa6muib-n3AXF9xtoaatu5qLNlITaMI8BoypEvOAR1HvnPCvMhY2cFNv46YXhV7EfRKmo4R-lVF4ug78_Gv-Blj5On-V_5K_yX_OX958B8evb37Ir8UvN9_d_NAD0r6BL9_CJVdw-uXNH-HzqgN3d-GLJZlYtyzDqVCGzMmUnlI-pPCYfiuVbdVybvFcVUemY6B34SBWEVr5BgA6tinjnZeB4TgifiuWrlrmLRZWTYQN267xGSPDrhJ6TMk8IAnloymbj8HeBY9b6XtCfZbNa7H3g-Qvp1MagqOmDO5x1wz-uTiELxB3r4vLxIBrCMs_vk8em65r3BmPHVV3NLsakd-Vx5prAffugshItWwd1eMyxkh_HzzGaxoC1TUE7rfzHLzMXOf5CUu8zQLijMyB5rN1iiOk3VE6B8PICc8190zoppTQMUSa7XJvRkmasPAiIFnoAQ1GacY5TUcpCxet9jmHi7YovI_W-XCs0-A7uG4eBBFb62Qi50M0kaaakonqQbO7jfSaJNbqslOryc4YQtucFMvs04nIYPvbSf__s5P5vuzkvEc7GYWdluAXnLB0FIjVBEXuXcQs3YCGbtGGMxYfLq-VoOaiyUO4BwVINCYLP4r4BijjFupQXPyIpN6si9CDjG0ZDTX0fT6PMj56RMnl4igr1v-uKmhSQnuzLLxYdFB3P4FkewNq7s-FXBPFx4-9_B9Qi7zJr2Xthjbx8Kg079sf4ZmCdHaSBSmLA1Y8Q4sEc8tCGK_4hWzVxo5WKbM_g2VImXdGE1BkpFSu24HvYSCt-FsVt_cgDeiOY2O0Jsl2gpa94R6C-WumW5ktrHoQJeyS7jJffbkSK4V7z8CqLTox-pq_rdxN9oil9aec-BS1-kVJw45EtkXPqE7kQrifBqImLsGKgl_i8iMoOCDIhayBy24bl2OBHhfoXhQFJXYLn_8GDIZCBNh8JWoVUYLkr3pFyfIr1CQv76ojJIsLS2iJfcKq48hh1QW9L_hqrbWEDklMvC6AEJpX7AE3MuwKLcE507fVpbfYsckExYezWUIBJ2R7Jewbaow8yAKJ2crDFYu6BlXLXediOWx0noV1Ep7QoHfASehHDYUzbg2ptASOLikPoGzrRMOfilak6OlcleVyp35Od-ZYhsQcU1dtwRy8Xy8RaOfeYhkqLEilpi7X60mcMigkG3yjQS2givR2dNVsBIQ6fRJBNdwlOoIQk31F16HQhljZACxIfkZSumOdYYKrbGX3kgYSs3F7VU1YWM4q6UpttyHMPhweAb3C6RkJp7TK7QfBJYMQe0J4mmUXDVrSuistiWUD4L1jHqrgOEYVZ99OkFURtgdRlJ6Dd7ZToPJM1anAou9CeqSZFYbajrmG15ma2JagdKwaWuHeW_k5W0BI8jmIjoKj5vbou-LoQw4kA4k8SY_E4G4NTGQ08XR7vXMMt-59ClcmjXFYXxHVeCeiyqER7UtTW97yMXQVCwug7RYI2IQmWRxHPN0tTBzDwGE5sKsaMzapMaljOXp7r7chqGIOkL29o2c0CJoKDeR0Eme-dDNvJVLasuNf3oo0yI3XN9-DQCu2QK7zX0QVAj-IHjMkz5vvOyTNsmuedNdISOYH-KzrCMv21xDPqDcTm1PtiJJOEj1fvSF_dp-fWy21TRPXprcE7Dy9ahPA1gzX0mW84SIBDu83QUfFFm4A23NyBrLMtVIHGQ0yU2ae8DXU1dfqTtIp3hka-Ny6ww1pmMD9N0a8AxYEvfOMh421_N01TC05W-y7Pe3K6cuoJa_ySc-FSdOhR8L74TSgu7WNtrdgWbGtKm6SFPa0ttsT39rzjPiEy20dgTTJaABV94UchvXWOuQhjIJa9aIJLYEKNJZntimx6qu2E3xoaDQUY-qQ04wAhUk4SfxxFIHLlCzuCIoLULNjrnB0q4G6M0YD_5NyRxA4fEZZCGLcq9dOx5T1Dmc0A_T1JIFXDMabGHx7o2HKQUKns92IiDSn7OJU9qsPeHRBwzOxo9mgp5oitGPLO2mOXg2olE8XUI0UgLsqT916tz7VetvHMFTz3RpUTb0vkfe0epW4T6OqonNF7WmKG7W4dsGC6S3dBNn1riG74LwucV4CLrq3xdsnkuhtb30VkEZ3NwLFa-raror3HDyc9B6CrMtC2iB5be29vJ-k77lhJnejsFFr8q-Z1OdRKHbZUx6Jl2NAR3rlqwWrbGx0M61Z2EGvm3acTaeLMVkUiHg7WWoB0mpG9CPvAgzsRfM4EyG380tKBagtgbYLBmSijYIBvI6E_q690rt8i0KmSyXRHw2Ho1OxvwF5lWXtZW-lmhf5voU0NCUsoH6S8QnxaAJSIhR7rV02hQojOIURcN2yUHZR7vEMKgxgCUSybmhugYZktJgA3u-j8Ujuq1-yMRdtTb6RK1I3UwB8Go3rUxSNUXj6OOYR8WZJxlLaRkAJtBzMF_eX44divHyLy4h5NBaB8JIu3X075FOwKw2eimEyzrOi-PGyJI3mLCnfFhoL67bhlVXTYRQUewrAArHtVt2fUMqTgtQ2Xh774kWngfLky3sIfwYXAMmLE-INmSgTQ1KoJCE1zQUY1jCCTAb57RxZAxMNDPdL5cV_AVV2vSCxLQAA
line: 0
col: 0
error: {}

`

**Comment by gopstr** [comment] 2021-11-26 17:19
It fails to find Advanced Missile Rack:
128935982 | Hpt_DumbfireMissileRack_Fixed_Small_Advanced | hardpoint | Advanced Missile Rack | Fixed | Dumbfire |   | 1 | B
It seems advanced weapon has not been added into Coriolis yet.

**Comment by felixlinker** [comment] 2022-11-12 11:35
Closing as duplicate of #681 

Thanks for looking into this @gopstr

**Closed by felixlinker** 2022-11-12 11:35 UTC
