### ISSUE TITLE
Missing Modules: Guardian Power Distributor, Decontamination Limpet Controller, etc

### ISSUE THREAD

**Issue by burtonsimmons** [EDCD/coriolis#299] opened 2018-06-06 21:56 UTC
Several modules that were added in 3.0, such as the decontamination limpet controller, the guardian power distributor, recon limpet controller, etc.  What do we need in order to incorporate these (for building and import purposes?)

**Comment by willyb321** [comment] 2018-06-06 21:57
I will be adding these soon hopefully, just need to get screenshots of them in outfitting with stats etc

**Comment by burtonsimmons** [comment] 2018-06-06 22:17
Anything I can assist with?  If you give me a list I can help get you the information.

**Comment by willyb321** [comment] 2018-06-06 22:36
Basically I just need the in game outfitting details for each size of each module.

**Comment by storyd** [comment] 2018-07-01 05:39
If you can enumerate what you need to update the db for the krait mkii, I'm currently flying the ship.

**Comment by willyb321** [comment] 2018-07-01 20:14
@storyd krait afaik just needs hull cost entered

**Comment by rlsg** [comment] 2018-08-04 08:01
When loading a Krait build with a Guardian Power Distributer the 7A Guardian Power Distributer gets loaded as a 1C Power Distributer.

In addition it may be worth considering representing the 4% available power increase benefit of the Guardian Power Distributer some how. In-game it shows the PP output as 104% when at maximum integrity.

**Comment by felixlinker** [comment] 2018-08-19 22:00
Duplicate of #313

**Closed by felixlinker** 2018-08-19 22:00 UTC
Labels: enhancement
