### ISSUE TITLE
Wrong jump range

### ISSUE THREAD

**Issue by felixlinker** [EDCD/coriolis#630] opened 2021-01-11 21:14 UTC
[This build](https://coriolis.io/outfit/diamondback_explorer?code=A0p0tdFfldd3sdf5-------32-43f2f22i3w3x.Iw18SQ%3D%3D.Aw18SQ%3D%3D.H4sIAAAAAAAAA2P%2BJ8nAwPCXEUiAMAP%2Fln%2F%2F%2F4vcBbKUQdz%2FbP8SYPL84T%2F%2B%2Fxfy%2B%2Fz%2Fv57En%2F9AVf9iYVJCF9gZGExfMAM1%2FAdyAVav%2FgJVAAAA.EweloBhBmSQUwIYHMA28QgIwVyKBQA%3D%3D) has the wrong jump range. Here is a screenshot with all relevant details:
![image](https://user-images.githubusercontent.com/9728715/104239153-58e31900-545a-11eb-9f24-5c00e3dfb1f1.png)

**Comment by SamClayton** [comment] 2021-03-26 21:24
I've definitely seen multiple inconsistencies on different ship builds between the jump range reported in-game and in Coriolis.

**Comment by alex-williams** [comment] 2024-05-24 15:20
Closing as a Duplicate of #646 to trim open issues down and reduce confusion

**Closed by alex-williams** 2024-05-24 15:20 UTC
Labels: bug, cat:numbers, duplicate
