### ISSUE TITLE
Coriolis is down error 522

### ISSUE THREAD

**Issue by bazza14** [EDCD/coriolis#581] opened 2020-04-11 16:59 UTC
The site has been unreachable from the UK since about 10pm yesterday.

**Comment by felixlinker** [comment] 2020-04-11 17:43
Duplicate of #572, thanks for reporting!

**Closed by felixlinker** 2020-04-11 17:43 UTC

**Comment by bazza14** [comment] 2020-04-12 17:44
Hi it's still down.

**Comment by felixlinker** [comment] 2020-04-12 22:01
We know that, that's why #572 is still open :)
