### ISSUE TITLE
Failed to import ship from edsm

### ISSUE THREAD

**Issue by meiergeorg** [EDCD/coriolis#236] opened 2018-04-08 18:29 UTC
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAEAMWUXU%2BDMBSG7038DwvXXvC1Tb1zm59Rs8gSL5sjVGnW0XooiZvZf7fAUDQSqWn0Bsrbc94%2BeXPK6%2F7eYOBksKLO8cCZr1UqMuegElciKTjNtf5afmvlBFeiwA%2FhvagtaZElWvD8Qzc8CkL3oLXz%2BSBSG5JzhIR6TrtQUxwPFBa0LUpkAplal%2B6NvK0X212dMwV8Eheg4vRnzobmptwErFonsJ4JgUYwfhfMWUH5ArKlQWSjMBh%2BG9llpkjjRyK2oUMy5ZDngZ3crtkjjQopBSojWm8YdtG2LCvgsAb2jYDdLuA5h4wqwPWJlCggTqOCKdqffTT2A2%2FcxV67f7a2kvMdJGByhUahH3YmHNEsF5hX6Y6sphulTE5FvJSsxzh8udVNn5W8ZjQG7vVnqOrJ6YvkAimSSE%2FIA4cNNbvRnThzYJm6Eg8Goew6yC6d6LmABPViwiFeWgzJNw1pUf52yQTF0lY6lW%2Fw%2Fxzl9N7qM9z%2BKGW55KDo%2B%2By4AblPrd37BslglP8C6XL2q4zqVvswv0rHHkz50o%2FtG3rGcqIWCQAA&bn=ESCARGOT
line: 0
col: 0
error: {}

**Comment by Psebcool** [comment] 2018-04-08 20:07
Same here !

`Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAJpgyloC_82Za2-jOBSG_8oKaW9Sp_IFG-h-6mUyrdTOdEvV-YhccFKrxEbGtJMd9b-vMc2FXBZ3NKsmrSIg-Pixz7HPe-B7MNacB0djVtb8IBBFcEQOgpI1Mn84YbM6OPoepKUygGSp-IcTd97cu0vtcalYoRoTHAXmWQUH8_PPbGqNBn8c84mof_t8kl7_NfrT_iy762NecM2MUDIbi8mD4Tp4eTlwHUHsOkK7O6oN022L9c7SxfXXXgyvzX0zmcyscWt9qoqm5G5Ex3qqGt0edRfbo415gCgGYYIpXRg8lixXsmBZ1z77pFnBse1QyeDI6MY2rLRQWpiZbX4QPLGyse0gRCGGFIOWYqStrfRBjM2ZFk-u569KP17Ia60mmtd1ZpHEWORuehztl8aMhTFCTkaCl8XtrOLZKD37UhkxZeUVq91dhairks3uuj4Dgg4h-jVYQhwSBGGy8rEw2yxfSMMn3RA2jH6A5BCAFavgMCY77Ozg-oBB3wQ8xDssXKtnrs80e_YhgYeQtPPL5URIzp1z58cX1psYAAjA8vfXoBnxUuR2sL-MmK65ix7Nc1HxS_7ES7cYuvP5_elZdqnk5IbJCQ8WUbUzgGgIUbQIIDu32bkdmi5a37tAp9lpaWeK7IgisBwgjgiiALkganh5y-SjRwTTEBPQA5g37hZ01_1wEMcYJC6Az5sJP2e6qJSQBg4T0NhG3XINnVcmu2pKI06ZlHb9fxLTe1ZmrdXBKSAhAgl1FJdMvw3DLuUQhz2ME86ml6zmeg7hjA5SIIBphOkmBdoLCuxHQeGQS_w4wgTSCDoMMeZpU1VKG6-4hCTpxeVK-9XQRIMI1C6MuCW4YkJ-dOu79iIASX9pdm1d55HvsrTLKyFR6BxxxQvRTN8alRQMeaKzO4wShwRs4UDvxiFKYZPyDHjMRIQjFPUD4so1uOFCjpXO-ZRLr8BY7lk4RgQ4kuuSSd6iHFeVVix_SBthuMfmFSEM-0HSmerbGQIJkctNXUITtdHivjFKewUpWu9_zYibktg3XO1wKExivMBph2N-VIWcc2Y-ju1tgst8u2DYyPbwh3QHWNcdyX-JhlNWsXy7KZhsACUDugFt0Q1XTOfql7-fbUyuSwa0JhmW05ydKFUbXnjpBkC3-L1yZjw8voy9JEEojhPn8RtWMP2jzv5JDtqhC9GGgXiHgZTLWunbNjuZNGfyWE66iVxn2tCqyf-hEOGauzs8m81sXfOVt99e7kYk7Lm7M1Ov-no4E8IwRlYWzGspALtc5rPPQYz78WZrFDvjn7hsK7XXbeY1K-JsxGozSBMhanNjvKBBneD1E60h7tGcWnerG5Y_ropmOJwBKCIJXBDgdyAAMepEuyMI30KAtnnklJflyVy-e1cPKCEhxmTBsVLOD-Rlm5XxWgHRlewnbLaajqGHLkhQsgxO6otAaUxC2i-imrL8KcLAkUR7QxK71qEnSehBEvqSQEoisiRJ9oUEAn8SStckZFvrprlS1SqBx2qJqd1Hw23PpAb1Ior7CCftE6j5WkHeO3mMu0I3nbKyfGNJQUDSk_LHxROTOS9ula6uZ6UV9CPxjReZsz2IkhC0hQS9I8mtkLO3Tgnsg7TKNRXy8dI96bTF922jNTdZa9pjM43IBgfyWyq4_yik29M7XdjlWOAv5eOYbM4H3hOOcE84yJ5w0D3hiPaEI34_jjtb8_DyTonc4xFAjMKQLjcP1-q6lYF33PUwlM2Ae_mw9gbBtqofRHVx1taH6QeQHL9eeS0iLn9nTWFLWN58WxYw34MHm1hbKEDtHwpX3mlgBNt_bEGNMszeFYYwQRGmVsU2slRM8nY8ANsPfXn5F8nMbOz4GQAA
line: 0
col: 0
error: {}
`

**Comment by willyb321** [comment] 2018-04-09 01:08
Duplicate of #205

**Closed by willyb321** 2018-04-09 01:08 UTC
