### ISSUE TITLE
Resistance Cap Missing

### ISSUE THREAD

**Issue by Trollhart** [EDCD/coriolis#324] opened 2018-07-18 10:58 UTC
It seems there was a bug introduced in calculating the resistances on both shields and armour.
Also, the (theoretical) cap at 75% is missing.

Sadly I can not pinpoint the exact point in time when this started Happening, but I noticed it last week.

Below is Frontier's official Explanation of resistance stacking:

 Damage resistance stacking (https://forums.frontier.co.uk/showthread.php/266235-Kinetic-Resistance-Calculation?p=4230114&viewfull=1#post4230114)

---
 Just to clarify how damage resistances work, especially with respect to how multiple sources stack together. 
 It can sometimes be easier to think of a damage resistance as a damage multiplier - for example a resistance of 20% is equivalent to a damage multiplier of 0.8, 50% is equivalent to 0.5, -40% is equivalent to 1.4, etc.

 When multiple sources of resistance are applied, the first step is that these damage multipliers are all multiplied together. Combining the 3 examples above would give 0.8*0.5*1.4 = 0.56 which is a damage resistance of 44%.

 There is an additional step to prevent damage resistances stacking too far however - up to 50% resistance nothing further is done, but the range of 50-100% is remapped to 50-75%. 
 It is impossible to reach or exceed 75% static resistance to a damage type. To clarify with numbers, if you had a lot of sources of 20% damage resistance (Not something you can actually do in game, but it illustrates the maths easily), the final resistance value would end up being:

 1 * 20% => 20%
 2 * 20% => 36%
 3 * 20% => 48.8%
 4 * 20% => 54.5%
 5 * 20% => 58.6%
 6 * 20% => 61.9%
 7 * 20% => 64.5%
 8 * 20% => 66.6%
 9 * 20% => 68.3%
 10* 20% => 69.6%

 There is no cap when stacking resistances that end up being a negative, so in the opposite direction damage increases can get a bit exponential!

 Taking the example in the original report, you have 45.8%, 12.2%, 18.0%, 9.3%, 8.9% and 10%. Converted to multipliers and combined this gives a raw multiplier of 0.290, which is then remapped to 0.395 for a total of 60.5% damage reduction. 

 This mechanic applies uniformly for all Players, AI, and anything else that takes damage. 
 Other sources of temporary damage modification (such as corrosive weapons, or the damage resistance from shield pips in the power distributor) stack multiplicatively with the final damage multiplier after the diminishing returns have been applied. Even allowing for this though, immunity to a damage type is not possible. 
---

**Comment by felixlinker** [comment] 2018-07-19 13:35
Duplicate of #305 however much more detailed. Thanks for the link to the forums post.

**Comment by felixlinker** [comment] 2018-07-19 16:38
I did investigate this situation and was able to come up with a solution on the logical side, and it's rather easy. As Mitch said, the range from 0.5-1 is mapped to 0.5-0.75. But he also said that it's worth to think of resistances as damage multipliers, so I will do this.

The function they're using is:
```js
if (damageMult > 0.5) {
  return damageMult;
} else {
  return 0.25 + 0.5 * damageMult;
}
```
I will try to implement this now.

**Comment by felixlinker** [comment] 2018-07-19 17:11
Sadly, this doesn't result in values that line up with edshipyard or what's displayed ingame.

**Comment by felixlinker** [comment] 2018-07-19 19:17
It seems like diminishing returns are not applied to the overall resistance result. In edshipyard (which never let me down), having one shield booster that gives +20% resistance is superior to having two that give +10% each.

**Comment by felixlinker** [comment] 2018-07-20 09:20
I was able to pinpoint the start of diminishing returns. As it stands, shield generator resistance will not be affected by diminishing returns. Those start at `sgDamageMult * 0,7`, so if your shield booster resistance rating results in a damage multiplier that is smaller than `0.7`, diminishing returns will be applied.

**Comment by willyb321** [comment] 2018-08-18 20:30
Probably

**Closed by willyb321** 2018-08-18 20:30 UTC
Labels: bug
