### ISSUE TITLE
Add Experimental weapon stabilizer support

### ISSUE THREAD

**Issue by SanderMander** [EDCD/coriolis#744] opened 2023-11-05 10:09 UTC
Currenttly EWS logic isn't supported. Add following logic:

- EWS unique module
- If EWS size 3 is installed 5 experimental weapons could be installed
- if EWS size 5 is installed 6 expiremental weapons could be installed

**Comment by alex-williams** [comment] 2024-05-14 15:53
Duplicate of #736

**Closed by alex-williams** 2024-05-14 15:53 UTC
Labels: duplicate
