### ISSUE TITLE
orbis.zone site webserver seems down with Error 521

### ISSUE THREAD

**Issue by fruitcakegsi** [EDCD/coriolis#608] opened 2020-10-16 08:09 UTC

**Comment by felixlinker** [comment] 2020-10-24 10:47
Duplicate of https://github.com/EDCD/Orbis/issues/17

**Closed by felixlinker** 2020-10-24 10:47 UTC

**Comment by dudeisbrendan03** [comment] 2020-12-06 00:33
> Duplicate of [EDCD/Orbis#17](https://github.com/EDCD/Orbis/issues/17)

Do you mind responding to it, it's over a year old

**Comment by felixlinker** [comment] 2020-12-06 07:56
Hey @dudeisbrendan03, I will take this to the duplicate issue.
