### ISSUE TITLE
Farseer/Tani/Dorn not listed as Sensor eng

### ISSUE THREAD

**Issue by luzclasil** [EDCD/coriolis#475] opened 2019-02-22 19:07 UTC
If you check in game options or even INARA, it says Farseer/Tani work with sensors till grade 3, however if you check the options at Coriolis they're not listed as valid options. As well as Dorn, but for him only g1.

Edit: the above is especially true for lightweight sensors, even though the other options seem to have mistakes as well.

**Comment by felixlinker** [comment] 2019-05-17 17:34
Duplicate of #296; closing this one because the other is more general. Thanks for reporting anyways!

**Closed** 2019-05-17 17:34 UTC
Labels: duplicate
