### ISSUE TITLE
Error: Unknown When try to get grades on 4's Plasma

### ISSUE THREAD

**Issue by LueKedowsky** [EDCD/coriolis#720] opened 2022-10-30 21:35 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.124 YaBrowser/22.9.4.863 Yowser/2.5 Safari/537.36
Path: /outfit/federal_corvette?code=A4putpFklndzsuf50w0w0v2a2a10100404040404040404B01K1Kfm2d1O1K1K1K32m73x3w.Iw18ZVA%3D.Aw18ZVA%3D.H4sIAAAAAAAAA42SP08CQRDFRwXCAXLcCcfFP4ByaqKJIbElkcZoZUwsjQmVhbGw0ISChtZKGysLCz%2BAnZYUfggLC0oLtTIWijO%2BIWGjBcle8TKZ99uZ2ZslThLRTxzSv4SkG30Rrw2JegUiGeMN47chyUeHyK1%2FigQ3LvxxDox%2FCnGjL5F86VukoH54FyOqnhRBTvC0IVtD0n9IE%2BXb6BQ%2Bw5EYrw8ht3aGbHcV2TjXzdEOxNGjKZV5lYUMiyxqk6WaBzzBTVOk9Yom3Z7Ims4sSd4zlc4h8Saukzh%2BFwkbbyLVixdAjg2U%2BgPNjYLSvG%2Bgw%2BGd%2FNwyUVHHrW5%2FAMrYQJM2M2VtIJe3DHStG79NoOcuNuZpFOqCI40kZ0161qTPm%2F9IV9fuD1atUPkpC2jKBsrbQAUbKLCBirxjoCOF9Hl7esVo8LxneMX4V%2FoL7hFmK7OANPIVjzSSCpeUjGmR7gGaNMrICo36fgFOkLkIowMAAA%3D%3D.EweloBhBmSQUwIYHMA28QgIwVyKBQA%3D%3D&bn=%D0%9A%D0%BE%D1%80%D0%B2%D0%B5%D1%82%20%D0%9F%D0%92%D0%95
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 84922
error: {}
Модификации

**Comment by felixlinker** [comment] 2022-10-31 08:18
Duplicate of #718 

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:18 UTC
