### ISSUE TITLE
Script Error with Firefox

### ISSUE THREAD

**Issue by NopiSoul** [EDCD/coriolis#91] opened 2017-03-18 11:32 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0
Path: /outfit/anaconda?code=A2putpFklndzsuf57o1616162g2g292900040400030h02024k5nfm05372d2dm9f4C0v424.Iw18gDBPkA%3D%3D.IzAM4yuzgJhCUc5A.H4sIAAAAAAAAA2P%2BJ8XAwPCXBUgIXeRiYOD3%2F%2FX%2Fv0QEGwODiDwfA4PwD6DEf4l%2FviBFzEBCdBYrAwP3LkYGBkEhJgYGFVWgTiYBoB7pX3%2F%2F%2F2dbA1QiEQaUFSn%2FDwIApeMU9V8AAAA%3D&bn=Imported%20Anaconda
Error: Unknown
Details:

scriptUrl: https://s3.amazonaws.com/js-content/34a51713d515c5c7aa.js
line: 0
col: 0
error: null

**Comment by NopiSoul** [comment] 2017-03-18 11:35
And that is not all, Every one of my open Taps of coriolis is not working. The menu is as well not working.

**Comment by cmdrmcdonald** [comment] 2017-03-22 19:40
Firefox has some issues with Coriolis.  You can try to remove the local storage for this site in Firefox, and see if that makes a difference.

```
Firefox Options -> Advanced -> Network:
Offline Data Menu at bottom: remove https://coriolis.edcd.io/ from the list.
The checkbox above should be ticked.
```

**Comment by cmdrmcdonald** [comment] 2017-04-13 22:30
Duplicate of #82

**Closed by cmdrmcdonald** 2017-04-13 22:30 UTC
