### ISSUE TITLE
Failed to import ship from EDSM.

### ISSUE THREAD

**Issue by Jaredcrue** [EDCD/coriolis#224] opened 2018-03-28 01:03 UTC
All other ships work fine except for my anaconda.

Details Below:

If you are attempting to import a ship from EDDI or EDMC and are seeing a 'Z_BUF_ERROR' it means that the URL has not been provided correctly. This is a common problem when using Microsoft Internet Explorer or Microsoft Edge, and you should use another browser instead.

Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.

Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAPqzuloC_81YW2_bNhT-K4OADRuQBryIopQ9JXXSZEhbIyrSvQmMRNtEGVKgqLRe0f8-UrLlW1zT7dDuxZBpn_N9PPejz9HEcB6dTZhs-EkkquiMnkSStaqcXbB5E519jnKpLUBFLv7hSfe9feiO_LPUrNKtjc4iZqOT5dc37NHpjH4__xv-9uYiH_959Yf7UfWnQlW85u5D2WIipjPLTfTly0kPk3Uw8X6YxjLjJbax8uF8AWN5Yx_a6XQeed29Lvj9ujzTR121kne2OTePujX-qT_0TzsWhSgFcYaTeFB4rlipVcWKXr54ZVjFoQPUKjqzpnWCtRHaCDt34ifRE5OtkwMefcRLJuFhyCShlGQDZCdWXH6qpTbcFJdSWH4EIPrRgPgHAl4ZpyGfiYkdGfHU4b3X5sONGhs9NbxpCkdETETJrNCqc_zb1k6EtUJNrwSX1bt5zYurfPS2tuKRydes6f5ViaaWbH7fY0WEnALwazSAw1NCHPxzum6U5dOe7I6aF3BLDzhN9-nZw-QFBttU8B4NY_2Rm5FhH0OYwFNIvEW5mgrFeZcZy-cb5zUMAARg9fsi4664FKW77C9XzDS8Sz3DS1HzW_7EZXRGlt-X_89Hxa1W0zumpjwaUnJv9iUxRHQIFGfb4tpdzVTe231hK15KZymyJ17A6oIxzCjBmcNsakfJ-Xo7NBbnxaSpihlnT05etVJ2gdZy-Y6pDwEFI4kxARuUl8IdYdITxgcDPCWUZh77Vkx43ta1NjYIHq6llodfk19ngA6aLMkoxJ7BaybUZef4JogBSOMNBr3sceAwIWl__7FDt3_ph4C6QtF6sV4KFkPVvhcPhjlCr5ywCisxY8kUd31lfl7XRrNylre-PAVxgZuh26va1HOIQ4zTjkWXy6KxRjy0VpuwQKCbgbCtpHMIDHYIxGSg4q8SFo2AoF0StRdfjwdy0BCYZjGIqWdwxyoWZgFENgMx56rRpumQ0-CLEwwwSrpRZybqmxE4jE1JmtEVtq9-7s7W5UCnoXg_C-5xvQT84ZhePuSmNCEAP4Pq-jmvhC-uAH4LNgzETr6OjY7C9nMr7MKDhowxSZKinVKfl1rXvY7Q5pS67goBTAYOa1P7ARMgmuGtdtPP5m4LWM8weJAEAcQpHCjgUAo-z5LNSuN86KaQV1xxw5aFBh9R-cGKRnwEDRzDDRovmZnqO1b2nTf-uiHWSg2AKB4IkN6KIRUfoq3OPzJa8ZdaWaNlPwa49tNM-LGlFxA88ElC-VBKMUr387njNRPfw4QGWyahCSIbTHrwhSEWnokX8AvhZ_FxCmnfBToK6Wrt_FkUsmAKFKFsM0Av_G66TNQ41Amu0K9KBQQr_G_ZfUZ5Xty5mvm6lfa5zWdn3Th2YUl2NCTfsrA8t_f89_sK3tpX-oGhuGKNzUumDm8svifgzaFj5MZHIXmVt2bCSu71uLpYvBNqfrAUIZhhSgZf9zU5aKXHJNmMtdxyKZm50NXczYClfuJmvuRyXj0xVfLqIB83AxLaj6Se_zUzVa3dlB30WgMRtGoT17Wrz1K31ZKDvxkIbZhZgihAOzRQ0AsdAjdpXHNmc6E-3HZvz7xrWmO4_ZqHwFqzoLs88P-ER_zzeNy7CsTlvRZlwLKUojheGyE6qbHv2_e80x8wvH3ZeUfnpJpu8nVnF-NLROHiZJHb3RJotFjVlM_RzO37nhEBIE78Hj28MnSdj2YJ8CuV1Za5fyEMUuAS1GV7q6R2u51_CRunJHMJ-y-NXOzyoBUAAA%3D%3D
line: 0
col: 0
error: {}

**Comment by Jaredcrue** [comment] 2018-03-28 01:04
I use Google Chrome Exclusively.

**Comment by willyb321** [comment] 2018-03-28 01:04
Does your anaconda have the new engineering?

**Comment by Jaredcrue** [comment] 2018-03-28 01:04
Yes

**Comment by willyb321** [comment] 2018-03-28 01:05
That would be why. You can use beta.coriolis.edcd.io for a (albeit engineerless) import for the moment. 
I will close this now.

Duplicate of #205

**Closed by willyb321** 2018-03-28 01:05 UTC

**Comment by Jaredcrue** [comment] 2018-03-28 01:06
Thank you
