### ISSUE TITLE
Page Rendering Issue in Firefox

### ISSUE THREAD

**Issue by JamesBalisciano** [EDCD/coriolis#454] opened 2018-12-31 01:36 UTC
After the latest update the page no longer renders properly in Firefox v 64.0. Icons are enormous and layout is messed up.

Seems to be an issue in the latest update as it was working fine until the "Click to Refresh" notification appeared, but now looks like this after refresh. I have tried disabling all add-ons, but it still appears the same.

![coriolis](https://user-images.githubusercontent.com/38664065/50553293-4da56200-0c72-11e9-9cfc-8c877b88767c.png)

**Comment by JamesBalisciano** [comment] 2018-12-31 17:07
This appears to be a duplicate of, or related to, issue #441. Mine is not just black, but otherwise the situation sounds similar. Firefox 64.0, also on Windows 10.

I can confirm that CTRL+F5 or CTRL+SHIFT+R will rebuild the page in working order, but unfortunately needs to be done every time I go to the site. (Whether via link or by typing the address into the address bar.)

I tried clearing cache, but there was no effect.

**Comment by willyb321** [comment] 2018-12-31 22:10
Closing this in favour of #441 
Duplicate of #441

**Closed by willyb321** 2018-12-31 22:10 UTC
