### ISSUE TITLE
EDMC with Chrome error

### ISSUE THREAD

**Issue by Chequers2** [EDCD/coriolis#672] opened 2021-07-28 06:27 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAKv3AGEC_-1Y32_bNhD-VwK99MUVKOqn_ZbWyZItWdM46IANg0BLZ5sLJQoUldQt-r_vKCW2ZDuW3WXAMDQvjmXex-Pdx-_u9NW6lmkloLRGf3y1zvI5zwEUz-fW6Kv1TlRQ4Bd9ObZGDo2C0PUDd7B-_ivLwBpZvwErZB6fzWY84ZBra7BCwl_vFnAyfgQh8Nv6BwPpEuJEZGBdwQMIa-QNjDN8xkE17lyxqXlu3chHUGPFHi2ztiwvy5-kTNGlgfVBccRj4hNDn6wRsYd0YK2-BI7jet8Ga6Qxy9gcbkBNIJF5uoFHtvAczw5Dzxl6K1AntIOI0DDchu1F82w_WgH5theRKAo6OLzUik8rLb_3uCGJ2oAYe5UxcSVZeiyY5zlRGHz7c2B9rJjgemkehkMf8a1LDRmiLwodF5UoQbASVDzn2ZSJWDBVx-JDbo20qmBg3SguVYMwsCZCarS9MqsumEoLiURyLOP1_41-fhRFr86-kA6J674C-4avST1_-Gq8c8MO6Ryb_BuMozXjTrNMXubvBS9wI4JrmwcXsigMeWj9rJ-W3jB8kZZXMp_fsrx2sE1LmZ68Mdx8h0fRoN6cXCcfK57n2ySlwZqk7kskvWZl2RtqzyarSHt2J2PHkNwL2pknTkdir9lnnlXZ85F7OEkIafkUeOZrG22ykHpSABxwWYIOFPWDDajmmpwzIeRsdph7dKd7e9mZVULzhOU5pn7GP0MaZ5DyKotZ-sDypD7Ifp5e1-s3pPEHUX8Q9T9O1EZRWzskQlZpabZAqS75FyD4CLPv9iLf8Xy5cQHauCjkcgcuPQ53RwWgm_cKr5W5WO3qgztlrAZIYQYYqFhXSoGONYIf54G7ebJywUGkUynNRWsfzT8O2GsDzyAFxTTHPKdKFrhHEWf3nMeJTO4Lrl-AdlbQE7R4_7S2hZuZwYGpOhtTtkylVC9A0RXUe7P4gulkcZCHTGWyUrEClmj-AL2entbr29AYjLgwioF5w39NSIP9IV2j1UpzY-wO7E4D399W18YsHnOll11lPRMPXLGTa6Z0Vd3vaE5bcuq8JKeXuYZ57Xmv7tC2qjqU2DRCdgffJ66h7a_FNbSjgHbEtTnKh0JzbAN3SP6uZtdrS5jjEa8riytIbKBnEttLvHv9qB1ddBxqmxvt-NvAF8D0LdPQe3LHdteAGIWXZdaQD5r0H0C8lrAynjdOlYcyz8wIm8w7n4xfKurnIHBW0suTc6ZK2DkZkTX5_H9Uy2mn2gXdpB5D304mCe0CHdMWtLuCYNhGwZAdxVnid5wKKLVd38NZqDs2D32ny4rFEstLqlDTamb4hzLjXGFqUY9nemyMN5VO8BmUVVFIpY_DvULDSWO4Uz3T9XR4HJWbtKytN9FLyEupyhrUO7SM37KUbSHNKhCa5fdtKLdX48_R6g6ttvyqK_EcclOYng79FE2nt8qZD-LEE2OzCbyohFDAc1SwBDLIO4mi_bXYQNPd0HUlVixpQuDu93YD0q0hva2glil-mPwnz1FwD81SjevVuO52q7XZabmD7fAnIMT0OaX0UMrV-_r1vnTzPNNqPl9is9JGPPAkQQtx70lo30mco04S1vse-oIsdHa0IBfIudsO57DYPSzH1WZHcsW_nNwu0131gJg3ZWef8YTcIDBxNptBYrwsC0g4EzuYnSyq_L7eYssOC1OC8ljimIEDD0Bxgo2WNufqb3kOqjpRS5cjO-i-BW4a92d0DIbQi9M05aYF7RV9121rvocVAEsTzr7tHX7B0OF0dQslSt9hjYo9NH_rN3SuTdxo-6Xaa4NiaoQssZa8AuzeRmi38HmHCt81R1ymlsTZvNP1HAKvAd2RiwKbMP2XnMY4nXSnkpmZRmTuxKRfXG8Mys9yulVVcawAzYpCSZYsyopr6Bu8W6CNsVqePtlPjH17iwfJEyhMKXiAp-5qP-QnTDiIT8bMMnk0M9-eycxqVtTaMHz6PzWv3nHEu3hLvHNcgLe4fmBeAsvKjJnYWAFSLDPIlFDnLQnf0uiOBCNKR67_u_Xtb3njNLqPGgAA
line: 0
col: 0
error: {}

**Comment by felixlinker** [comment] 2021-08-04 06:51
Am I right to assume that you tried to import a build?

**Comment by Chequers2** [comment] 2021-08-04 12:34
Hello felix,
yes I was importing a build
Browser: chrome Version 92.0.4515.107

------ Original Message ------
From: "Felix Linker" ***@***.***>
To: "EDCD/coriolis" ***@***.***>
Cc: "Chequers2" ***@***.***>; "Author" 
***@***.***>
Sent: 04/08/2021 07:51:42
Subject: Re: [EDCD/coriolis] EDMC with Chrome error (#672)

**Comment by Chequers2** [comment] 2021-08-04 12:37
Hello Felix,
just updated to the latest version of EDMC and everything is fine again

------ Original Message ------
From: "Glyn Jones" ***@***.***>
To: "EDCD/coriolis" 
***@***.***>
Sent: 04/08/2021 13:34:32
Subject: Re[2]: [EDCD/coriolis] EDMC with Chrome error (#672)

>Hello felix,
>yes I was importing a build
>Browser: chrome Version 92.0.4515.107
>
>------ Original Message ------
>From: "Felix Linker" ***@***.***>
>To: "EDCD/coriolis" ***@***.***>
>Cc: "Chequers2" ***@***.***>; "Author" 
***@***.***>

**Comment by felixlinker** [comment] 2022-11-12 11:37
Possibly related to #681

**Comment by alex-williams** [comment] 2024-05-14 16:52
Closing as a duplicate of #754 purely because the OP said the issue was resolved after updating EDMC. I am linking to 754 so that the import string can be analysed as part of the work done to resolve that issue, as the import string still does not work when applied directly to Coriolis. If 754 doesn't reveal the problem and/or fix the issue, I will re-open this as its own issue again.

**Closed by alex-williams** 2024-05-14 16:52 UTC
Labels: cat:import, duplicate
