### ISSUE TITLE
Hull reinforcement package - "hull boost value" bug

### ISSUE THREAD

**Issue by Vega2135** [EDCD/coriolis#562] opened 2019-12-10 11:08 UTC
An engineered "Hull reinforcement package" (for example 1D with "lightweight grade 5 and deep plating" is imported from EDSM and is displayed with "hull boost" current value = 0%, it should be 24% and armour rating displays "97", it should be "223" for my Explo Anaconda. EDSM' import into EDSY works correctly, correct values are displayed.
When I manually change engineering and put "lightweight grade 5 and deep plating" on Coriolis.io, website displays correctly "hull boost" current value= 24% and armour "223", but when I export this modified configuration, values are correct in file, but the "configuration link" in file is not updated. If I copy this configuration link and open it, I get the old faulty value: 0% and 97.
I use Firefox 71.0, but the bug is the same with Chrome.

Here is an example from my ED journal:
{
            "Item": "int_hullreinforcement_size1_class2",
            "Slot": "military01",
            "On": true,
            "Priority": 1,
            "Engineering": {
                "BlueprintID": 128673709,
                "BlueprintName": "hullreinforcement_advanced",
                "Level": 5,
                "Quality": 1,
                "Modifiers": [
                    {
                        "Label": "Mass",
                        "Value": 0.76,
                        "OriginalValue": 1,
                        "LessIsGood": 1
                    },
                    {
                        "Label": "DefenceModifierHealthMultiplier",
                        "Value": 24,
                        "OriginalValue": 0,
                        "LessIsGood": 0
                    },
                    {
                        "Label": "DefenceModifierHealthAddition",
                        "Value": 96.800003,
                        "OriginalValue": 110,
                        "LessIsGood": 0
                    },
                    {
                        "Label": "KineticResistance",
                        "Value": -1.489997,
                        "OriginalValue": 0.5,
                        "LessIsGood": 0
                    },
                    {
                        "Label": "ThermicResistance",
                        "Value": -1.489997,
                        "OriginalValue": 0.5,
                        "LessIsGood": 0
                    },
                    {
                        "Label": "ExplosiveResistance",
                        "Value": -1.489997,
                        "OriginalValue": 0.5,
                        "LessIsGood": 0
                    }
                ],
                "ExperimentalEffect": "special_hullreinforcement_chunky"
            }
        },

**Comment by Freaky** [comment] 2019-12-11 05:30
Seems specific to lightweight engineering - easily reproduced, just Lightweight a hull reinforcement module, reload the page and the value drops until you re-apply it.  The behaviour is not seen with other engineering.

**Comment by alex-williams** [comment] 2024-11-24 23:19
I cannot reproduce this, so closing the issue.

**Closed by alex-williams** 2024-11-24 23:19 UTC
Labels: bug, beta, cat:numbers, cat:import
