### ISSUE TITLE
Import from EDMC

### ISSUE THREAD

**Issue by Filalig** [EDCD/coriolis#226] opened 2018-03-31 08:34 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAANFv1oC_8VZW0_jOBT-K6NI-waVr7n0DegwIMEOSxA8Rm7ithapHTkObHfEf18n6S29uuzMLA8omJxzPvuc71ycH95Ic-71Rywv-ZknMq8PwZmXs0qmk0s2K73-Dy_OlQFhEot_OGn-robNUv2cK5apynh9rzRMG669s8Xan2xqNXvxcl22C4aXZliNxzPv4-PjzJuqrMp5Y-hCT1Wl66d2sX7axodCQCLsk6XCC8lSJTOWtPLJN80yDq1BJb2-0ZUVLLRQWpiZFT_z3lheWTlQW79Uw2HOATlu1A8QCunSaCuYPAh7Etd8yqygk8Gvciwkv1K5004DAgIULo3OhavSqKkomRFKJo88c7N8ra2SeCJGZqDFW2PyRenXW_mg1VjzskwsFjESaaO3ccj3yoyEMUKOrwXPs6dZwZPrePC9MMLu-J6VzVuZKIuczZ5bWx4lvQD-4S2Nwx4lAbQAdmm7lYaPW7hbis4h7QGwpgn0QrpHzx4s5xh0VcAe3qPhQb1zPdDs3QUJ7EFanylvHMIbTy6eb63rMAAQgNX_51y45rlI7Wa_XDNd8oYUmqei4Hf8jedeny7-XrwfD5I7JcePTI65tyTLXl74BKJgGS32bJMbuzWd1f5u-OsnV7k9KbonYsBqgzQIKCD1YZWFhWS9vRkc8_VkVGZJLsYT887r315fVnneBFzF8ycmXx0I7RNMQQf4QriBTVvY-GigRxTDJtjvxIjHVVEobZzMQxp1zK_JryNARxEEAaFhjeCeCdnytfws1VrxG87MIzN8V1ySrfAme8K71WWZ-8D1SOkpk-kujQj1sN9RiBD2j-k8kA3Ogx7tcjhC9DPJINrMBRH8DJPDzQMD4S8gMt4gcntSyUBouzkXHoOwy-O5grVQPM5hEgU-ptSBwu3udrP4IWeS2xo-uygKrVg6iSvRBuPReolhdxOtqq6eY3wiYdCgaHwqSqPFsDJK_zdKlVesYOnuQENblEIHw7985OmE6fEuNkF_q2zs41I8Kw2fHgJ2jrcYEBxWdgDZCcpeOCvsif4cZHNlh5DBLWXREYaiHQy9ZzpVX_5659JskhNukHMztpKHeRwu0rcLYRFA3VjfVHoSdSGCwHaby8ivmWM-G_N1Afk6sq8JLtNd_sO9CHdP3AfBJ3I0Dnsh6TZbYUhO7NjIVoImh_L8gbC029rQhH9HJDW-ms8itjd3yvaUbAdP0ehZ69qONx_EDwmADgm_WBnYmfQfWcY-nWMPlvHNhhz0gtMChG4p2NdOxFyWSj_VecbEKZMXcpxz5znj1zcFLT7batqjf2kd4JRpNoKlVVM2kRIejpS1BBMAgH1U79KOhEWNCDiMozSM8GoGrqXsQRqeXKnpkBkAk5eJS1EH63bh77Zb312gllgOplEQIdxlpz1h6_o69wyFbO9FXBlKKSFwiQI7o8DEj-gxFM5jEsYIQLyEQVxh-PYnhFtzWpwqVZw2X9aXOISilUNouwMXDLar7TLgkRdMaH5ijQ1RBEi4QuC7Ivip0-oqGIIT7KOw221YLtms941LrtnJzcZiTlgAWbvqc7gS687Nl_XF3iWbNSqQKytst-OvHBGt7H-m_AziOGkuTO6r3OxI9-4z874WxX1EOHyptKUG_oKqA_dUHfdrpZr1G4wb2IlQ5DyLKz1iKa-rqw295EnI2XFnExzQpbchcI42G6R-N_nEhuc505cqm9lWO1VvXM8WWC6yt_qO4_jlKKTAt4iWgNqkjJyuoSnphv9Apa82AGxZKipTJyTDpO2ksuMctJ1yjaA-wRsrUCghDXTDAFfl6aYwydWEjUZ3zQ3-YZesp8Id1h1PAEYd6_WwEQv5ugJQac2NGw5M2qrUwYH_PxzPNunw_FmJ1OHCI0TEFukliEbqgaWvyTNv9Ds1J-187Px5ACMYrSgxF-58HvhmxaSL7Y-t7ylWqrQ92u3Arv19HoL7y_nKPJMIySRbpa8f3sROD1YrDjFBzTy8_LbjB2EYUhCeeUYZZl9CwEcYBPXHpkrmiklL1L6tbLYz-fj4F9LVZWuWGgAA
line: 0
col: 0
error: {}

**Comment by willyb321** [comment] 2018-03-31 08:35
Duplicate of #205

**Closed by willyb321** 2018-03-31 08:35 UTC
