### ISSUE TITLE
Error when trying to put engineering on 

### ISSUE THREAD

**Issue by Ph4nt0m-0** [EDCD/coriolis#717] opened 2022-10-29 22:14 UTC
Browser: Mozilla/5.0 (iPhone; CPU iPhone OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6,2 Mobile/15E148 Safari/604.1
Path: /outfit/krait_mkii?code=A2pptkFflidussf52b2b2b1g1g040404045o5op22d1Jm5m53w3x.Iw18eQ%3D%3D.Aw18eQ%3D%3D.H4sIAAAAAAAAA42SO0sDURCFJ6%2FVZJNsdk1ifOJjNSAoWgYEG9EgCpZpba1SWAgaiI2VlYgPsEhhaWGnRUpLf4CFpLawM4honOPMSm6Ryi0Oh%2F3OZc7dWeI%2BIvqJiXRORexmmChVTxK5FXHeg03kt0NECPGKSdZE%2Bh%2FjRM7yB5BvOMLDnDd8T8Txv4Ds%2BDeQU164ixJNVwclGeFhkzzoJoNJ2cOcJF%2BEIMpL3ZCz%2Fyb8qQUgxiVz9EgkPs9A4swlmkyKm1I3o25WHSze6ca9TJFoodwGhjbHBNmxygiRdZuSVsHAZO%2BLFK%2BbWdf6aW4s6bItF3LVFfT%2BvjqkuWySF5qsSgNXxT9JCHd4zfBLwxX56pDhVcOvlCv6Ox9wlzeUR5Ufi4Tq74Cz%2BAkEJYqvEenckE3A%2B3dygLfMzF2RcKEDWLokuyQhtyWSe05Lxab8IcjynImfa8V7semJUUmq83TFvjqAep9fXRGHiGQCAAA%3D.EweloBhBmSQUwIYHMA28RmAVgCwikKA%3D
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 85071
error: {}

**Comment by felixlinker** [comment] 2022-10-31 08:19
Duplicate of #718 

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:19 UTC
