### ISSUE TITLE
Error when trying to change engineering properties on a stored ship build

### ISSUE THREAD

**Issue by Prodromos-alt-f4** [EDCD/coriolis#723] opened 2022-10-31 05:40 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
Path: /outfit/cobra_mk_iii?code=A0pataFalddasdf40s0s241i0902B35e0301016eC26t.Iw18cQ%3D%3D.Aw18cQ%3D%3D.H4sIAAAAAAAAA42QvUoDURCFzyab6G42bhJ3zUZsjInpwloKIpYiFpaCTSoLK0FEC4VYCGIl4gNYWlpaWKSwtPABRFKmsAgYxJ9kxhnRxUgEb3E43Pnm3LkDGgLQS4h0T0VS1zEgXXeA7Kq43FUKKHUMgA2aj8h9keGVd2a3WQXGLk0h7ySIYxRE0JaI23hl9oIus9%2B2gWAhCUydtJg5TuMRuaNk6Y358zlvzxfyXips0sw35O4%2BSv32QVoTNBu1HohYDjHbZ1lgUl1RXVndtDpOUq0%2FpNFkrs49S5JFa1HSsdbDbflJpgLkN%2FMy6WJHIPsHVPgLSv0nyaH1vkkKOkSo43CaylqSRQNHo1%2BtE%2Bp4hJaj6A1t1a6c9nsXPVmsbiqotSXEpSUlTSUPRYz6k1yGL8zBjQVUWnGZ5Fw%2F7lFmwGJ9Kg64Zfw6H8K6hWQ0AgAA.EweloBhBGA2MAsICmBDA5gG2SGF8hRFA&bn=Cobra%3F
Error: Unknown
Details:
scriptUrl: https://coriolis.io/main.js
line: 46
col: 84922
error: {}

**Comment by felixlinker** [comment] 2022-10-31 08:17
Duplicate of #718 

Thanks for reporting!

**Closed by felixlinker** 2022-10-31 08:17 UTC
