### ISSUE TITLE
Cannot import 

### ISSUE THREAD

**Issue by Incal24** [EDCD/coriolis#222] opened 2018-03-21 20:35 UTC
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAFnBsloC_8VYW0_jOBT-KyjSvkHlay68AR0GdmEGEcQ8RiZxi0UaR47DbBfx38dOekvTEk9X7PJQpab-zmef851L3ryJ4tw7nbC84seeyLxTeuzlrC7S53M2r7zTNy_OpQZ-Eot_OGq-10_Nkn3OJctkrb1Tr9JMaa684-XaNzYzwF68Wi_aBc0r_VRPp3Pv_f392JvJrM55Y-hMzWSt7FO7aJ969CAKAYkwICvAs6pM2q3JV8UyDo0tWXinWtVmT6mEVELPzc5j75XltdkCrOEvxVQU_ELmTjYDAgKEVjYXm-tKy5momBaySM4ttpPpS2VQ4mcx0WMlXhubP6R6uS7ulJwqXlWJISMmIm2Am7v5XuuJ0FoU00vB8-xhXvLkMh5_L7WYsfyWVc2vMlGVOZs_trY8Skah_4e3Mg5HlIS-IbAL7brQfNrS7QGdQDoCYAMJjEK6B2cPlxMMuhBwhPcg3MmfXI0V--nCBI4gtXfKG4_wxpXL52vjOwwABGD9_0VYXvJcpOawR5dMVbyJT8VTUfIb_srzRgXt9-Xv43FyI4vpPSum3FvF7d4Q9QncCBdzt8mVOZrKrL8bKdHkIjc3RfdEDFgdkEKAI4qbuKl5_sCKFweJ-ART0LG_3LxpHQ_GaxQElFjbN2LC47ospdJO5iElHfMb-xsGpGWABhmgEAfN6W-ZKFrdVYcqpt1-xZm-Z5rvCC8CtuN8n1xaKKO_O64mUs1Yke4ChGEvXMMhxA8UfeJv84vIIXoOezDoEDH2DgfCT9Ai3tJie1HJQ13wzEmKIIg6sbgAcAjDDRlGPm7C8M6Eof5TPg2rwPeDAPkry8uNiS1YsVbmQDABxK1k3OWs4KaUzs_KUkmWPse1aCN4gEOAMAw6p2-hujhDHChoWTTBICpD_qnWUrllgrB7-9sgjR-wqx8ggAs_WBh7Fn1oNrB54MvE_EzwIt0pk16tAfQQtfWKZ0Q_UtsFK1m6GwqiXjpBn6A4uKW49V0n51JW2lV3BPU9XzYwGz6nDtEXRO0571nG1KH-_tBHqJf5w99rcDAeYdgtHb4f7cGIeVFJ9cDUlOs4ZcVZMc35znanRyv6BH-jLX-39EzNnj7rH9x-Ovkb4a7SW5hqs-MYFngQEdJ0HKZBLi0f4NCd0whstFt2l7lFbVpknnHVRAXApkFn6Ytbul3ahv-HbTtcwebSfJciY_5or9OLUynLFuPjVm8jswaRrVcrCqj1m1Od82G32bznJROKKxfXkxUDDEmEwhUB3GYJt26XdAlcGGnJe3Pnm5lmeDKEgPp4RYCsCRzUbf5d5rIyDf89r0y529Mh0p7CD6kx7tPVXyYxaJF-yAmjUbjVBgf7GsSHZ65mA3iw17aGZCiN-f009iV_FYod3TKl6_plqE00GjYcv_LCqtBkswVRt0zmb2WyLazfa1nCsK1eTVDRfxdU4zhOmiH0ts71jqsOsBkJOoEQ4L0zwr4pg_SiiRwyHqAeDPoPi5f7tG5TKO6Oq2PTbIucZ3GtJizltkYb3ycPopgPT6ymWwbrVL7x6mywV0dbvfK5fVF2zuYthGseRUY8a_uBs30fUx92417zPGfqXGZz07Gn8pWr-fIuzrJXK_dsOKlSQhcXYu_viqmslGYWgi6UEEXr8eWqNJk9l3W25GBPBpwLHDKjSNM-PRq58fxRitRhhAoRIcG6ujS77mxleRSpnYEcivr75stKs6Ey7cX12Hy9-XaCyNliZRG_vDpKc87U0VP7QnEB8-Y917kJdx9i2iTH1ZvTKPJDhM2KlprZ7t1UY4wjs1AXuWR2Sj6FJMDUMPkFZHJoBPEVAAA%3D
line: 0
col: 0
error: {}

**Comment by willyb321** [comment] 2018-03-21 20:43
Duplicate of #205

**Comment by strideynet** [comment] 2018-03-21 20:44
angery

**Closed by strideynet** 2018-03-21 20:44 UTC
