### ISSUE TITLE
EDDI Import not working

### ISSUE THREAD

**Issue by xG0rFx** [EDCD/coriolis#110] opened 2017-05-09 19:46 UTC
Tried with Edge and Chrome for Cobra III, Asp Exp, T6, Viper III, Python and Vulture. Only Vulture worked.

Error page:

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAAAAAAEAF2PQW4DIQxFr1J5zQIzA2ZYdpMucwW3OM1IDEgDVIqiuXtoq2bRrfX%2Bf993WCMEnBVk3gQCnG%2FtWjIo%2BOLUx%2BEO154SBGuRtF%2Bcgq3EnqRCIHLOIVkFH7x%2FFghaQSuNB42T8RNpQgU9p8JZhsXiTIiHgssuo%2FnCqYqC2ritwzhM31MmY8xinfH%2BOemV09oz15e3%2Fg7HT2Kvt9pk%2BwtZPSF5v9DstXnmTpKjjE9%2BWY5xl1r%2FwcfxAIxqG5kCAQAA&bn=The%20Grey%20Area
line: 0
col: 0
error: {}

**Comment by cmdrmcdonald** [comment] 2017-05-17 06:51
Duplicate of #109

**Closed by cmdrmcdonald** 2017-05-17 06:51 UTC
