### ISSUE TITLE
Resting heat is wrong in coriolis ship builder

### ISSUE THREAD

**Issue by cmdrdragsham** [EDCD/coriolis#599] opened 2020-07-29 07:20 UTC
I've built a FDL that has a resting heat of just 13-15%. Yet coriolis shows it as 47.43%
I know resting heat is still beta hence me posting.

**Comment by felixlinker** [comment] 2021-01-31 19:11
Duplicate of #599

**Closed by felixlinker** 2021-01-31 19:11 UTC
Labels: cat:numbers
