### ISSUE TITLE
Planetary Approach Suite and Docking Computer export problem (easy fix)

### ISSUE THREAD

**Issue by mattbledsoe** [EDCD/coriolis#632] opened 2021-01-13 02:13 UTC
[Update added at bottom only 15 min later]

When clicking on the "Stations That Sell This Build" button, the "1I Planetary Approach Suite" is included in the "Stations sells Modules" on eddb. With that included, nothing can match as they are no longer supported as "for sale" by eddb. I spent almost 15 minutes trying to figure out how Jameson didn't sell my build. After I realized the issue was so simple and removed that single Module, I immediately got multiple hits. With so many new players and new coriolis and eddb users (and some of us having played for a while LOL), it may appear the export is broken while it actually isn't. Hopefully simply removing the singular object from  your api will be super-simple. 

Thanks!

I also read the only previous ticket for "Planetary..." and see it was left due to legacy issues from the previous ED versions. Now though, there is no need for this to be included as neither eddb nor the recent ED base package integration with Horizons. (Sure, there's someone out there still running the original, but if they are, I'm sure they won't have any trouble finding this part!)

[15 min update]
Maybe there was a brief eddb issue? After entering this ticket, Jameson DOES now show up as having the Planetary Approach Suite (PLAS). However, when removing only that, one more station shows as having the build. I then did a search for *only* the PLAS and see there are a total, including planetary and not carriers, of 3075 stations that carry it. When entering very common things such as a 1E Supercruise assist or 1E Advanced Docking, 23,000 to 24,000 locations appear. This tells me the eddb database isn't consistent with regards to the PLAS, so my initial suggestion to remove it still appears to be a good idea.

Additionally, while testing this, I noticed the "1E Advanced Docking Computer" is exported incorrectly as the "1E *Standard* Docking Computer".

**Comment by felixlinker** [comment] 2021-01-27 19:19
I can't reproduce this behaviour. For me, the planetary approach suite is not included. Could you give me more details to reproduce this?

**Comment by mattbledsoe** [comment] 2021-01-29 22:48
that's odd that you can't.... It's been a consistent issue I've seen for at
least a couple months. Odd that, huh? Okay. I'll put together an exact
thing for you to reproduce. Thanks!

I recently joined in the EDCD. Would you prefer me go there to give you
info?

**Comment by felixlinker** [comment] 2021-01-31 11:17
Thanks for giving it another go.

I prefer issues. It's better organized here and more public. But I'm happy to take discussions to another platform if it suits you. The one who shares the issue can choose :)

I will close this issue, for now, feel free to reopen it, once you find a way to reproduce the behaviour!

**Comment by bakanisan** [comment] 2021-02-02 18:02
The problem with the Planetary Approach Suite is if you import from EDMC and then export the build to EDDB it will be included if it's on your ship. Create a new build and export it to EDDB afterwards should no longer have the PAS included.

Also I'm not sure if this qualifies as a new issue but since it is mentioned here I'll post here instead.
When exporting the build to EDDB, no matter which Docking Computer is chosen it is always exported as Standard Docking Computer.

**Comment by felixlinker** [comment] 2021-02-03 09:07
Still can't reproduce. I imported one of my builds using EDMC and didn't have the PAS on EDDB afterwards.

Could you send me an import ink I can reproduce this problem with? It is critical that the link is an import link, i.e. has `coriolis.io/import?data=` in the beginning.

**Comment by bakanisan** [comment] 2021-02-03 09:26
[Here](https://coriolis.io/import?data=H4sIAJJqGmAC_8WWb2_aMBDGv8rk11RKAt0f3jHaikrtVpWqLzZNkbEPsHBs62yzsarffbahbQjQUGlSJSRCuOd3j8--Sx7IteZegiX9nw9kUFX6Ug2lMKT_Jetsfo-0MYCkX-RZuHfpoCJ9MjeurLx0glGltCpnoppQWUqKMyAd8l2RvkMPHXKDQqNwq6DvkLHULoivYtSIIjdaKJeTx85DnWu8tCCpBXzCVsCFrw5ws2fudQr7b-DiELhI4Hq18qJZrVCsRrlMyFzRBOAwBcWgdB4RXOmEWh3w0H32cBeCGkvbcrCzXVvJ50CdFWohqVdsHgrQnjrfn_r9F999dwe9-sniglZa8Qlliz-yZJotjHCtNR3PhRluYmuwKrYjRRY6RE_oimuNrdaGMXhEHZsftkWx0j4ce6Qc8lZzgxRdp4VFl0b_BgxlDJdW_IVeyUJJ7Wkr7SbqbqKuSQQ1EwrqtKK9yalQ50lnm7j5Kuw9R7FcI09fN_iCvEBaQdiQqTuL4iZWiilYb4zG9cK7x1q9CsLxWri3llxYh2Linca3gVNFz17UTboFZTXat0FvKac7pKkH6aha1Avabd3xi6C6C6odX3MBks9AAdKnRR99jOJXlpfjqNln0zKtzTHI3jay2I9EMFQgbO3MaWsvJmI3EbtNYmpqDP1YR-bHrbu3H8lRK2BaOdRx9EgJzInwOI4J8tc3vuH5NCUomgkmfjZbhUGUiMXrxEZdP-4ncnBUSODW45QysPEFIj6PDg_hbJv7KXHznbPlQ_Mz9MJC8Bh64ziXn_fT4pgLRo1BTdnceuGgfc6tNbgabGTjJKuRl1qwcKzCCVgK5g6O9hfkPdjwxnIfZeTxVyc9NZqznaxvX56t31jiJQeVxvj11_Pbzd_fwoiL03Mw-jC4HY7SfViu46405drHgjlRgXW0ikmKrMhPsuIk695lX_p5-PR-kMd_rkeYejIKAAA%3D) you go.
I've also tested creating a new identical build in incognito mode and the result is the same: no PAS included just like creating a new one in "normal mode". Copying the import link to incognito mode bring back the PAS so I think the problem is with EDMC itself.
This is not the EDMC github so maybe I should bring this issue over to them?
The Docking Computer issue is an EDDB one though.

**Comment by felixlinker** [comment] 2021-02-03 13:29
Thanks for taking the whole picture into consideration. I think, though, that the issue is on our side. To my knowledge, EDMC simply compresses the loadout from Elite and hands it to coriolis. Coriolis should handle the approach suite correctly. I will investigate this myself first!

**Comment by bakanisan** [comment] 2021-02-03 14:16
Thank you! After looking up PAS on EEDB with Planetary Bases and no Carrier I've found just shy of 3000 Stations having this module. This is simply incorrect as I myself was in one with PAS and don't see it in the list.

I suggest maybe remove the module entirely from Coriolis when exporting to other websites or when importing from EDMC (or EDDI but I don't use it so I can't be certain).

**Comment by mattbledsoe** [comment] 2021-02-05 00:06
Wow, I've taken a couple days off my digital everything (a rare occurrence,
I assure you LOL) and I've only now seen the ongoing conversation.

I agree the PAS should be removed. It's either that or reproduce it
throughout everything, quite a task, especially for something built into
every ship now.

With regards to the Docking computer, I looked at it after putting in the
original ticket for only the PAS (the Docking Computer was a side-issue I
only noticed after testing the PAS export issue and didn't want to re-edit
the ticket again). It's exported from coriolis as item number 899 (made up
numbers, see below) which is the number for the Basic Docking Computer
while it should be 1299 instead (or opposite of that, I can't remember
which at the moment). Both Docking Computers are given the same exported
number code. This is seen in the export of the code I copied and examined
directly from the coriolis export in notepad++. The correct numbers are
easy to find with an EDDB source page opened with only the two docking
computers listed in the page code which couples the numbers with the
devices. That's why I believe this is a coriolis issue, based on the
exported number.

A clarification for my numbers above. I don't have that computer open at
the moment and I'm on my tablet, so my numbers are not the actual numbers
and I simply used the standard 99's as placeholder numbers above. I think
the numbers above were in the 800's and the other in the 1200's but that
was over a week ago.

*** I'm on my tablet because my computer is open and down for the moment
(or evening, depending on how it goes with driver's and grub...) I'm adding
a quad PCIe 3.0 nvme card with three Samsung 970 1tb nvme's! I'll get the
4th next month. I have dual boot but my physical Linux grub drive boots,
not the Win10 loader (two separate physical drives, Linux currently on a
single PCIe x4 lane nvme card as the primary boot drive and Win10 on an
ssd) and this card might have issues with that and might need some kind of
special Win10 drivers. As only the first nvme drive can be bootable, I'm
worried it may behave similarly to an lvm partitioned drive and the other
drives might not be accessable without using the proprietary Windows
driver. There's very little documetation, almost nothing except comments
from other people, about this card, so there will be guesswork. It's very
cool but with some odd kind of early bifurcation and allows for CPU RAID 0
(it's a vendor specific quirk). I'd prefer a full nvme PCIe RAID card with
a hardware controller, but I'm not sure those are available yet at a
reasonable cost and, if spending as much as that would probably cost, I'll
want a PCIe 4.0 version for a future upgrade. With the card I'm installing,
I'm supposed to get almost double the throughput speeds on PCIe 3.0...
about 7GBps per pair! Can't wait to get the benchmarks! I'll also need to
transfer my Win10 install from its SSD to one of the nvme's, but that
shouldn't be difficult with a simple dd and gdisk. Anyway, fun stuff!

**Comment by mattbledsoe** [comment] 2021-02-05 08:25
Okay, I'm back online.

I rechecked what I'd said earlier about the Standard Docking Computer and
the Advanced Docking Computer. Tonight I used the coriolis json export as
suggested and got a look at the values used there. The exports I see are I
using json and look correct with expected differences. (However, I can only
tell that's correct for your page although I suspect it's correct elsewhere
too. But I have zero experience with the codification of the shared ship
info.) I created two identical stripped down ships with different Docking
Computers and looked at the code that may have been generated by the "Find
stations that sell..." for the eddb export, did a comparison of the (to my
eyes) random chars and didn't see any differences when I expected to see
differences, so maybe that is a place to look at? I looked at the coriolis
full length url and did see a difference there, as expected.

I then looked at eddb's interpreted page and saw when either kind of
Docking Computer was sent, the page always shows only the "Standard". I
manually played with the url and with
https://eddb.io/station?m=890,1810
I can see both Advanced and Standard show up in the search.

890 = "Standard Docking Computer"
1810 = "Advanced Docking Computer"

So I know it's either the coriolis export that's incorrect (although the
other two export types, json and the url, are correct) or the eddb api
isn't parsing the import correctly.

Thanks!

BTW, I never said, but I've always been loved coriolis and it's always been
loved of my three favorite tools. Thank you for all the awesome work!

***The new quad nvme card is beautiful and absolutely no issues
transferring anything at all. Not only did Linux come up and recognize the
drives automatically, but even Win10 moved and expanded into its larger
nvme without complaint and can see all the drives! It was suspiciously easy
hmmm. I did some speed tests between 3 versions of nvme drives and saw some
expected results and several unexpected results. The fastest two nvme
cards, Samsung 970 Evo Plus's, are reading at a solid 3.5GBps. The second
drive, a Samsung 970 EVO (yes, I bought the wrong card on accident and
missed the return date), was just below that at 3.3GBps. However, my poor
Intel 600p though, it didn't fare very well at a max of just under 800MBps
read. (I had to find something to fill the fourth slot!) I tell myself it's
more stable though... Hmm. The write speeds of the cards all have roughly
equivalent lower and expected speeds. I was able to dd a 1TB EVO to a 1TB
Evo Plus in only ~400 seconds, so that was impressive.
I haven't tried the striped write yet... That may be very cool! I'd also
like to try the new 980 Pro, but it's just not worth it yet.

**Comment by alex-williams** [comment] 2024-05-15 08:41
This was resolved in this commit https://github.com/EDCD/coriolis-data/commit/365412375ea8ed591e87025bae5848ef079333b3 It has been merged to Dev and is live at https://beta.coriolis.io. The data was wrong, with the Supercruise Assist Module having the EDDB Id of the PLAS against it inside coriolis-data and the Advanced Docking Computer having the same EDDB Id as the standard one. This caused any export with an SCA in it, to look for the PLAS in the export link and it caused any export with an Advanced Docking Computer, to simply look for a standard one. Closing this issue, as it will be deployed to the live site soon. However, I have created #756 which seeks to improve the export link generation, so that it does not include default core modules.

**Closed by alex-williams** 2024-05-15 08:41 UTC
Labels: bug, cat:import
