### ISSUE TITLE
Experimental Effects are not considered for the Material Export List

### ISSUE THREAD

**Issue by WaldemarLehner** [EDCD/coriolis#619] opened 2020-12-01 18:39 UTC
### Description
Materials required for an experimental effect are not added to the "Materials Needed For this Build" - Popup.

### How to reproduce
Create a new build and add one engineered module that supports experimental effects.
In this case I went with this build: https://s.orbis.zone/9y_1

Note the required materials are just 2 x Phosphorus. This is expected.

Now, I add an experimental: https://s.orbis.zone/9y_3
**The required materials still only show 2 x Phosphorus.** 
Expected result:
```
Phosphorus: 2
Worn Shield Emitters: 5
Flawed Focus Crystals: 3
Compound Shielding: 1
```

**Comment by felixlinker** [comment] 2021-01-31 15:35
Duplicate of #466

**Closed by felixlinker** 2021-01-31 15:35 UTC
