### ISSUE TITLE
3D SHIELD GENERATOR with G5 Enhanced Low Power wrong value

### ISSUE THREAD

**Issue by DemonBDC** [EDCD/coriolis#603] opened 2020-09-02 04:37 UTC
there's a mismatch in the Ship Builder with the Maximum Hull Mass for the 3D Shield Generator engineered with G5 Enhanced, Low Power. The maximum hull mass is listed wrong as 388T instead of the correct 413T value.

**Comment by felixlinker** [comment] 2020-09-02 07:29
But it is correct without modifications?

**Comment by DemonBDC** [comment] 2020-09-02 07:43
Yes, the value is correct without modifications

**Comment by felixlinker** [comment] 2021-01-31 12:16
Duplicate of #473

**Closed by felixlinker** 2021-01-31 12:16 UTC
Labels: bug, investigation-needed
