### ISSUE TITLE
Engineer configuration panel does not retain modifications

### ISSUE THREAD

**Issue by Sheuzzo** [EDCD/coriolis#372] opened 2018-09-11 14:47 UTC
as in topic, when manually inserting engineering values they revert to previous number when the window is closed.

https://youtu.be/g9nZ4WkRyew

**Comment by felixlinker** [comment] 2018-09-11 14:52
Could you please provide me with a link to the build. My best guess would be that this has to do with special effects. There is an issue already known (cf. #249).

**Comment by Sheuzzo** [comment] 2018-09-11 15:00
https://coriolis.io/outfit/fer_de_lance?code=A0pktjFeljdtsjf3-----040404---p2----.Iw18aQ%3D%3D.Aw18aQ%3D%3D.H4sIAAAAAAAAA%2BP958HAwPCXFUj8mQMkuBf8%2Ff9fEESoHONkYJCPB4r95%2FvniqKIfwuQKWRQysAgcQSoiNvqP1APiJDnFmJgUAGx%2FvMTrYcJrkf4ny9cTw6QYPr1%2B%2F9%2Ftg0sQOUmzAwMgleAhOhSKaDyFexAczhBbvsPJBgAJzP1I8YAAAA%3D.EweloBhAOEoUwIYHMA28QgIwV0A%3D

https://s.orbis.zone/dfa

**Comment by felixlinker** [comment] 2018-09-11 15:04
As I guessed: values don't get reset but special effects mess them up. For instance setting integrity manually works just fine.

Duplicate of #249

**Closed by felixlinker** 2018-09-11 15:04 UTC
Labels: investigation-needed
