### ISSUE TITLE
Can't import ship

### ISSUE THREAD

**Issue by Nosttromo** [EDCD/coriolis#227] opened 2018-04-01 21:40 UTC
No matter what I do, or on what browser I try, I get this error. I tried on chrome, firefox, edge, and vivaldi, and had no success.

Jameson, we have a problem..
Failed to import ship

If you are attempting to import a ship from EDDI or EDMC and are seeing a 'Z_BUF_ERROR' it means that the URL has not been provided correctly. This is a common problem when using Microsoft Internet Explorer or Microsoft Edge, and you should use another browser instead.

Please note that this site uses Google Analytics to track performance and usage. If you are blocking cookies, for example using Ghostery, please disable blocking for this site and try again.

Create an issue on Github if this keeps happening. Add these details:
Browser: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.189 Safari/537.36 Vivaldi/1.95.1077.60
Path:
Error: Unknown
Details:
scriptUrl: /import?data=H4sIAAfDt1oC_-VaXVPjuBL9K1Sq9o1NWbJky7wBgWF2YZci3OG-uTS2kqhwLJcsM5s7Nf_9tux8OU5iBeZubdXlARITdR9Jp093S_k-mGghBhcTnpXifCDTwQXC54OMV3kyu-KLcnDxfTDOlEF-PJb_Ebh-X321jzz7OlM8VZUZXAxKw7URenC-evYHn4PlwXj9PG8eGFGar9V0uhj8-PHjfDBXaZWJ2tGlnqtK21cvSr9-zh-1mmpRljF8Rk5kwo1Uef3JPyszkcbIfHorRZY-LwoRj8RE5Il4qD8r9J3gmZk9VJmRRQbv7bBUlkXGF194VlkkCIdDn_0C0N6aJ3iIQz8MANU-Bzd_FZkq5Zt4EqWE6YKzPUZ_9ckwiLaMoqFPgsiP1j_sgP3fZS6MTI5bR3RIaMs6ooTiAyYfeFnus4Lp0PNaVjA9YOJ5JvS8B5U_DLdn7A2jACO7uSKfwqSaxV-9_gwk8z0PI2_z_xVXRCZycfab4DlY0yKRhbgXbyIbXJDV--VHG67EsMtvi1FlgEwrKllfe1jNPBL5AVnT8DLnicpTHi8tfdI8FQjcqnxwYXQFAwstlZZg-wJt5manNRIJz5B1dNxlEIQhjdYu62ENjbTQ8U0mjTjBIXZ0iHYcPtuZnezN7_cW-pgSvOPtUX0T-hHIAeSbqdzN403Ng2uVLeO_xy_xQrzxuxxclUbNZVmLRHxlbTu5vtVgZTyTEzPSENvvVZ_b8ejPwsg5zw7EHCVDxlohRwk7JAWfcyOmDdy9EtAKXm_I6Inx73u78e8fsFBv50jzby5IrBj1hD3yumF_KzKZwGTPbrkuRZ0rWrFPd2If1jq-V_n0iedT4RD4AQGlX9MF1ja-g6np1O53ndaC-DqDlaIHGONtJkhQFFI_Ap9lAZBgt3fJsXweT8o0nll1GlzkVZbVVKtE9szz136GA2Sfei3Iq8E1YNoA9nspzmgYRtb3vZyIcVUUShsn92hLt6z7rfHbCHDvkgVRiHyL4IHLvAnV8r1B1gwHzTdP3IiPEbuxBTH7KPRE6fmB1IbYkLazOWI06rN5RAd-7URvRN-jAkHHDHlPCAe76-UFfREcdCP4JnuTmp89QKlXVa-78Yt34rdZpngktVPeDojHSIuMSwMn8RAFlIUugdtMLVZvQttKVqSbAH4ECpvf1Fe3FEXZGvRqYLyuOh6E4RnIHo4_qSx1S1WQVaFC5HpxWRRa8WQ2rmQTBj1VQYh91BbAxlTbTh8G4rMaRU0nKAa1_FoZpT8WzOU1L3iyn-NBJ5iDo4FXPolkxvV0XxwTsmuLHIqX8aI0Yn4M2CkpeGntCLRTrL0IXsCa_iRsS2vHsO1Tqx59YF19gCbibPRNZFl_ct-lV_y4pOIqdzjl-6gtGB2jVjqIq3RgwqIN9W3omPeS3uaumwl8TEKvuvhga3Y0P-DOzoX0WII4QinSiUPSwwEv6nLgTkCGgApGOjGgXuX4SimIntQtSWy1Ius9L2ozdrf94zXelswFjHjIIVEUGwczOZ2tYmiVLJ54yt8tjke3lnq7W3ti_R9GoH4tA9ijh7R1LPJS6Wc7OTNOeH6ZTzPhzLgercBdntwLeXY9E1U-7SNKgwxK0-nMvAj724ko0LS2iNKYKWuWMOdygvqej-taCZrH4vPIcygKKIvCjW87C1hAA0tcW4hfZs4tejMC_e0-7XinmUbQou_x-gLUKj30Hrfob3ZrjzhRTYrQ5eAlCBjuNGzjRKmiseHaYjKICgRF9hoDblpUt6ZxRwOvIWrVE09aXWP_IVcURt5mEfwNgHfVeU7Hpu6adjzrdcx85LSVdKwFpwktgXYxaM-Ksff0aT4ZhqyNhOJDp74QMfDyk8h_Wie6tjg2GuTazPZ1ymjIdg6DUBht_3zghLmzsVAW_dTcsnu-vJ4xVC22YKyXUpaOtQgO2qcnu9a2ChKnztVjDvVIWTuJXxtibwqROoiJq4oEQRgg1EL_JAou7Yn11llZP2wCeQdHawC0kSAHEQ9DH7MWgJFW9nQ4N1plSzS1NdTGsrSzdw096q-hhK5QakWNDh_DEddjOIxCj679s2awy174NGjvxdhAF8X1lUoX0M8k9pRiYasyYFZ8mb7Z8Ok_TUA-pWHTzdeAIndAAKldPY2E4TIT6bjSE56IFZZnmS8cliXyw_W6IM8VhkciurMvI5UA8afXal5UxlIVlATq77SXpn5E1iTdvuXsPVLBrI3gyt5pXvFFY8I5uBlMxfq3C3YHgAslc4P-J33Dh9NZwIa-3zLgoyDs0-E9F31PfA6t4KxPhB-A4SeW98AMtNmXu8LULfdY5q_39aW2pWaltTDHGLrFDqgnO7uD_5m7E0Jf3t4dzGiwnYDp_91WudxihohtnS9bHJe5kf_KX3P1LR_PKpPCXzcMlGLmd0A4KtrWlaYF8QgCMueP1sDyqw0nLQcKcCOtLSjUReMZ9YMWlKZ8aQ5jmszrubYzmAQ0ZB0cwT8Eh0NrF0Y-QrSF498iV6tEd8VLmTgyFHuRhzoYmMtaYIrbGK4zVaUrEFtLgfqZAXyv28svIFwi-6Jk4nCJwDAh4eZKsh71aDvLLzKxtwAOTfWPzpcvYFRZn0PAszxBCoXLJ0tVgZqvrAseK6sbZfs-mEFta2ER6oURC7e-RhRFQeTB8_OBUYbb2ydMUMSwD9FV5Zniub3RCQmjVg7_C9TS9IkBJQAA
line: 0
col: 0
error: {}

**Comment by willyb321** [comment] 2018-04-01 21:44
Duplicate of #205

**Closed by willyb321** 2018-04-01 21:44 UTC
