### ISSUE TITLE
ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by texaspete** [EDCD/coriolis#337] opened 2018-08-03 20:19 UTC
Browse to coriolis.edcd.io and click on any ship to open a default build. Resize the browser window. I get an error where the build should be:

Jameson, we have a problem..

ResizeObserver loop limit exceeded.

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36
Path: /outfit/adder
Error: Unknown
Details:
scriptUrl: https://coriolis.edcd.io/outfit/adder
line: 0
col: 0
error: null

2.9.17 - 2018-07-26

CMDR texaspete

**Comment by willyb321** [comment] 2018-08-03 22:45
Duplicate of #208

**Closed by willyb321** 2018-08-03 22:45 UTC
