### ISSUE TITLE
Site not working in Chrome/Safari mobile

### ISSUE THREAD

**Issue by Jefzwang** [EDCD/coriolis#573] opened 2020-03-11 18:07 UTC
1) Attempting to access the site via Google Chrome on my iPhone returns a Cloudflare error 552.  This error has been independently encountered by my friend using Chrome on his Android phone as well.  

![E15A2F02-1CC7-42D5-A609-A6438F6F3672](https://user-images.githubusercontent.com/62071898/76448716-06dbed80-6388-11ea-90cd-0cd6e3c2a630.png)

The site works fine in the desktop Chrome browser.  

2) Attempting to access the site via Safari on my iPhone yields a bizarrely-formatted home page: 

![8DFB0625-AC2C-44AC-9AF6-10DCCDFFD78C](https://user-images.githubusercontent.com/62071898/76448861-4571a800-6388-11ea-9ed6-44169e643794.png)
![9755CCC5-9BBD-4B78-B25C-6C3A0FBB5B67](https://user-images.githubusercontent.com/62071898/76448865-46a2d500-6388-11ea-8632-6750e1756970.png)

Clicking one of the links yields a similarly incorrectly formatted and unusable interface: 

![6D6D8D83-DB8C-4ADD-96CC-6B01605A40CD](https://user-images.githubusercontent.com/62071898/76448922-63d7a380-6388-11ea-9a52-c1981f3baac6.png)

The site was working fine on Safari as of 12 hours ago (10MAR2020).  The formatting issues started after refreshing the page post-update.

**Comment by willyb321** [comment] 2020-03-11 18:18
Duplicate of #572

**Closed by willyb321** 2020-03-11 18:18 UTC
